# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6079264feebb449e0e8d7df42a9618e8477f2f9a2cb586f1bd108fd6d3e483fc
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.14.1"
end
