# frozen_string_literal: true

source 'https://rubygems.org'

gem 'html-to-markdown', '~> 3.6.0.pre.rc.4'
gem 'rspec', '~> 3.13'
gem 'rubocop', '~> 1.86'
gem 'rubocop-rspec', '~> 3.9'
gem 'faraday', '~> 2.0'
