#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bf4be9a98f2dfc584c42e36fda42ef5d9b0969715e7f93c5112b9d524a7f917
# To regenerate: alef e2e generate
# To verify freshness: alef verify
# Installs the PIE PHP native extension and runs main.php.
set -euo pipefail

VERSION="3.15.0"
PKG="xberg-io/html-to-markdown"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Require PIE.
if ! command -v pie &>/dev/null; then
  echo 'error: pie is required. Install via: composer global require php/pie' >&2
  exit 1
fi

echo "Installing $PKG version $VERSION via PIE..."
pie install "$PKG:$VERSION"

# Locate the installed extension.
EXT_DIR="$(php -r 'echo ini_get("extension_dir");')"
EXT_NAME="html_to_markdown"

# Determine OS-specific extension suffix.
case "$(uname -s)" in
Darwin) EXT_SUFFIX=".dylib" ;;
*) EXT_SUFFIX=".so" ;;
esac

EXT_PATH="$EXT_DIR/$EXT_NAME$EXT_SUFFIX"

if [ ! -f "$EXT_PATH" ]; then
  echo "error: extension not found at $EXT_PATH" >&2
  exit 1
fi

echo "Running main.php with extension=$EXT_PATH ..."
php -d "extension=$EXT_PATH" "$SCRIPT_DIR/main.php"
