# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8b3e3f77d8a143057014a8513b0c79f2580124b20b47a68e97fe5dc86baac328
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: smoke
defmodule E2e.SmokeTest do
  use ExUnit.Case, async: false

  describe "smoke_empty_string" do
    test "smoke_empty_string" do
      {:ok, result} = HtmlToMarkdown.convert("")
      assert String.trim(result.content) == ""
    end
  end

  describe "smoke_simple_heading" do
    test "smoke_simple_heading" do
      {:ok, result} = HtmlToMarkdown.convert("<h1>Title</h1>")
      assert String.contains?(to_string(result.content), "\# Title")
    end
  end

  describe "smoke_simple_paragraph" do
    test "smoke_simple_paragraph" do
      {:ok, result} = HtmlToMarkdown.convert("<p>Hello World</p>")
      assert String.trim(result.content) == "Hello World"
      assert result.content != ""
    end
  end
end
