# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ebd743234348ca65d1a270b8fb48fc8038c7b76fa930ce21ad192f3820a2c7c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: structure
defmodule E2e.StructureTest do
  use ExUnit.Case, async: false

  describe "structure_code_block" do
    test "structure_code_block" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<p>Example code:</p><pre><code class=\"language-rust\">fn main() { println!(\"Hello\"); }</code></pre>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 2
    end
  end

  describe "structure_deep_nesting_h1_h2_h3" do
    test "structure_deep_nesting_h1_h2_h3" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<h1>Top Level</h1><p>Top intro.</p><h2>Mid Level</h2><p>Mid content.</p><h3>Deep Level</h3><p>Deep content.</p>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 5
    end
  end

  describe "structure_h1_h2_nested_group" do
    test "structure_h1_h2_nested_group" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<h1>Chapter One</h1><p>Chapter intro.</p><h2>Section One</h2><p>Section content.</p>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 3
    end
  end

  describe "structure_heading_paragraph" do
    test "structure_heading_paragraph" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<h1>Title</h1><p>A paragraph of text.</p>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 2
    end
  end

  describe "structure_list" do
    test "structure_list" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<p>Items:</p><ul><li>Alpha</li><li>Beta</li><li>Gamma</li></ul>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 2
    end
  end

  describe "structure_multiple_headings" do
    test "structure_multiple_headings" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<h1>Main Title</h1><h2>Section One</h2><p>Section one content.</p><h2>Section Two</h2><p>Section two content.</p>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 4
    end
  end

  describe "structure_sibling_h1_groups" do
    test "structure_sibling_h1_groups" do
      options = %HtmlToMarkdown.ConversionOptions{include_document_structure: true}
      {:ok, result} = HtmlToMarkdown.convert("<h1>Chapter One</h1><h2>Section A</h2><p>Section A content.</p><h1>Chapter Two</h1><h2>Section B</h2><p>Section B content.</p>", options)
      assert result.content != ""
      assert result.document.nodes != ""
      assert length(result.document.nodes) >= 4
    end
  end
end
