packages:
  - crates/html-to-markdown-node
  - crates/html-to-markdown-wasm
  - packages/typescript
  - e2e/node
  - e2e/wasm

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - wasm-pack
