// This file is auto-generated by alef. DO NOT EDIT.
using System.Threading.Tasks;
using Xunit;
using HtmlToMarkdown;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: smoke.</summary>
public class SmokeTests
{
    [Fact]
    public void Test_SmokeEmptyString()
    {
        // Empty string produces empty output
        var result = HtmlToMarkdownRs.Convert("", null);
        Assert.Equal("", result.Content.Trim());
    }

    [Fact]
    public void Test_SmokeSimpleHeading()
    {
        // H1 heading converts to ATX markdown
        var result = HtmlToMarkdownRs.Convert("<h1>Title</h1>", null);
        Assert.Contains("# Title", result.Content.ToString());
    }

    [Fact]
    public void Test_SmokeSimpleParagraph()
    {
        // Simple paragraph converts correctly
        var result = HtmlToMarkdownRs.Convert("<p>Hello World</p>", null);
        Assert.Equal("Hello World", result.Content.Trim());
        Assert.NotEmpty(result.Content);
    }
}
