// Generated by alef. Do not edit by hand.
// alef:hash:3438f9fbb970f773f3c45f0a76ef480a632b0dfc5f03c8dc6bcca0e4f2e5e5f9
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package dev.kreuzberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init {
        System.loadLibrary("htm_jni")
    }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI trait-bridge external funs — implementations are Rust JNI shims.

    // Destructor external funs for handle-only opaque types.
    external fun nativeFreeVisitorHandle(handle: Long)
}
