// Generated by alef. Do not edit by hand.
// alef:hash:587d200c95438abc2158e73f50ad7a072bde7ec6ef55df8510c6b9bc5343923c
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package dev.kreuzberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init {
        System.loadLibrary("htm_jni")
    }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI trait-bridge external funs — implementations are Rust JNI shims.

    // Destructor external funs for handle-only opaque types.
    external fun nativeFreeVisitorHandle(handle: Long)
}
