// Generated by alef. Do not edit by hand.
// alef:hash:34fbdb4c0b2fb7f62ac67874a0b159460164b065dffdca16159d5338edb45346
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package dev.kreuzberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init {
        System.loadLibrary("htm_jni")
    }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI trait-bridge external funs — implementations are Rust JNI shims.

    // Destructor external funs for handle-only opaque types.
    external fun nativeFreeVisitorHandle(handle: Long)
}
