// Generated by alef. Do not edit by hand.
// alef:hash:c4123217bb42e6cbe7cc59851037f301994cdb660a4a2934d8b056b2b5fc5adf

package dev.kreuzberg.android

class HtmlToMarkdownRsBridgeException(message: String?, cause: Throwable?) :
    RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
