// Generated by alef. Do not edit by hand.
// alef:hash:4dc99abf2bf36539437457be6b18ac3381ea7d2c2c95cfc377ab43c25238c712
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg.android

/**
 * Output format for conversion.
 *
 * Specifies the target markup language format for the conversion output.
 */
enum class OutputFormat {
    /** Standard Markdown (`CommonMark` compatible). Default. */
    @com.fasterxml.jackson.annotation.JsonProperty("Markdown") MARKDOWN,
    /** Djot lightweight markup language. */
    @com.fasterxml.jackson.annotation.JsonProperty("Djot") DJOT,
    /** Plain text output (no markup, visible text only). */
    @com.fasterxml.jackson.annotation.JsonProperty("Plain") PLAIN;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            MARKDOWN -> "Markdown"
            DJOT -> "Djot"
            PLAIN -> "Plain"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): OutputFormat =
            when (value) {
                "Markdown",
                "markdown" -> MARKDOWN
                "Djot",
                "djot" -> DJOT
                "Plain",
                "plain" -> PLAIN
                else -> throw IllegalArgumentException("Unknown OutputFormat value: $value")
            }
    }
}
