// Generated by alef. Do not edit by hand.
// alef:hash:f8026f1bd5c957d54c05eab1d6eace9df28d99dae19dfe307c25ea4ef8344e6b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.android

/**
 * Text directionality of document content.
 *
 * Corresponds to the HTML `dir` attribute and `bdi` element directionality.
 */
enum class TextDirection {
    /** Left-to-right text flow (default for Latin scripts) */
    @com.fasterxml.jackson.annotation.JsonProperty("ltr") LEFT_TO_RIGHT,
    /** Right-to-left text flow (Hebrew, Arabic, Urdu, etc.) */
    @com.fasterxml.jackson.annotation.JsonProperty("rtl") RIGHT_TO_LEFT,
    /** Automatic directionality detection */
    @com.fasterxml.jackson.annotation.JsonProperty("auto") AUTO;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            LEFT_TO_RIGHT -> "ltr"
            RIGHT_TO_LEFT -> "rtl"
            AUTO -> "auto"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): TextDirection =
            when (value) {
                "ltr" -> LEFT_TO_RIGHT
                "rtl" -> RIGHT_TO_LEFT
                "auto" -> AUTO
                else -> throw IllegalArgumentException("Unknown TextDirection value: $value")
            }
    }
}
