// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:602dff71187141788025192a9fca1e3288feb1abd857a11d46edaa3834499870
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: smoke

use html_to_markdown_rs::convert;
use html_to_markdown_rs::ConversionOptions;

#[test]
fn test_smoke_empty_string() {
    // Empty string produces empty output
    let html = r#""#;
    let options: ConversionOptions = Default::default();
    let result = convert(html, Some(options.clone())).expect("should succeed");
    let _content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert_eq!(_content.to_string().as_str().trim(), r#""#, "equals assertion failed");
}

#[test]
fn test_smoke_simple_heading() {
    // H1 heading converts to ATX markdown
    let html = r#"<h1>Title</h1>"#;
    let options: ConversionOptions = Default::default();
    let result = convert(html, Some(options.clone())).expect("should succeed");
    let _content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", _content).contains(r#"# Title"#),
        "expected to contain: {}",
        r#"# Title"#
    );
}

#[test]
fn test_smoke_simple_paragraph() {
    // Simple paragraph converts correctly
    let html = r#"<p>Hello World</p>"#;
    let options: ConversionOptions = Default::default();
    let result = convert(html, Some(options.clone())).expect("should succeed");
    let _content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert_eq!(
        _content.to_string().as_str().trim(),
        r#"Hello World"#,
        "equals assertion failed"
    );
    assert!(!_content.is_empty(), "expected non-empty value");
}
