// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b3742ed8d1c52918c45d7137b6634daec980bd917c4e64ccc9bb0baf888e6aa6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: visitor

use html_to_markdown_rs::convert;
use html_to_markdown_rs::visitor::{HtmlVisitor, NodeContext, VisitResult};
use html_to_markdown_rs::ConversionOptions;

#[test]
fn test_visitor_audio_custom() {
    // Visitor replaces audio element with custom output
    let html = r#"<p>Listen to this: <audio src="podcast.mp3" controls></audio></p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_audio(&mut self, _ctx: &NodeContext, _src: Option<&str>) -> VisitResult {
            VisitResult::Custom("[AUDIO: podcast.mp3]".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[AUDIO: podcast.mp3]"#),
        "expected to contain: {}",
        r#"[AUDIO: podcast.mp3]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Listen to this:"#),
        "expected to contain: {}",
        r#"Listen to this:"#
    );
}

#[test]
fn test_visitor_audio_skip() {
    // Visitor removes audio elements from output
    let html = r#"<p>Background music:</p><audio src="music.ogg" autoplay></audio><p>Enjoy!</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_audio(&mut self, _ctx: &NodeContext, _src: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Background music:"#),
        "expected to contain: {}",
        r#"Background music:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Enjoy!"#),
        "expected to contain: {}",
        r#"Enjoy!"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"music.ogg"#),
        "expected NOT to contain: {}",
        r#"music.ogg"#
    );
}

#[test]
fn test_visitor_button_custom() {
    // Visitor replaces button with bracketed text
    let html =
        r#"<p>Confirm action: <button type="submit">Click me</button> or <button type="reset">Cancel</button></p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_button(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("[BTN:{text}]"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[BTN:Click me]"#),
        "expected to contain: {}",
        r#"[BTN:Click me]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"[BTN:Cancel]"#),
        "expected to contain: {}",
        r#"[BTN:Cancel]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Confirm action:"#),
        "expected to contain: {}",
        r#"Confirm action:"#
    );
}

#[test]
fn test_visitor_button_skip() {
    // Visitor removes all buttons from output
    let html = r#"<p>Actions available: <button>Save</button> <button>Delete</button> <button>Export</button></p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_button(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Actions available:"#),
        "expected to contain: {}",
        r#"Actions available:"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Save"#),
        "expected NOT to contain: {}",
        r#"Save"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Delete"#),
        "expected NOT to contain: {}",
        r#"Delete"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Export"#),
        "expected NOT to contain: {}",
        r#"Export"#
    );
}

#[test]
fn test_visitor_continue_default() {
    // Visitor continue action preserves default conversion
    let html = r#"<p>Hello <strong>World</strong></p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_strong(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Continue
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"**World**"#),
        "expected to contain: {}",
        r#"**World**"#
    );
}

#[test]
fn test_visitor_custom_blockquote() {
    // Visitor replaces blockquote with custom format
    let html = r#"<blockquote><p>A wise quote.</p></blockquote>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_blockquote(&mut self, _ctx: &NodeContext, content: &str, _depth: usize) -> VisitResult {
            VisitResult::Custom(format!("QUOTE: \"{content}\""))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"QUOTE:"#),
        "expected to contain: {}",
        r#"QUOTE:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"A wise quote."#),
        "expected to contain: {}",
        r#"A wise quote."#
    );
}

#[test]
fn test_visitor_custom_emphasis() {
    // Visitor replaces emphasis with custom output
    let html = r#"<p>This is <em>important</em> text.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_emphasis(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!(">>>{text}<<<"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#">>>important<<<"#),
        "expected to contain: {}",
        r#">>>important<<<"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"*important*"#),
        "expected NOT to contain: {}",
        r#"*important*"#
    );
}

#[test]
fn test_visitor_custom_heading() {
    // Visitor replaces heading with custom format
    let html = r#"<h2>Section Title</h2><p>Content below heading.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&mut self, _ctx: &NodeContext, _level: u32, text: &str, _id: Option<&str>) -> VisitResult {
            VisitResult::Custom(format!("--- {text} ---"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"--- Section Title ---"#),
        "expected to contain: {}",
        r#"--- Section Title ---"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"## Section Title"#),
        "expected NOT to contain: {}",
        r#"## Section Title"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Content below heading."#),
        "expected to contain: {}",
        r#"Content below heading."#
    );
}

#[test]
fn test_visitor_custom_image() {
    // Visitor replaces image with custom output using template
    let html = r#"<img src="banner.png" alt="Banner">"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_image(&mut self, _ctx: &NodeContext, _src: &str, alt: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Custom(format!("[Image: {alt}]"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[Image: Banner]"#),
        "expected to contain: {}",
        r#"[Image: Banner]"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"banner.png"#),
        "expected NOT to contain: {}",
        r#"banner.png"#
    );
}

#[test]
fn test_visitor_custom_link_format() {
    // Visitor reformats links using template interpolation
    let html = r#"<p>Visit <a href="https://example.com">Example</a> for more info.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&mut self, _ctx: &NodeContext, href: &str, text: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Custom(format!("{text} ({href})"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Example (https://example.com)"#),
        "expected to contain: {}",
        r#"Example (https://example.com)"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"[Example]"#),
        "expected NOT to contain: {}",
        r#"[Example]"#
    );
}

#[test]
fn test_visitor_custom_link_static() {
    // Visitor replaces link with static custom output
    let html = r#"<a href="https://example.com">Click here</a>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&mut self, _ctx: &NodeContext, _href: &str, _text: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Custom("[REDACTED LINK]".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[REDACTED LINK]"#),
        "expected to contain: {}",
        r#"[REDACTED LINK]"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"example.com"#),
        "expected NOT to contain: {}",
        r#"example.com"#
    );
}

#[test]
fn test_visitor_custom_output() {
    // Visitor custom action replaces element output
    let html = r#"<h1>Original Heading</h1>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&mut self, _ctx: &NodeContext, _level: u32, _text: &str, _id: Option<&str>) -> VisitResult {
            VisitResult::Custom("## REPLACED HEADING".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"## REPLACED HEADING"#),
        "expected to contain: {}",
        r#"## REPLACED HEADING"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"# Original Heading"#),
        "expected NOT to contain: {}",
        r#"# Original Heading"#
    );
}

#[test]
fn test_visitor_definition_list_custom() {
    // Visitor customizes definition list items
    let html = r#"<dl><dt>HTML</dt><dd>HyperText Markup Language</dd><dt>CSS</dt><dd>Cascading Style Sheets</dd></dl>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_definition_term(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("**{text}**"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"**HTML**"#),
        "expected to contain: {}",
        r#"**HTML**"#
    );
    assert!(
        format!("{:?}", content).contains(r#"**CSS**"#),
        "expected to contain: {}",
        r#"**CSS**"#
    );
    assert!(
        format!("{:?}", content).contains(r#"HyperText Markup Language"#),
        "expected to contain: {}",
        r#"HyperText Markup Language"#
    );
}

#[test]
fn test_visitor_definition_list_custom_format() {
    // Visitor formats definition lists with custom templates
    let html = r#"<dl><dt>Python</dt><dd>A high-level programming language</dd><dt>JavaScript</dt><dd>A scripting language for web browsers</dd></dl>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_definition_description(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("> {text}"))
        }
        fn visit_definition_term(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("### {text}"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"### Python"#),
        "expected to contain: {}",
        r#"### Python"#
    );
    assert!(
        format!("{:?}", content).contains(r#"### JavaScript"#),
        "expected to contain: {}",
        r#"### JavaScript"#
    );
    assert!(
        format!("{:?}", content).contains(r#"> A high-level programming language"#),
        "expected to contain: {}",
        r#"> A high-level programming language"#
    );
    assert!(
        format!("{:?}", content).contains(r#"> A scripting language for web browsers"#),
        "expected to contain: {}",
        r#"> A scripting language for web browsers"#
    );
}

#[test]
fn test_visitor_definition_list_skip() {
    // Visitor skips definition list items from output
    let html = r#"<p>Glossary:</p><dl><dt>Term A</dt><dd>Definition of term A</dd><dt>Term B</dt><dd>Definition of term B</dd></dl><p>End of glossary</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_definition_term(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
        fn visit_definition_description(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Glossary:"#),
        "expected to contain: {}",
        r#"Glossary:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"End of glossary"#),
        "expected to contain: {}",
        r#"End of glossary"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Term A"#),
        "expected NOT to contain: {}",
        r#"Term A"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Definition"#),
        "expected NOT to contain: {}",
        r#"Definition"#
    );
}

#[test]
fn test_visitor_details_summary_custom() {
    // Visitor customizes details/summary disclosure elements
    let html = r#"<details><summary>Click to expand</summary><p>This content is initially hidden.</p><p>But can be revealed by the user.</p></details>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_summary(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("[EXPANDABLE] {text}"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[EXPANDABLE] Click to expand"#),
        "expected to contain: {}",
        r#"[EXPANDABLE] Click to expand"#
    );
    assert!(
        format!("{:?}", content).contains(r#"This content is initially hidden."#),
        "expected to contain: {}",
        r#"This content is initially hidden."#
    );
}

#[test]
fn test_visitor_details_summary_skip() {
    // Visitor removes details/summary elements entirely
    let html = r#"<p>Main content here.</p><details><summary>Hidden section</summary><p>Secret details</p></details><p>More main content.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_details(&mut self, _ctx: &NodeContext, _open: bool) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Main content here."#),
        "expected to contain: {}",
        r#"Main content here."#
    );
    assert!(
        format!("{:?}", content).contains(r#"More main content."#),
        "expected to contain: {}",
        r#"More main content."#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Hidden section"#),
        "expected NOT to contain: {}",
        r#"Hidden section"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Secret details"#),
        "expected NOT to contain: {}",
        r#"Secret details"#
    );
}

#[test]
fn test_visitor_figure_custom() {
    // Visitor customizes figure and figcaption elements
    let html = r#"<article><h1>Article Title</h1><p>Introduction paragraph.</p><figure><img src="diagram.png" alt="System architecture diagram"><figcaption>Figure 1: System Architecture</figcaption></figure><p>Explanation of the figure.</p></article>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_figcaption(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("*{text}*"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Article Title"#),
        "expected to contain: {}",
        r#"Article Title"#
    );
    assert!(
        format!("{:?}", content).contains(r#"*Figure 1: System Architecture*"#),
        "expected to contain: {}",
        r#"*Figure 1: System Architecture*"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Explanation of the figure."#),
        "expected to contain: {}",
        r#"Explanation of the figure."#
    );
}

#[test]
fn test_visitor_figure_custom_wrap() {
    // Visitor wraps figure content with custom formatting
    let html = r#"<section><h2>Gallery</h2><figure><img src="photo1.jpg" alt="Photo"><figcaption>Beautiful sunset</figcaption></figure></section>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_figure_start(&mut self, _ctx: &NodeContext) -> VisitResult {
            VisitResult::Custom("\n[FIGURE]\n".to_string())
        }
        fn visit_figure_end(&mut self, _ctx: &NodeContext, output: &str) -> VisitResult {
            VisitResult::Custom(format!("{output}\n[/FIGURE]\n"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[FIGURE]"#),
        "expected to contain: {}",
        r#"[FIGURE]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"[/FIGURE]"#),
        "expected to contain: {}",
        r#"[/FIGURE]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Gallery"#),
        "expected to contain: {}",
        r#"Gallery"#
    );
}

#[test]
fn test_visitor_figure_skip() {
    // Visitor removes figure elements with their captions
    let html = r#"<p>See the chart below:</p><figure><img src="chart.svg"><figcaption>Revenue Trends 2020-2024</figcaption></figure><p>As shown in the chart above.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_figure_start(&mut self, _ctx: &NodeContext) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"See the chart below:"#),
        "expected to contain: {}",
        r#"See the chart below:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"As shown in the chart above."#),
        "expected to contain: {}",
        r#"As shown in the chart above."#
    );
    assert!(
        !format!("{:?}", content).contains(r#"Revenue Trends"#),
        "expected NOT to contain: {}",
        r#"Revenue Trends"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"chart.svg"#),
        "expected NOT to contain: {}",
        r#"chart.svg"#
    );
}

#[test]
fn test_visitor_form_custom() {
    // Visitor replaces form with custom output
    let html = r#"<div><form action="/submit" method="POST"><label>Name: <input type="text" name="name"></label><button type="submit">Submit</button></form></div>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_form(&mut self, _ctx: &NodeContext, _action: Option<&str>, _method: Option<&str>) -> VisitResult {
            VisitResult::Custom("[FORM PLACEHOLDER]".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[FORM PLACEHOLDER]"#),
        "expected to contain: {}",
        r#"[FORM PLACEHOLDER]"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"submit"#),
        "expected NOT to contain: {}",
        r#"submit"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"input"#),
        "expected NOT to contain: {}",
        r#"input"#
    );
}

#[test]
fn test_visitor_form_skip() {
    // Visitor skips form elements entirely
    let html = r#"<p>Before form</p><form><input type="email" name="email"></form><p>After form</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_form(&mut self, _ctx: &NodeContext, _action: Option<&str>, _method: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Before form"#),
        "expected to contain: {}",
        r#"Before form"#
    );
    assert!(
        format!("{:?}", content).contains(r#"After form"#),
        "expected to contain: {}",
        r#"After form"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"email"#),
        "expected NOT to contain: {}",
        r#"email"#
    );
}

#[test]
fn test_visitor_heading_bare_string_preserves_case() {
    // Visitor returns rendered heading template as bare string; mixed-case is preserved (regression guard for issue #350)
    let html = r#"<h2>Important Section Title</h2><p>Body.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&mut self, _ctx: &NodeContext, _level: u32, text: &str, _id: Option<&str>) -> VisitResult {
            VisitResult::Custom(format!("## {text} ##"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"## Important Section Title ##"#),
        "expected to contain: {}",
        r#"## Important Section Title ##"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"important section title"#),
        "expected NOT to contain: {}",
        r#"important section title"#
    );
}

#[test]
fn test_visitor_horizontal_rule_custom() {
    // Visitor replaces horizontal rule with custom output
    let html = r#"<h1>Section A</h1><p>Content A</p><hr><h1>Section B</h1><p>Content B</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_horizontal_rule(&mut self, _ctx: &NodeContext) -> VisitResult {
            VisitResult::Custom("\n[DIVIDER]\n".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[DIVIDER]"#),
        "expected to contain: {}",
        r#"[DIVIDER]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Section A"#),
        "expected to contain: {}",
        r#"Section A"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Section B"#),
        "expected to contain: {}",
        r#"Section B"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"---"#),
        "expected NOT to contain: {}",
        r#"---"#
    );
}

#[test]
fn test_visitor_horizontal_rule_skip() {
    // Visitor removes all horizontal rules
    let html = r#"<p>Part 1</p><hr><p>Part 2</p><hr><p>Part 3</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_horizontal_rule(&mut self, _ctx: &NodeContext) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Part 1"#),
        "expected to contain: {}",
        r#"Part 1"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Part 2"#),
        "expected to contain: {}",
        r#"Part 2"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Part 3"#),
        "expected to contain: {}",
        r#"Part 3"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"---"#),
        "expected NOT to contain: {}",
        r#"---"#
    );
}

#[test]
fn test_visitor_iframe_custom() {
    // Visitor replaces embedded iframe with custom text
    let html = r#"<p>Embedded map:</p><iframe src="https://maps.example.com/embed" width="400" height="300"></iframe><p>End of map</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_iframe(&mut self, _ctx: &NodeContext, _src: Option<&str>) -> VisitResult {
            VisitResult::Custom("[EMBEDDED: https://maps.example.com/embed]".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[EMBEDDED: https://maps.example.com/embed]"#),
        "expected to contain: {}",
        r#"[EMBEDDED: https://maps.example.com/embed]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Embedded map:"#),
        "expected to contain: {}",
        r#"Embedded map:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"End of map"#),
        "expected to contain: {}",
        r#"End of map"#
    );
}

#[test]
fn test_visitor_iframe_skip() {
    // Visitor removes embedded iframes
    let html = r#"<h3>Reviews</h3><iframe src="https://widget.example.com/reviews"></iframe><p>See reviews from our partners.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_iframe(&mut self, _ctx: &NodeContext, _src: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Reviews"#),
        "expected to contain: {}",
        r#"Reviews"#
    );
    assert!(
        format!("{:?}", content).contains(r#"See reviews from our partners."#),
        "expected to contain: {}",
        r#"See reviews from our partners."#
    );
    assert!(
        !format!("{:?}", content).contains(r#"widget.example.com"#),
        "expected NOT to contain: {}",
        r#"widget.example.com"#
    );
}

#[test]
fn test_visitor_image_bare_string_preserves_case() {
    // Visitor returns bare-string image replacement; mixed-case alt/src preserved (regression guard for issue #350)
    let html = r#"<img src="PhotoOne.JPG" alt="Sunset Over Bay">"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_image(&mut self, _ctx: &NodeContext, src: &str, alt: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Custom(format!("[image: {alt} -> {src}]"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[image: Sunset Over Bay -> PhotoOne.JPG]"#),
        "expected to contain: {}",
        r#"[image: Sunset Over Bay -> PhotoOne.JPG]"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"sunset over bay"#),
        "expected NOT to contain: {}",
        r#"sunset over bay"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"photoone.jpg"#),
        "expected NOT to contain: {}",
        r#"photoone.jpg"#
    );
}

#[test]
fn test_visitor_input_custom() {
    // Visitor replaces input with labeled output
    let html = r#"<form><label>Username: <input type="text" name="username" value=""></label><label>Password: <input type="password" name="password"></label></form>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_input(
            &mut self,
            _ctx: &NodeContext,
            input_type: &str,
            _name: Option<&str>,
            _value: Option<&str>,
        ) -> VisitResult {
            VisitResult::Custom(format!("[INPUT:{input_type}]"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[INPUT:text]"#),
        "expected to contain: {}",
        r#"[INPUT:text]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"[INPUT:password]"#),
        "expected to contain: {}",
        r#"[INPUT:password]"#
    );
}

#[test]
fn test_visitor_input_skip() {
    // Visitor skips all input elements
    let html = r#"<p>Sign up:</p><input type="text" name="email" placeholder="your@email.com"><input type="checkbox" name="agree"><p>Continue</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_input(
            &mut self,
            _ctx: &NodeContext,
            _input_type: &str,
            _name: Option<&str>,
            _value: Option<&str>,
        ) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Sign up:"#),
        "expected to contain: {}",
        r#"Sign up:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Continue"#),
        "expected to contain: {}",
        r#"Continue"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"email"#),
        "expected NOT to contain: {}",
        r#"email"#
    );
}

#[test]
fn test_visitor_line_break_custom() {
    // Visitor replaces line break with custom output
    let html = r#"<p>First line<br>Second line<br>Third line</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_line_break(&mut self, _ctx: &NodeContext) -> VisitResult {
            VisitResult::Custom(" | ".to_string())
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"First line | Second line | Third line"#),
        "expected to contain: {}",
        r#"First line | Second line | Third line"#
    );
    assert!(
        !format!("{:?}", content).contains(
            r#"

"#
        ),
        "expected NOT to contain: {}",
        r#"

"#
    );
}

#[test]
fn test_visitor_line_break_skip() {
    // Visitor removes all line breaks
    let html = r#"<p>Address Line 1<br>Address Line 2<br>Address Line 3</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_line_break(&mut self, _ctx: &NodeContext) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Address Line 1Address Line 2Address Line 3"#),
        "expected to contain: {}",
        r#"Address Line 1Address Line 2Address Line 3"#
    );
}

#[test]
fn test_visitor_link_bare_string_preserves_case() {
    // Visitor returns rendered template as a bare string (not a dict) and original mixed-case content is preserved end-to-end (regression guard for issue #350)
    let html = r#"<a href="https://old-cdn.com/file.pdf">Download</a>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&mut self, _ctx: &NodeContext, _href: &str, text: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Custom(format!("[{text}](https://new-cdn.com/file.pdf)"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[Download](https://new-cdn.com/file.pdf)"#),
        "expected to contain: {}",
        r#"[Download](https://new-cdn.com/file.pdf)"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"[download]"#),
        "expected NOT to contain: {}",
        r#"[download]"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"old-cdn.com"#),
        "expected NOT to contain: {}",
        r#"old-cdn.com"#
    );
}

#[test]
fn test_visitor_mark_custom() {
    // Visitor replaces highlight/mark with custom template
    let html = r#"<p>This is a <mark>highlighted passage</mark> in the text.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_mark(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("=={text}=="))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"==highlighted passage=="#),
        "expected to contain: {}",
        r#"==highlighted passage=="#
    );
    assert!(
        format!("{:?}", content).contains(r#"This is a"#),
        "expected to contain: {}",
        r#"This is a"#
    );
}

#[test]
fn test_visitor_mark_skip() {
    // Visitor skips mark elements entirely
    let html = r#"<p>Key insight: <mark>always validate input</mark> for security.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_mark(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        !format!("{:?}", content).contains(r#"always validate input"#),
        "expected NOT to contain: {}",
        r#"always validate input"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Key insight:"#),
        "expected to contain: {}",
        r#"Key insight:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"for security."#),
        "expected to contain: {}",
        r#"for security."#
    );
}

#[test]
fn test_visitor_preserve_html() {
    // Visitor preserve_html action includes raw HTML in output
    let html = r#"<div><custom-tag>Custom content</custom-tag></div>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_custom_element(&mut self, _ctx: &NodeContext, _tag_name: &str, _html: &str) -> VisitResult {
            VisitResult::PreserveHtml
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"<custom-tag>"#),
        "expected to contain: {}",
        r#"<custom-tag>"#
    );
}

#[test]
fn test_visitor_skip_code_blocks() {
    // Visitor skips code blocks from output
    let html = r#"<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_code_block(&mut self, _ctx: &NodeContext, _lang: Option<&str>, _code: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Intro text"#),
        "expected to contain: {}",
        r#"Intro text"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Outro text"#),
        "expected to contain: {}",
        r#"Outro text"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"let x = 42"#),
        "expected NOT to contain: {}",
        r#"let x = 42"#
    );
}

#[test]
fn test_visitor_skip_heading() {
    // Visitor skip action omits all headings from output
    let html = r#"<h1>Title</h1><p>Body text remains.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_heading(&mut self, _ctx: &NodeContext, _level: u32, _text: &str, _id: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        !format!("{:?}", content).contains(r#"Title"#),
        "expected NOT to contain: {}",
        r#"Title"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Body text remains."#),
        "expected to contain: {}",
        r#"Body text remains."#
    );
}

#[test]
fn test_visitor_skip_images() {
    // Visitor skips all images from output
    let html = r#"<p>Before image</p><img src="photo.jpg" alt="A photo"><p>After image</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_image(&mut self, _ctx: &NodeContext, _src: &str, _alt: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Before image"#),
        "expected to contain: {}",
        r#"Before image"#
    );
    assert!(
        format!("{:?}", content).contains(r#"After image"#),
        "expected to contain: {}",
        r#"After image"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"photo.jpg"#),
        "expected NOT to contain: {}",
        r#"photo.jpg"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"A photo"#),
        "expected NOT to contain: {}",
        r#"A photo"#
    );
}

#[test]
fn test_visitor_skip_links() {
    // Visitor skips all links entirely
    let html = r#"<p>Before <a href="https://example.com">link text</a> after</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_link(&mut self, _ctx: &NodeContext, _href: &str, _text: &str, _title: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        !format!("{:?}", content).contains(r#"link text"#),
        "expected NOT to contain: {}",
        r#"link text"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"example.com"#),
        "expected NOT to contain: {}",
        r#"example.com"#
    );
}

#[test]
fn test_visitor_skip_strong() {
    // Visitor skips bold/strong elements
    let html = r#"<p>Normal <strong>bold text</strong> normal</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_strong(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        !format!("{:?}", content).contains(r#"bold text"#),
        "expected NOT to contain: {}",
        r#"bold text"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Normal"#),
        "expected to contain: {}",
        r#"Normal"#
    );
}

#[test]
fn test_visitor_subscript_custom() {
    // Visitor replaces subscript with custom template
    let html = r#"<p>H<sub>2</sub>O is water.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_subscript(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("~{text}~"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"H~2~O"#),
        "expected to contain: {}",
        r#"H~2~O"#
    );
    assert!(
        format!("{:?}", content).contains(r#"is water"#),
        "expected to contain: {}",
        r#"is water"#
    );
}

#[test]
fn test_visitor_subscript_skip() {
    // Visitor skips subscript elements entirely
    let html = r#"<p>The formula C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> is sugar.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_subscript(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"The formula CHO is sugar."#),
        "expected to contain: {}",
        r#"The formula CHO is sugar."#
    );
}

#[test]
fn test_visitor_superscript_custom() {
    // Visitor replaces superscript with custom template
    let html = r#"<p>Einstein's E=mc<sup>2</sup> revolutionized physics.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_superscript(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("^{text}^"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"E=mc^2^"#),
        "expected to contain: {}",
        r#"E=mc^2^"#
    );
    assert!(
        format!("{:?}", content).contains(r#"revolutionized physics"#),
        "expected to contain: {}",
        r#"revolutionized physics"#
    );
}

#[test]
fn test_visitor_superscript_skip() {
    // Visitor skips superscript from output
    let html = r#"<p>The equation x<sup>3</sup> + y<sup>3</sup> = z<sup>3</sup> has no solutions.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_superscript(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"The equation x + y = z has no solutions."#),
        "expected to contain: {}",
        r#"The equation x + y = z has no solutions."#
    );
}

#[test]
fn test_visitor_underline_custom() {
    // Visitor replaces underline with custom markup
    let html = r#"<p>This is <u>very important</u> text.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_underline(&mut self, _ctx: &NodeContext, text: &str) -> VisitResult {
            VisitResult::Custom(format!("_{text}_"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"_very important_"#),
        "expected to contain: {}",
        r#"_very important_"#
    );
    assert!(
        !format!("{:?}", content).contains(r#"**"#),
        "expected NOT to contain: {}",
        r#"**"#
    );
}

#[test]
fn test_visitor_underline_skip() {
    // Visitor skips underline elements from output
    let html = r#"<p>Normal text with <u>underlined part</u> and more text.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_underline(&mut self, _ctx: &NodeContext, _text: &str) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Normal text with"#),
        "expected to contain: {}",
        r#"Normal text with"#
    );
    assert!(
        format!("{:?}", content).contains(r#"and more text."#),
        "expected to contain: {}",
        r#"and more text."#
    );
    assert!(
        !format!("{:?}", content).contains(r#"underlined part"#),
        "expected NOT to contain: {}",
        r#"underlined part"#
    );
}

#[test]
fn test_visitor_video_custom() {
    // Visitor replaces video with custom link
    let html = r#"<p>Watch our tutorial:</p><video src="tutorial.mp4" width="320" height="240" controls></video><p>Great content!</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_video(&mut self, _ctx: &NodeContext, src: Option<&str>) -> VisitResult {
            let src = src.unwrap_or_default();
            VisitResult::Custom(format!("[VIDEO: {src}]"))
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"[VIDEO: tutorial.mp4]"#),
        "expected to contain: {}",
        r#"[VIDEO: tutorial.mp4]"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Watch our tutorial:"#),
        "expected to contain: {}",
        r#"Watch our tutorial:"#
    );
    assert!(
        format!("{:?}", content).contains(r#"Great content!"#),
        "expected to contain: {}",
        r#"Great content!"#
    );
}

#[test]
fn test_visitor_video_skip() {
    // Visitor removes video elements entirely
    let html = r#"<h2>Demo</h2><video src="demo.webm"></video><p>See the demo above.</p>"#;
    let mut options: ConversionOptions = Default::default();
    #[derive(Debug)]
    struct _TestVisitor;
    impl HtmlVisitor for _TestVisitor {
        fn visit_video(&mut self, _ctx: &NodeContext, _src: Option<&str>) -> VisitResult {
            VisitResult::Skip
        }
    }
    let visitor = std::sync::Arc::new(std::sync::Mutex::new(_TestVisitor));
    options.visitor = Some(visitor);
    let result = convert(html, Some(options)).expect("should succeed");
    let content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(
        format!("{:?}", content).contains(r#"Demo"#),
        "expected to contain: {}",
        r#"Demo"#
    );
    assert!(
        format!("{:?}", content).contains(r#"See the demo above."#),
        "expected to contain: {}",
        r#"See the demo above."#
    );
    assert!(
        !format!("{:?}", content).contains(r#"demo.webm"#),
        "expected NOT to contain: {}",
        r#"demo.webm"#
    );
}
