<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:75c92f06505292e46df8ff48646d1ebf778bc6ed356d0f06a4b3e0ccd4f1603d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use HtmlToMarkdown\HtmlToMarkdown;

/** E2e tests for category: options. */
final class OptionsTest extends TestCase
{
    /** Bare URL links rendered as regular markdown links when autolinks disabled */
    public function test_options_autolinks_false(): void
    {
        $result = HtmlToMarkdown::convert("<p><a href='https://example.com'>https://example.com</a></p>", ["autolinks" => false]);
        $this->assertStringContainsString("example.com", $result->content);
    }

    /** BR elements in table cells are stripped when disabled */
    public function test_options_br_in_tables_false(): void
    {
        $result = HtmlToMarkdown::convert("<table><tr><th>Col</th></tr><tr><td>A<br>B</td></tr></table>", ["br_in_tables" => false]);
        $this->assertStringContainsString("Col", $result->content);
    }

    /** BR elements in table cells render as line breaks */
    public function test_options_br_in_tables_true(): void
    {
        $result = HtmlToMarkdown::convert("<table><tr><th>Header</th></tr><tr><td>Line 1<br>Line 2</td></tr></table>", ["br_in_tables" => true]);
        $this->assertStringContainsString("Header", $result->content);
        $this->assertStringContainsString("Line 1", $result->content);
        $this->assertStringContainsString("Line 2", $result->content);
    }

    /** Backticks code block style uses triple backtick fences */
    public function test_options_code_block_backticks(): void
    {
        $result = HtmlToMarkdown::convert("<pre><code class=\"language-js\">console.log('hi');</code></pre>", ["code_block_style" => "backticks"]);
        $this->assertStringContainsString("```", $result->content);
        $this->assertStringContainsString("console.log('hi');", $result->content);
    }

    /** Code blocks use 4-space indentation */
    public function test_options_code_block_indented(): void
    {
        $result = HtmlToMarkdown::convert("<pre><code>print('hello')</code></pre>", ["code_block_style" => "indented"]);
        $this->assertStringContainsString("print('hello')", $result->content);
        $this->assertStringNotContainsString("```", $result->content);
    }

    /** Code blocks use tilde fences */
    public function test_options_code_block_tildes(): void
    {
        $result = HtmlToMarkdown::convert("<pre><code>let x = 1;</code></pre>", ["code_block_style" => "tildes"]);
        $this->assertStringContainsString("~~~", $result->content);
        $this->assertStringContainsString("let x = 1;", $result->content);
    }

    /** Tildes code block style uses triple tilde fences */
    public function test_options_code_block_tildes_style(): void
    {
        $result = HtmlToMarkdown::convert("<pre><code>some code</code></pre>", ["code_block_style" => "tildes"]);
        $this->assertStringContainsString("~~~", $result->content);
        $this->assertStringContainsString("some code", $result->content);
    }

    /** Default code language annotation on blocks without lang attribute */
    public function test_options_code_language_python(): void
    {
        $result = HtmlToMarkdown::convert("<pre><code>def hello(): pass</code></pre>", ["code_language" => "python"]);
        $this->assertStringContainsString("```python", $result->content);
        $this->assertStringContainsString("def hello", $result->content);
    }

    /** Block elements treated as inline */
    public function test_options_convert_as_inline(): void
    {
        $result = HtmlToMarkdown::convert("<p>One</p><p>Two</p>", ["convert_as_inline" => true]);
        $this->assertStringContainsString("One", $result->content);
        $this->assertStringContainsString("Two", $result->content);
    }

    /** Debug mode enabled does not crash and produces output */
    public function test_options_debug_true(): void
    {
        $result = HtmlToMarkdown::convert("<p>Debug test</p>", ["debug" => true]);
        $this->assertStringContainsString("Debug test", $result->content);
    }

    /** Links without title get empty title attribute when defaultTitle is true */
    public function test_options_default_title_true(): void
    {
        $result = HtmlToMarkdown::convert("<p><a href='https://example.com'>Link</a></p>", ["default_title" => true]);
        $this->assertStringContainsString("Link", $result->content);
        $this->assertStringContainsString("https://example.com", $result->content);
    }

    /** UTF-8 encoding hint for special characters */
    public function test_options_encoding_utf8(): void
    {
        $result = HtmlToMarkdown::convert("<p>Café naïve résumé</p>", ["encoding" => "utf-8"]);
        $this->assertNotEmpty($result->content);
    }

    /** ASCII Markdown characters are escaped when escapeAscii is true */
    public function test_options_escape_ascii_enabled(): void
    {
        $result = HtmlToMarkdown::convert("<p>Text with # hash and [brackets] and * star</p>", ["escape_ascii" => true]);
        $this->assertStringContainsString("Text", $result->content);
        $this->assertStringContainsString("hash", $result->content);
        $this->assertStringContainsString("brackets", $result->content);
        $this->assertStringContainsString("star", $result->content);
    }

    /** escape_asterisks option escapes asterisks in plain text */
    public function test_options_escape_asterisks(): void
    {
        $result = HtmlToMarkdown::convert("<p>Use 2*3 = 6 in math.</p>", ["escape_asterisks" => true]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("2", $result->content);
        $this->assertStringContainsString("3", $result->content);
        $this->assertStringContainsString("6", $result->content);
    }

    /** escape_misc option escapes miscellaneous markdown characters */
    public function test_options_escape_misc(): void
    {
        $result = HtmlToMarkdown::convert("<p>Use # and | and ~ in text.</p>", ["escape_misc" => true]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("Use", $result->content);
        $this->assertStringContainsString("and", $result->content);
        $this->assertStringContainsString("in text.", $result->content);
    }

    /** escape_underscores option escapes underscores in plain text */
    public function test_options_escape_underscores(): void
    {
        $result = HtmlToMarkdown::convert("<p>The variable_name is defined.</p>", ["escape_underscores" => true]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("variable", $result->content);
        $this->assertStringContainsString("name", $result->content);
        $this->assertStringContainsString("defined.", $result->content);
    }

    /** Elements matching CSS attribute selector are excluded entirely */
    public function test_options_exclude_selectors_attribute(): void
    {
        $result = HtmlToMarkdown::convert("<body><div role=\"complementary\">Sidebar</div><p>Primary text</p></body>", ["exclude_selectors" => ["[role='complementary']"]]);
        $this->assertStringContainsString("Primary text", $result->content);
        $this->assertStringNotContainsString("Sidebar", $result->content);
    }

    /** Elements matching CSS class selector are excluded entirely */
    public function test_options_exclude_selectors_class(): void
    {
        $result = HtmlToMarkdown::convert("<body><div class=\"cookie-banner\">Accept cookies</div><p>Main content</p></body>", ["exclude_selectors" => [".cookie-banner"]]);
        $this->assertStringContainsString("Main content", $result->content);
        $this->assertStringNotContainsString("cookies", $result->content);
    }

    /** Empty exclude_selectors list does not affect output */
    public function test_options_exclude_selectors_empty_noop(): void
    {
        $result = HtmlToMarkdown::convert("<p>Hello world</p>", ["exclude_selectors" => []]);
        $this->assertStringContainsString("Hello world", $result->content);
    }

    /** Elements matching CSS id selector are excluded entirely */
    public function test_options_exclude_selectors_id(): void
    {
        $result = HtmlToMarkdown::convert("<body><div id=\"ad-container\">Buy stuff</div><p>Article text</p></body>", ["exclude_selectors" => ["#ad-container"]]);
        $this->assertStringContainsString("Article text", $result->content);
        $this->assertStringNotContainsString("Buy stuff", $result->content);
    }

    /** Multiple CSS selectors each exclude their matched elements */
    public function test_options_exclude_selectors_multiple(): void
    {
        $result = HtmlToMarkdown::convert("<body><nav class=\"nav\">Menu</nav><p>Content</p><footer>Footer</footer></body>", ["exclude_selectors" => [".nav", "footer"]]);
        $this->assertStringContainsString("Content", $result->content);
        $this->assertStringNotContainsString("Menu", $result->content);
        $this->assertStringNotContainsString("Footer", $result->content);
    }

    /** All descendants of excluded elements are dropped */
    public function test_options_exclude_selectors_nested_content_dropped(): void
    {
        $result = HtmlToMarkdown::convert("<body><aside class=\"sidebar\"><h2>Related</h2><p>Sidebar text</p></aside><main><p>Main text</p></main></body>", ["exclude_selectors" => [".sidebar"]]);
        $this->assertStringContainsString("Main text", $result->content);
        $this->assertStringNotContainsString("Related", $result->content);
        $this->assertStringNotContainsString("Sidebar text", $result->content);
    }

    /** Exclude selectors work in plain text output mode */
    public function test_options_exclude_selectors_plain_text_mode(): void
    {
        $result = HtmlToMarkdown::convert("<body><div class=\"nav\">Navigation</div><p>Article body</p></body>", ["exclude_selectors" => [".nav"], "output_format" => "plain"]);
        $this->assertStringContainsString("Article body", $result->content);
        $this->assertStringNotContainsString("Navigation", $result->content);
    }

    /** exclude_selectors drops entire subtree unlike strip_tags which keeps children */
    public function test_options_exclude_selectors_vs_strip_tags(): void
    {
        $result = HtmlToMarkdown::convert("<body><div class=\"wrapper\"><p>Inner paragraph</p></div><p>Outer text</p></body>", ["exclude_selectors" => [".wrapper"]]);
        $this->assertStringContainsString("Outer text", $result->content);
        $this->assertStringNotContainsString("Inner paragraph", $result->content);
    }

    /** Extract metadata returns document metadata when enabled */
    public function test_options_extract_metadata_true(): void
    {
        $result = HtmlToMarkdown::convert("<html><head><title>Test Page</title><meta name='description' content='A test page'></head><body><p>Content</p></body></html>", ["extract_metadata" => true]);
        $this->assertNotEmpty($result->content);
        // skipped: result_is_simple, field 'metadata.title' not on simple result type
        // skipped: result_is_simple, field 'metadata.description' not on simple result type
    }

    /** ATX heading style produces hash-prefixed headings */
    public function test_options_heading_style_atx(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Title</h1><h2>Subtitle</h2>", ["heading_style" => "atx"]);
        $this->assertStringContainsString("# Title", $result->content);
        $this->assertStringContainsString("## Subtitle", $result->content);
    }

    /** ATX closed heading style adds closing hashes */
    public function test_options_heading_style_atx_closed(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Closed Heading</h1>", ["heading_style" => "atx_closed"]);
        $this->assertStringContainsString("# Closed Heading #", $result->content);
    }

    /** Underlined heading style produces setext-style headings for h1 and h2 */
    public function test_options_heading_style_underlined(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Main Title</h1>", ["heading_style" => "underlined"]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("Main Title", $result->content);
    }

    /** Mark tag rendered as bold */
    public function test_options_highlight_bold(): void
    {
        $result = HtmlToMarkdown::convert("<p>Text with <mark>highlighted</mark> text.</p>", ["highlight_style" => "bold"]);
        $this->assertStringContainsString("**highlighted**", $result->content);
    }

    /** Mark tag with double equal highlight style */
    public function test_options_highlight_double_equal(): void
    {
        $result = HtmlToMarkdown::convert("<p>Text with <mark>highlighted</mark> here.</p>", ["highlight_style" => "double_equal"]);
        $this->assertStringContainsString("==highlighted==", $result->content);
    }

    /** Mark tag with no highlight style strips the mark */
    public function test_options_highlight_none(): void
    {
        $result = HtmlToMarkdown::convert("<p>Text with <mark>plain</mark> content.</p>", ["highlight_style" => "none"]);
        $this->assertStringContainsString("plain", $result->content);
        $this->assertStringNotContainsString("==", $result->content);
    }

    /** Images inside specified tags stay inline */
    public function test_options_keep_inline_images_in_paragraph(): void
    {
        $result = HtmlToMarkdown::convert("<p>Text <img src='icon.png' alt='icon'> more text</p>", ["keep_inline_images_in" => ["p"]]);
        $this->assertStringContainsString("Text", $result->content);
        $this->assertStringContainsString("more text", $result->content);
    }

    /** Links use reference-style formatting */
    public function test_options_link_style_reference(): void
    {
        $result = HtmlToMarkdown::convert("<p><a href='https://example.com'>Example</a> and <a href='https://other.com'>Other</a></p>", ["link_style" => "reference"]);
        $this->assertStringContainsString("Example", $result->content);
        $this->assertStringContainsString("Other", $result->content);
        $this->assertStringContainsString("example.com", $result->content);
    }

    /** Custom bullet character for unordered lists */
    public function test_options_list_custom_bullets(): void
    {
        $result = HtmlToMarkdown::convert("<ul><li>Item A</li><li>Item B</li></ul>", ["bullets" => "*"]);
        $this->assertStringContainsString("* Item A", $result->content);
        $this->assertStringContainsString("* Item B", $result->content);
    }

    /** Tab indentation type for nested list items */
    public function test_options_list_indent_tabs(): void
    {
        $result = HtmlToMarkdown::convert("<ul><li>Parent<ul><li>Child</li></ul></li></ul>", ["list_indent_type" => "tabs"]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("Parent", $result->content);
        $this->assertStringContainsString("Child", $result->content);
    }

    /** Nested lists indented with 4 spaces per level */
    public function test_options_list_indent_width_four(): void
    {
        $result = HtmlToMarkdown::convert("<ul><li>Outer<ul><li>Inner</li></ul></li></ul>", ["list_indent_width" => 4]);
        $this->assertStringContainsString("Outer", $result->content);
        $this->assertStringContainsString("Inner", $result->content);
    }

    /** Default max_depth (null) converts deeply nested content fully */
    public function test_options_max_depth_default_unlimited(): void
    {
        $result = HtmlToMarkdown::convert("<div><div><div><div><p>Deep content</p></div></div></div></div>");
        $this->assertStringContainsString("Deep content", $result->content);
    }

    /** max_depth truncates content beyond the specified depth */
    public function test_options_max_depth_truncates(): void
    {
        $result = HtmlToMarkdown::convert("<div><p>Shallow</p><div><div><div><p>Too deep</p></div></div></div></div>", ["max_depth" => 3]);
        $this->assertStringContainsString("Shallow", $result->content);
        $this->assertStringNotContainsString("Too deep", $result->content);
    }

    /** max_depth of 0 produces empty output */
    public function test_options_max_depth_zero_empty(): void
    {
        $result = HtmlToMarkdown::convert("<p>Hello</p>", ["max_depth" => 0]);
        $this->assertEquals("", trim($result->content));
    }

    /** Hard line breaks rendered with backslash */
    public function test_options_newline_backslash(): void
    {
        $result = HtmlToMarkdown::convert("<p>Line one<br>Line two</p>", ["newline_style" => "backslash"]);
        $this->assertStringContainsString("Line one", $result->content);
        $this->assertStringContainsString("Line two", $result->content);
    }

    /** Hard line breaks rendered with trailing spaces */
    public function test_options_newline_spaces(): void
    {
        $result = HtmlToMarkdown::convert("<p>First<br>Second</p>", ["newline_style" => "spaces"]);
        $this->assertStringContainsString("First", $result->content);
        $this->assertStringContainsString("Second", $result->content);
    }

    /** Djot output format produces djot-compatible markup */
    public function test_options_output_format_djot(): void
    {
        $result = HtmlToMarkdown::convert("<p>Simple paragraph.</p>", ["output_format" => "djot"]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("Simple paragraph.", $result->content);
    }

    /** Default markdown output format produces standard markdown */
    public function test_options_output_format_markdown(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Title</h1><p>Some text.</p>", ["heading_style" => "atx", "output_format" => "markdown"]);
        $this->assertStringContainsString("# Title", $result->content);
        $this->assertStringContainsString("Some text.", $result->content);
    }

    /** Plain text output format strips markdown syntax */
    public function test_options_output_format_plain(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Title</h1><p>Some <strong>bold</strong> text.</p>", ["output_format" => "plain"]);
        $this->assertStringContainsString("Title", $result->content);
        $this->assertStringContainsString("bold", $result->content);
        $this->assertStringContainsString("text.", $result->content);
    }

    /** Aggressive preset removes nav, footer, aside unconditionally */
    public function test_options_preprocessing_aggressive(): void
    {
        $result = HtmlToMarkdown::convert("<nav>Menu</nav><article><h1>Title</h1><p>Content</p></article><aside>Sidebar</aside><footer>Footer</footer>", ["preprocessing" => ["preset" => "Aggressive"]]);
        $this->assertStringContainsString("Title", $result->content);
        $this->assertStringContainsString("Content", $result->content);
        $this->assertStringNotContainsString("Menu", $result->content);
    }

    /** Minimal preset preserves nav, footer, aside */
    public function test_options_preprocessing_minimal(): void
    {
        $result = HtmlToMarkdown::convert("<nav>Navigation</nav><p>Content</p><footer>Footer</footer>", ["preprocessing" => ["preset" => "Minimal"]]);
        $this->assertStringContainsString("Navigation", $result->content);
        $this->assertStringContainsString("Content", $result->content);
        $this->assertStringContainsString("Footer", $result->content);
    }

    /** Forms are removed when remove_forms is true */
    public function test_options_preprocessing_remove_forms(): void
    {
        $result = HtmlToMarkdown::convert("<p>Before</p><form><input type='text'/><button>Submit</button></form><p>After</p>", ["preprocessing" => ["removeForms" => true]]);
        $this->assertStringContainsString("Before", $result->content);
        $this->assertStringContainsString("After", $result->content);
        $this->assertStringNotContainsString("Submit", $result->content);
    }

    /** Iframe tags preserved as raw HTML in output */
    public function test_options_preserve_tags_iframe(): void
    {
        $result = HtmlToMarkdown::convert("<p>Before</p><iframe src='video.html' width='560'></iframe><p>After</p>", ["preserve_tags" => ["iframe"]]);
        $this->assertStringContainsString("Before", $result->content);
        $this->assertStringContainsString("After", $result->content);
        $this->assertStringContainsString("<iframe", $result->content);
    }

    /** Images are omitted from output when skipImages is true */
    public function test_options_skip_images_true(): void
    {
        $result = HtmlToMarkdown::convert("<p>Before <img src='test.jpg' alt='photo'> After</p>", ["skip_images" => true]);
        $this->assertStringContainsString("Before", $result->content);
        $this->assertStringContainsString("After", $result->content);
        $this->assertStringNotContainsString("photo", $result->content);
    }

    /** Strip newlines produces single-line paragraphs */
    public function test_options_strip_newlines(): void
    {
        $result = HtmlToMarkdown::convert("<p>First paragraph.</p><p>Second paragraph.</p>", ["strip_newlines" => true]);
        $this->assertStringContainsString("First paragraph.", $result->content);
        $this->assertStringContainsString("Second paragraph.", $result->content);
    }

    /** Div and span tags stripped but content preserved */
    public function test_options_strip_tags_div_span(): void
    {
        $result = HtmlToMarkdown::convert("<div class='wrapper'><p>Inside div</p></div><p>Outside <span class='hl'>span text</span></p>", ["strip_tags" => ["div", "span"]]);
        $this->assertStringContainsString("Inside div", $result->content);
        $this->assertStringContainsString("span text", $result->content);
    }

    /** Strong and em tags use underscore symbol instead of asterisk */
    public function test_options_strong_em_underscore(): void
    {
        $result = HtmlToMarkdown::convert("<p><strong>bold</strong> and <em>italic</em></p>", ["strong_em_symbol" => "_"]);
        $this->assertStringContainsString("__bold__", $result->content);
        $this->assertStringContainsString("_italic_", $result->content);
    }

    /** Subscript rendered with tilde symbol */
    public function test_options_sub_symbol_tilde(): void
    {
        $result = HtmlToMarkdown::convert("<p>H<sub>2</sub>O</p>", ["sub_symbol" => "~"]);
        $this->assertStringContainsString("~2~", $result->content);
    }

    /** Superscript rendered with caret symbol */
    public function test_options_sup_symbol_caret(): void
    {
        $result = HtmlToMarkdown::convert("<p>x<sup>2</sup></p>", ["sup_symbol" => "^"]);
        $this->assertStringContainsString("^2^", $result->content);
    }

    /** Normalized whitespace mode collapses multiple spaces */
    public function test_options_whitespace_normalized(): void
    {
        $result = HtmlToMarkdown::convert("<p>Text   with    extra   spaces.</p>", ["whitespace_mode" => "normalized"]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("Text", $result->content);
        $this->assertStringContainsString("with", $result->content);
        $this->assertStringContainsString("extra", $result->content);
        $this->assertStringContainsString("spaces.", $result->content);
    }

    /** Strict whitespace mode preserves whitespace as-is */
    public function test_options_whitespace_strict(): void
    {
        $result = HtmlToMarkdown::convert("<p>Preserved   spacing.</p>", ["whitespace_mode" => "strict"]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("Preserved", $result->content);
        $this->assertStringContainsString("spacing.", $result->content);
    }

    /** Wrap option disabled preserves long lines without breaking */
    public function test_options_wrap_disabled(): void
    {
        $result = HtmlToMarkdown::convert("<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>", ["wrap" => false]);
        $this->assertStringContainsString("This is a long paragraph that should not be wrapped at all because wrapping is disabled.", $result->content);
    }

    /** Wrap option enabled with custom width wraps long lines */
    public function test_options_wrap_enabled(): void
    {
        $result = HtmlToMarkdown::convert("<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>", ["wrap" => true, "wrap_width" => 40]);
        $this->assertNotEmpty($result->content);
        $this->assertStringContainsString("This is a long paragraph", $result->content);
    }
}
