<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7090ad49c09ad607e370e6132b45cf1554588f43a06a9e2b6693719464e04a88
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace HtmlToMarkdown\E2e;

use PHPUnit\Framework\TestCase;
use HtmlToMarkdown\HtmlToMarkdown;use HtmlToMarkdown\ConversionOptions;
/** E2e tests for category: options. */
final class OptionsTest extends TestCase
{

    /** Bare URL links rendered as regular markdown links when autolinks disabled */
    public function test_options_autolinks_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["autolinks" => false]));
        $result = HtmlToMarkdown::convert("<p><a href='https://example.com'>https://example.com</a></p>", $options);

            $this->assertStringContainsString("example.com", $result->content);

    }


    /** BR elements in table cells are stripped when disabled */
    public function test_options_br_in_tables_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["brInTables" => false]));
        $result = HtmlToMarkdown::convert("<table><tr><th>Col</th></tr><tr><td>A<br>B</td></tr></table>", $options);

            $this->assertStringContainsString("Col", $result->content);

    }


    /** BR elements in table cells render as line breaks */
    public function test_options_br_in_tables_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["brInTables" => true]));
        $result = HtmlToMarkdown::convert("<table><tr><th>Header</th></tr><tr><td>Line 1<br>Line 2</td></tr></table>", $options);

            $this->assertStringContainsString("Header", $result->content);
    $this->assertStringContainsString("Line 1", $result->content);
    $this->assertStringContainsString("Line 2", $result->content);

    }


    /** Disabling capture_svg still produces content; SVG is not extracted as an image */
    public function test_options_capture_svg_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["captureSvg" => false, "extractImages" => true]));
        $result = HtmlToMarkdown::convert("<p>Below SVG:</p><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10\" height=\"10\"><rect width=\"10\" height=\"10\" fill=\"red\"/></svg>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Below SVG", $result->content);

    }


    /** Enabling capture_svg processes inline SVG elements when extract_images is on */
    public function test_options_capture_svg_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["captureSvg" => true, "extractImages" => true]));
        $result = HtmlToMarkdown::convert("<p>Below SVG:</p><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10\" height=\"10\"><rect width=\"10\" height=\"10\" fill=\"red\"/></svg>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Below SVG", $result->content);

    }


    /** Backticks code block style uses triple backtick fences */
    public function test_options_code_block_backticks(): void
    {        $options = ConversionOptions::from_json(json_encode(["codeBlockStyle" => "Backticks"]));
        $result = HtmlToMarkdown::convert("<pre><code class=\"language-js\">console.log('hi');</code></pre>", $options);

            $this->assertStringContainsString("```", $result->content);
    $this->assertStringContainsString("console.log('hi');", $result->content);

    }


    /** Code blocks use 4-space indentation */
    public function test_options_code_block_indented(): void
    {        $options = ConversionOptions::from_json(json_encode(["codeBlockStyle" => "Indented"]));
        $result = HtmlToMarkdown::convert("<pre><code>print('hello')</code></pre>", $options);

            $this->assertStringContainsString("print('hello')", $result->content);
            $this->assertStringNotContainsString("```", $result->content);

    }


    /** Code blocks use tilde fences */
    public function test_options_code_block_tildes(): void
    {        $options = ConversionOptions::from_json(json_encode(["codeBlockStyle" => "Tildes"]));
        $result = HtmlToMarkdown::convert("<pre><code>let x = 1;</code></pre>", $options);

            $this->assertStringContainsString("~~~", $result->content);
    $this->assertStringContainsString("let x = 1;", $result->content);

    }


    /** Tildes code block style uses triple tilde fences */
    public function test_options_code_block_tildes_style(): void
    {        $options = ConversionOptions::from_json(json_encode(["codeBlockStyle" => "Tildes"]));
        $result = HtmlToMarkdown::convert("<pre><code>some code</code></pre>", $options);

            $this->assertStringContainsString("~~~", $result->content);
    $this->assertStringContainsString("some code", $result->content);

    }


    /** Default code language annotation on blocks without lang attribute */
    public function test_options_code_language_python(): void
    {        $options = ConversionOptions::from_json(json_encode(["codeLanguage" => "python"]));
        $result = HtmlToMarkdown::convert("<pre><code>def hello(): pass</code></pre>", $options);

            $this->assertStringContainsString("```python", $result->content);
    $this->assertStringContainsString("def hello", $result->content);

    }


    /** compact_tables false (default) pads cells to column width */
    public function test_options_compact_tables_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["compactTables" => false]));
        $result = HtmlToMarkdown::convert("<table><thead><tr><th>Name</th><th>Score</th></tr></thead><tbody><tr><td>Alice</td><td>100</td></tr><tr><td>Bob</td><td>42</td></tr></tbody></table>", $options);

            $this->assertStringContainsString("| ----- |", $result->content);
            $this->assertStringContainsString("| 42    |", $result->content);
            $this->assertStringNotContainsString("| --- |", $result->content);

    }


    /** compact_tables emits unpadded cells and minimal --- separators */
    public function test_options_compact_tables_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["compactTables" => true]));
        $result = HtmlToMarkdown::convert("<table><thead><tr><th>Name</th><th>Score</th></tr></thead><tbody><tr><td>Alice</td><td>100</td></tr><tr><td>Bob</td><td>42</td></tr></tbody></table>", $options);

            $this->assertStringContainsString("| --- |", $result->content);
            $this->assertStringNotContainsString("| ----- |", $result->content);
            $this->assertStringContainsString("| 42 |", $result->content);
            $this->assertStringNotContainsString("| 42    |", $result->content);

    }


    /** Block elements treated as inline */
    public function test_options_convert_as_inline(): void
    {        $options = ConversionOptions::from_json(json_encode(["convertAsInline" => true]));
        $result = HtmlToMarkdown::convert("<p>One</p><p>Two</p>", $options);

            $this->assertStringContainsString("One", $result->content);
    $this->assertStringContainsString("Two", $result->content);

    }


    /** Debug mode enabled does not crash and produces output */
    public function test_options_debug_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["debug" => true]));
        $result = HtmlToMarkdown::convert("<p>Debug test</p>", $options);

            $this->assertStringContainsString("Debug test", $result->content);

    }


    /** Links without title get empty title attribute when defaultTitle is true */
    public function test_options_default_title_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["defaultTitle" => true]));
        $result = HtmlToMarkdown::convert("<p><a href='https://example.com'>Link</a></p>", $options);

            $this->assertStringContainsString("Link", $result->content);
    $this->assertStringContainsString("https://example.com", $result->content);

    }


    /** UTF-8 encoding hint for special characters */
    public function test_options_encoding_utf8(): void
    {        $options = ConversionOptions::from_json(json_encode(["encoding" => "utf-8"]));
        $result = HtmlToMarkdown::convert("<p>Café naïve résumé</p>", $options);

            $this->assertNotEmpty($result->content);

    }


    /** ASCII Markdown characters are escaped when escapeAscii is true */
    public function test_options_escape_ascii_enabled(): void
    {        $options = ConversionOptions::from_json(json_encode(["escapeAscii" => true]));
        $result = HtmlToMarkdown::convert("<p>Text with # hash and [brackets] and * star</p>", $options);

            $this->assertStringContainsString("Text", $result->content);
    $this->assertStringContainsString("hash", $result->content);
    $this->assertStringContainsString("brackets", $result->content);
    $this->assertStringContainsString("star", $result->content);

    }


    /** escape_asterisks option escapes asterisks in plain text */
    public function test_options_escape_asterisks(): void
    {        $options = ConversionOptions::from_json(json_encode(["escapeAsterisks" => true]));
        $result = HtmlToMarkdown::convert("<p>Use 2*3 = 6 in math.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("2", $result->content);
    $this->assertStringContainsString("3", $result->content);
    $this->assertStringContainsString("6", $result->content);

    }


    /** escape_misc option escapes miscellaneous markdown characters */
    public function test_options_escape_misc(): void
    {        $options = ConversionOptions::from_json(json_encode(["escapeMisc" => true]));
        $result = HtmlToMarkdown::convert("<p>Use # and | and ~ in text.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Use", $result->content);
    $this->assertStringContainsString("and", $result->content);
    $this->assertStringContainsString("in text.", $result->content);

    }


    /** escape_underscores option escapes underscores in plain text */
    public function test_options_escape_underscores(): void
    {        $options = ConversionOptions::from_json(json_encode(["escapeUnderscores" => true]));
        $result = HtmlToMarkdown::convert("<p>The variable_name is defined.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("variable", $result->content);
    $this->assertStringContainsString("name", $result->content);
    $this->assertStringContainsString("defined.", $result->content);

    }


    /** Elements matching CSS attribute selector are excluded entirely */
    public function test_options_exclude_selectors_attribute(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => ["[role='complementary']"]]));
        $result = HtmlToMarkdown::convert("<body><div role=\"complementary\">Sidebar</div><p>Primary text</p></body>", $options);

            $this->assertStringContainsString("Primary text", $result->content);
            $this->assertStringNotContainsString("Sidebar", $result->content);

    }


    /** Elements matching CSS class selector are excluded entirely */
    public function test_options_exclude_selectors_class(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => [".cookie-banner"]]));
        $result = HtmlToMarkdown::convert("<body><div class=\"cookie-banner\">Accept cookies</div><p>Main content</p></body>", $options);

            $this->assertStringContainsString("Main content", $result->content);
            $this->assertStringNotContainsString("cookies", $result->content);

    }


    /** Empty exclude_selectors list does not affect output */
    public function test_options_exclude_selectors_empty_noop(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => []]));
        $result = HtmlToMarkdown::convert("<p>Hello world</p>", $options);

            $this->assertStringContainsString("Hello world", $result->content);

    }


    /** Elements matching CSS id selector are excluded entirely */
    public function test_options_exclude_selectors_id(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => ["#ad-container"]]));
        $result = HtmlToMarkdown::convert("<body><div id=\"ad-container\">Buy stuff</div><p>Article text</p></body>", $options);

            $this->assertStringContainsString("Article text", $result->content);
            $this->assertStringNotContainsString("Buy stuff", $result->content);

    }


    /** Multiple CSS selectors each exclude their matched elements */
    public function test_options_exclude_selectors_multiple(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => [".nav", "footer"]]));
        $result = HtmlToMarkdown::convert("<body><nav class=\"nav\">Menu</nav><p>Content</p><footer>Footer</footer></body>", $options);

            $this->assertStringContainsString("Content", $result->content);
            $this->assertStringNotContainsString("Menu", $result->content);
            $this->assertStringNotContainsString("Footer", $result->content);

    }


    /** All descendants of excluded elements are dropped */
    public function test_options_exclude_selectors_nested_content_dropped(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => [".sidebar"]]));
        $result = HtmlToMarkdown::convert("<body><aside class=\"sidebar\"><h2>Related</h2><p>Sidebar text</p></aside><main><p>Main text</p></main></body>", $options);

            $this->assertStringContainsString("Main text", $result->content);
            $this->assertStringNotContainsString("Related", $result->content);
            $this->assertStringNotContainsString("Sidebar text", $result->content);

    }


    /** Exclude selectors work in plain text output mode */
    public function test_options_exclude_selectors_plain_text_mode(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => [".nav"], "outputFormat" => "Plain"]));
        $result = HtmlToMarkdown::convert("<body><div class=\"nav\">Navigation</div><p>Article body</p></body>", $options);

            $this->assertStringContainsString("Article body", $result->content);
            $this->assertStringNotContainsString("Navigation", $result->content);

    }


    /** exclude_selectors drops entire subtree unlike strip_tags which keeps children */
    public function test_options_exclude_selectors_vs_strip_tags(): void
    {        $options = ConversionOptions::from_json(json_encode(["excludeSelectors" => [".wrapper"]]));
        $result = HtmlToMarkdown::convert("<body><div class=\"wrapper\"><p>Inner paragraph</p></div><p>Outer text</p></body>", $options);

            $this->assertStringContainsString("Outer text", $result->content);
            $this->assertStringNotContainsString("Inner paragraph", $result->content);

    }


    /** When extract_images is false, conversion still succeeds and inline images are not extracted */
    public function test_options_extract_images_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractImages" => false]));
        $result = HtmlToMarkdown::convert("<p>Text with <img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==\" alt=\"pixel\"> image.</p>", $options);

            $this->assertNotEmpty($result->content);

    }


    /** Enabling extract_images processes a data-URI image without crashing */
    public function test_options_extract_images_true_data_uri(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractImages" => true]));
        $result = HtmlToMarkdown::convert("<p>Before<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==\" alt=\"pixel\">After</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Before", $result->content);
    $this->assertStringContainsString("After", $result->content);

    }


    /** Extract metadata returns document metadata when enabled */
    public function test_options_extract_metadata_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractMetadata" => true]));
        $result = HtmlToMarkdown::convert("<html><head><title>Test Page</title><meta name='description' content='A test page'></head><body><p>Content</p></body></html>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertEquals("Test Page", trim($result->getMetadata()->getDocument()->title));
            $this->assertEquals("A test page", trim($result->getMetadata()->getDocument()->description));

    }


    /** ATX heading style produces hash-prefixed headings */
    public function test_options_heading_style_atx(): void
    {        $options = ConversionOptions::from_json(json_encode(["headingStyle" => "Atx"]));
        $result = HtmlToMarkdown::convert("<h1>Title</h1><h2>Subtitle</h2>", $options);

            $this->assertStringContainsString("# Title", $result->content);
    $this->assertStringContainsString("## Subtitle", $result->content);

    }


    /** ATX closed heading style adds closing hashes */
    public function test_options_heading_style_atx_closed(): void
    {        $options = ConversionOptions::from_json(json_encode(["headingStyle" => "AtxClosed"]));
        $result = HtmlToMarkdown::convert("<h1>Closed Heading</h1>", $options);

            $this->assertStringContainsString("# Closed Heading #", $result->content);

    }


    /** Underlined heading style produces setext-style headings for h1 and h2 */
    public function test_options_heading_style_underlined(): void
    {        $options = ConversionOptions::from_json(json_encode(["headingStyle" => "Underlined"]));
        $result = HtmlToMarkdown::convert("<h1>Main Title</h1>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Main Title", $result->content);

    }


    /** Mark tag rendered as bold */
    public function test_options_highlight_bold(): void
    {        $options = ConversionOptions::from_json(json_encode(["highlightStyle" => "Bold"]));
        $result = HtmlToMarkdown::convert("<p>Text with <mark>highlighted</mark> text.</p>", $options);

            $this->assertStringContainsString("**highlighted**", $result->content);

    }


    /** Mark tag with double equal highlight style */
    public function test_options_highlight_double_equal(): void
    {        $options = ConversionOptions::from_json(json_encode(["highlightStyle" => "DoubleEqual"]));
        $result = HtmlToMarkdown::convert("<p>Text with <mark>highlighted</mark> here.</p>", $options);

            $this->assertStringContainsString("==highlighted==", $result->content);

    }


    /** Mark tag with no highlight style strips the mark */
    public function test_options_highlight_none(): void
    {        $options = ConversionOptions::from_json(json_encode(["highlightStyle" => "None"]));
        $result = HtmlToMarkdown::convert("<p>Text with <mark>plain</mark> content.</p>", $options);

            $this->assertStringContainsString("plain", $result->content);
            $this->assertStringNotContainsString("==", $result->content);

    }


    /** Disabling include_document_structure still produces content without the document tree overhead */
    public function test_options_include_document_structure_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["includeDocumentStructure" => false]));
        $result = HtmlToMarkdown::convert("<article><h1>Heading</h1><p>Paragraph body.</p></article>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Heading", $result->content);

    }


    /** Setting include_document_structure populates the structured document tree on the result */
    public function test_options_include_document_structure_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["includeDocumentStructure" => true]));
        $result = HtmlToMarkdown::convert("<article><h1>Heading</h1><p>Paragraph body.</p></article>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Heading", $result->content);

    }


    /** Disabling infer_dimensions skips the decode step and still produces content */
    public function test_options_infer_dimensions_false(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractImages" => true, "inferDimensions" => false]));
        $result = HtmlToMarkdown::convert("<p>No dims: <img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==\" alt=\"pixel\"></p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("No dims", $result->content);

    }


    /** Enabling infer_dimensions decodes image bytes to populate dimension metadata when extract_images is on */
    public function test_options_infer_dimensions_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractImages" => true, "inferDimensions" => true]));
        $result = HtmlToMarkdown::convert("<p>With dims: <img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==\" alt=\"pixel\"></p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("With dims", $result->content);

    }


    /** Images inside specified tags stay inline */
    public function test_options_keep_inline_images_in_paragraph(): void
    {        $options = ConversionOptions::from_json(json_encode(["keepInlineImagesIn" => ["p"]]));
        $result = HtmlToMarkdown::convert("<p>Text <img src='icon.png' alt='icon'> more text</p>", $options);

            $this->assertStringContainsString("Text", $result->content);
    $this->assertStringContainsString("more text", $result->content);

    }


    /** Links use reference-style formatting */
    public function test_options_link_style_reference(): void
    {        $options = ConversionOptions::from_json(json_encode(["linkStyle" => "Reference"]));
        $result = HtmlToMarkdown::convert("<p><a href='https://example.com'>Example</a> and <a href='https://other.com'>Other</a></p>", $options);

            $this->assertStringContainsString("Example", $result->content);
    $this->assertStringContainsString("Other", $result->content);
    $this->assertStringContainsString("example.com", $result->content);

    }


    /** Custom bullet character for unordered lists */
    public function test_options_list_custom_bullets(): void
    {        $options = ConversionOptions::from_json(json_encode(["bullets" => "*"]));
        $result = HtmlToMarkdown::convert("<ul><li>Item A</li><li>Item B</li></ul>", $options);

            $this->assertStringContainsString("* Item A", $result->content);
    $this->assertStringContainsString("* Item B", $result->content);

    }


    /** Tab indentation type for nested list items */
    public function test_options_list_indent_tabs(): void
    {        $options = ConversionOptions::from_json(json_encode(["listIndentType" => "Tabs"]));
        $result = HtmlToMarkdown::convert("<ul><li>Parent<ul><li>Child</li></ul></li></ul>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Parent", $result->content);
    $this->assertStringContainsString("Child", $result->content);

    }


    /** Nested lists indented with 4 spaces per level */
    public function test_options_list_indent_width_four(): void
    {        $options = ConversionOptions::from_json(json_encode(["listIndentWidth" => 4]));
        $result = HtmlToMarkdown::convert("<ul><li>Outer<ul><li>Inner</li></ul></li></ul>", $options);

            $this->assertStringContainsString("Outer", $result->content);
    $this->assertStringContainsString("Inner", $result->content);

    }


    /** Default max_depth (null) converts deeply nested content fully */
    public function test_options_max_depth_default_unlimited(): void
    {        $result = HtmlToMarkdown::convert("<div><div><div><div><p>Deep content</p></div></div></div></div>");

            $this->assertStringContainsString("Deep content", $result->content);

    }


    /** max_depth truncates content beyond the specified depth */
    public function test_options_max_depth_truncates(): void
    {        $options = ConversionOptions::from_json(json_encode(["maxDepth" => 3]));
        $result = HtmlToMarkdown::convert("<div><p>Shallow</p><div><div><div><p>Too deep</p></div></div></div></div>", $options);

            $this->assertStringContainsString("Shallow", $result->content);
            $this->assertStringNotContainsString("Too deep", $result->content);

    }


    /** max_depth of 0 produces empty output */
    public function test_options_max_depth_zero_empty(): void
    {        $options = ConversionOptions::from_json(json_encode(["maxDepth" => 0]));
        $result = HtmlToMarkdown::convert("<p>Hello</p>", $options);

            $this->assertEquals("", trim($result->content));

    }


    /** A generous max_image_size accommodates a small data-URI image without warnings */
    public function test_options_max_image_size_generous_limit(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractImages" => true, "maxImageSize" => 10485760]));
        $result = HtmlToMarkdown::convert("<p>Image: <img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==\" alt=\"pixel\"></p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Image", $result->content);

    }


    /** A tiny max_image_size does not crash conversion even when the image exceeds the limit */
    public function test_options_max_image_size_tiny_limit_safe(): void
    {        $options = ConversionOptions::from_json(json_encode(["extractImages" => true, "maxImageSize" => 10]));
        $result = HtmlToMarkdown::convert("<p>Tiny limit: <img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==\" alt=\"pixel\"></p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Tiny limit", $result->content);

    }


    /** Hard line breaks rendered with backslash */
    public function test_options_newline_backslash(): void
    {        $options = ConversionOptions::from_json(json_encode(["newlineStyle" => "Backslash"]));
        $result = HtmlToMarkdown::convert("<p>Line one<br>Line two</p>", $options);

            $this->assertStringContainsString("Line one", $result->content);
    $this->assertStringContainsString("Line two", $result->content);

    }


    /** Hard line breaks rendered with trailing spaces */
    public function test_options_newline_spaces(): void
    {        $options = ConversionOptions::from_json(json_encode(["newlineStyle" => "Spaces"]));
        $result = HtmlToMarkdown::convert("<p>First<br>Second</p>", $options);

            $this->assertStringContainsString("First", $result->content);
    $this->assertStringContainsString("Second", $result->content);

    }


    /** Djot output format produces djot-compatible markup */
    public function test_options_output_format_djot(): void
    {        $options = ConversionOptions::from_json(json_encode(["outputFormat" => "Djot"]));
        $result = HtmlToMarkdown::convert("<p>Simple paragraph.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Simple paragraph.", $result->content);

    }


    /** Default markdown output format produces standard markdown */
    public function test_options_output_format_markdown(): void
    {        $options = ConversionOptions::from_json(json_encode(["headingStyle" => "Atx", "outputFormat" => "Markdown"]));
        $result = HtmlToMarkdown::convert("<h1>Title</h1><p>Some text.</p>", $options);

            $this->assertStringContainsString("# Title", $result->content);
    $this->assertStringContainsString("Some text.", $result->content);

    }


    /** Plain text output format strips markdown syntax */
    public function test_options_output_format_plain(): void
    {        $options = ConversionOptions::from_json(json_encode(["outputFormat" => "Plain"]));
        $result = HtmlToMarkdown::convert("<h1>Title</h1><p>Some <strong>bold</strong> text.</p>", $options);

            $this->assertStringContainsString("Title", $result->content);
    $this->assertStringContainsString("bold", $result->content);
    $this->assertStringContainsString("text.", $result->content);
            $this->assertStringNotContainsString("**bold**", $result->content);
    $this->assertStringNotContainsString("# Title", $result->content);

    }


    /** Aggressive preset removes nav, footer, aside unconditionally */
    public function test_options_preprocessing_aggressive(): void
    {        $options = ConversionOptions::from_json(json_encode(["preprocessing" => ["preset" => "Aggressive"]]));
        $result = HtmlToMarkdown::convert("<nav>Menu</nav><article><h1>Title</h1><p>Content</p></article><aside>Sidebar</aside><footer>Footer</footer>", $options);

            $this->assertStringContainsString("Title", $result->content);
    $this->assertStringContainsString("Content", $result->content);
            $this->assertStringNotContainsString("Menu", $result->content);

    }


    /** Disabling preprocessing entirely preserves elements the standard preset would remove */
    public function test_options_preprocessing_enabled_false_skips_cleanup(): void
    {        $options = ConversionOptions::from_json(json_encode(["preprocessing" => ["enabled" => false]]));
        $result = HtmlToMarkdown::convert("<nav>NavSection</nav><p>Paragraph</p>", $options);

            $this->assertStringContainsString("NavSection", $result->content);
    $this->assertStringContainsString("Paragraph", $result->content);

    }


    /** Minimal preset preserves nav, footer, aside */
    public function test_options_preprocessing_minimal(): void
    {        $options = ConversionOptions::from_json(json_encode(["preprocessing" => ["preset" => "Minimal"]]));
        $result = HtmlToMarkdown::convert("<nav>Navigation</nav><p>Content</p><footer>Footer</footer>", $options);

            $this->assertStringContainsString("Navigation", $result->content);
    $this->assertStringContainsString("Content", $result->content);
    $this->assertStringContainsString("Footer", $result->content);

    }


    /** Forms are removed when remove_forms is true */
    public function test_options_preprocessing_remove_forms(): void
    {        $options = ConversionOptions::from_json(json_encode(["preprocessing" => ["removeForms" => true]]));
        $result = HtmlToMarkdown::convert("<p>Before</p><form><input type='text'/><button>Submit</button></form><p>After</p>", $options);

            $this->assertStringContainsString("Before", $result->content);
    $this->assertStringContainsString("After", $result->content);
            $this->assertStringNotContainsString("Submit", $result->content);

    }


    /** Setting remove_navigation to false preserves nav and aside elements */
    public function test_options_preprocessing_remove_navigation_false_keeps_nav(): void
    {        $options = ConversionOptions::from_json(json_encode(["preprocessing" => ["removeNavigation" => false]]));
        $result = HtmlToMarkdown::convert("<nav>SiteMenu</nav><main><p>MainContent</p></main><aside>SidebarText</aside>", $options);

            $this->assertStringContainsString("SiteMenu", $result->content);
    $this->assertStringContainsString("MainContent", $result->content);
    $this->assertStringContainsString("SidebarText", $result->content);

    }


    /** Iframe tags preserved as raw HTML in output */
    public function test_options_preserve_tags_iframe(): void
    {        $options = ConversionOptions::from_json(json_encode(["preserveTags" => ["iframe"]]));
        $result = HtmlToMarkdown::convert("<p>Before</p><iframe src='video.html' width='560'></iframe><p>After</p>", $options);

            $this->assertStringContainsString("Before", $result->content);
    $this->assertStringContainsString("After", $result->content);
    $this->assertStringContainsString("<iframe", $result->content);

    }


    /** Images are omitted from output when skipImages is true */
    public function test_options_skip_images_true(): void
    {        $options = ConversionOptions::from_json(json_encode(["skipImages" => true]));
        $result = HtmlToMarkdown::convert("<p>Before <img src='test.jpg' alt='photo'> After</p>", $options);

            $this->assertStringContainsString("Before", $result->content);
    $this->assertStringContainsString("After", $result->content);
            $this->assertStringNotContainsString("photo", $result->content);

    }


    /** Strip newlines produces single-line paragraphs */
    public function test_options_strip_newlines(): void
    {        $options = ConversionOptions::from_json(json_encode(["stripNewlines" => true]));
        $result = HtmlToMarkdown::convert("<p>First paragraph.</p><p>Second paragraph.</p>", $options);

            $this->assertStringContainsString("First paragraph.", $result->content);
    $this->assertStringContainsString("Second paragraph.", $result->content);

    }


    /** Div and span tags stripped but content preserved */
    public function test_options_strip_tags_div_span(): void
    {        $options = ConversionOptions::from_json(json_encode(["stripTags" => ["div", "span"]]));
        $result = HtmlToMarkdown::convert("<div class='wrapper'><p>Inside div</p></div><p>Outside <span class='hl'>span text</span></p>", $options);

            $this->assertStringContainsString("Inside div", $result->content);
    $this->assertStringContainsString("span text", $result->content);

    }


    /** Strong and em tags use underscore symbol instead of asterisk */
    public function test_options_strong_em_underscore(): void
    {        $options = ConversionOptions::from_json(json_encode(["strongEmSymbol" => "_"]));
        $result = HtmlToMarkdown::convert("<p><strong>bold</strong> and <em>italic</em></p>", $options);

            $this->assertStringContainsString("__bold__", $result->content);
    $this->assertStringContainsString("_italic_", $result->content);

    }


    /** Subscript rendered with tilde symbol */
    public function test_options_sub_symbol_tilde(): void
    {        $options = ConversionOptions::from_json(json_encode(["subSymbol" => "~"]));
        $result = HtmlToMarkdown::convert("<p>H<sub>2</sub>O</p>", $options);

            $this->assertStringContainsString("~2~", $result->content);

    }


    /** Superscript rendered with caret symbol */
    public function test_options_sup_symbol_caret(): void
    {        $options = ConversionOptions::from_json(json_encode(["supSymbol" => "^"]));
        $result = HtmlToMarkdown::convert("<p>x<sup>2</sup></p>", $options);

            $this->assertStringContainsString("^2^", $result->content);

    }


    /** Normalized whitespace mode collapses multiple spaces */
    public function test_options_whitespace_normalized(): void
    {        $options = ConversionOptions::from_json(json_encode(["whitespaceMode" => "Normalized"]));
        $result = HtmlToMarkdown::convert("<p>Text   with    extra   spaces.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Text", $result->content);
    $this->assertStringContainsString("with", $result->content);
    $this->assertStringContainsString("extra", $result->content);
    $this->assertStringContainsString("spaces.", $result->content);

    }


    /** Strict whitespace mode preserves whitespace as-is */
    public function test_options_whitespace_strict(): void
    {        $options = ConversionOptions::from_json(json_encode(["whitespaceMode" => "Strict"]));
        $result = HtmlToMarkdown::convert("<p>Preserved   spacing.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("Preserved", $result->content);
    $this->assertStringContainsString("spacing.", $result->content);

    }


    /** Wrap option disabled preserves long lines without breaking */
    public function test_options_wrap_disabled(): void
    {        $options = ConversionOptions::from_json(json_encode(["wrap" => false]));
        $result = HtmlToMarkdown::convert("<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>", $options);

            $this->assertStringContainsString("This is a long paragraph that should not be wrapped at all because wrapping is disabled.", $result->content);

    }


    /** Wrap option enabled with custom width wraps long lines */
    public function test_options_wrap_enabled(): void
    {        $options = ConversionOptions::from_json(json_encode(["wrap" => true, "wrapWidth" => 40]));
        $result = HtmlToMarkdown::convert("<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>", $options);

            $this->assertNotEmpty($result->content);
            $this->assertStringContainsString("This is a long paragraph", $result->content);

    }

}
