<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7557045bc37abac5566d686c3712d3074a3948d00a20f776bf3ed491055d4f11
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use HtmlToMarkdown\HtmlToMarkdown;

/** E2e tests for category: visitor. */
final class VisitorTest extends TestCase
{
    /** Visitor replaces audio element with custom output */
    public function test_visitor_audio_custom(): void
    {
        $visitor = new class {
            public function visit_audio($ctx, $src) {
                return ['custom' => [AUDIO: podcast.mp3]];
            }
        };
        $result = HtmlToMarkdown::convert("<p>Listen to this: <audio src=\"podcast.mp3\" controls></audio></p>", $visitor);
        $this->assertStringContainsString("[AUDIO: podcast.mp3]", $result);
        $this->assertStringContainsString("Listen to this:", $result);
    }

    /** Visitor removes audio elements from output */
    public function test_visitor_audio_skip(): void
    {
        $visitor = new class {
            public function visit_audio($ctx, $src) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Background music:</p><audio src=\"music.ogg\" autoplay></audio><p>Enjoy!</p>", $visitor);
        $this->assertStringContainsString("Background music:", $result);
        $this->assertStringContainsString("Enjoy!", $result);
        $this->assertStringNotContainsString("music.ogg", $result);
    }

    /** Visitor replaces button with bracketed text */
    public function test_visitor_button_custom(): void
    {
        $visitor = new class {
            public function visit_button($ctx, $text) {
                return ['custom' => [BTN:{text}]];
            }
        };
        $result = HtmlToMarkdown::convert("<p>Confirm action: <button type=\"submit\">Click me</button> or <button type=\"reset\">Cancel</button></p>", $visitor);
        $this->assertStringContainsString("[BTN:Click me]", $result);
        $this->assertStringContainsString("[BTN:Cancel]", $result);
        $this->assertStringContainsString("Confirm action:", $result);
    }

    /** Visitor removes all buttons from output */
    public function test_visitor_button_skip(): void
    {
        $visitor = new class {
            public function visit_button($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Actions available: <button>Save</button> <button>Delete</button> <button>Export</button></p>", $visitor);
        $this->assertStringContainsString("Actions available:", $result);
        $this->assertStringNotContainsString("Save", $result);
        $this->assertStringNotContainsString("Delete", $result);
        $this->assertStringNotContainsString("Export", $result);
    }

    /** Visitor continue action preserves default conversion */
    public function test_visitor_continue_default(): void
    {
        $visitor = new class {
            public function visit_strong($ctx, $text) {
                return 'continue';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Hello <strong>World</strong></p>", $visitor);
        $this->assertStringContainsString("**World**", $result);
    }

    /** Visitor replaces blockquote with custom format */
    public function test_visitor_custom_blockquote(): void
    {
        $visitor = new class {
            public function visit_blockquote($ctx, $content, $depth) {
                return ['custom' => QUOTE: \"{content}\"];
            }
        };
        $result = HtmlToMarkdown::convert("<blockquote><p>A wise quote.</p></blockquote>", $visitor);
        $this->assertStringContainsString("QUOTE:", $result);
        $this->assertStringContainsString("A wise quote.", $result);
    }

    /** Visitor replaces emphasis with custom output */
    public function test_visitor_custom_emphasis(): void
    {
        $visitor = new class {
            public function visit_emphasis($ctx, $text) {
                return ['custom' => >>>{text}<<<];
            }
        };
        $result = HtmlToMarkdown::convert("<p>This is <em>important</em> text.</p>", $visitor);
        $this->assertStringContainsString(">>>important<<<", $result);
        $this->assertStringNotContainsString("*important*", $result);
    }

    /** Visitor replaces heading with custom format */
    public function test_visitor_custom_heading(): void
    {
        $visitor = new class {
            public function visit_heading($ctx, $level, $text, $id) {
                return ['custom' => --- {text} ---];
            }
        };
        $result = HtmlToMarkdown::convert("<h2>Section Title</h2><p>Content below heading.</p>", $visitor);
        $this->assertStringContainsString("--- Section Title ---", $result);
        $this->assertStringNotContainsString("## Section Title", $result);
        $this->assertStringContainsString("Content below heading.", $result);
    }

    /** Visitor replaces image with custom output using template */
    public function test_visitor_custom_image(): void
    {
        $visitor = new class {
            public function visit_image($ctx, $src, $alt, $title) {
                return ['custom' => [Image: {alt}]];
            }
        };
        $result = HtmlToMarkdown::convert("<img src=\"banner.png\" alt=\"Banner\">", $visitor);
        $this->assertStringContainsString("[Image: Banner]", $result);
        $this->assertStringNotContainsString("banner.png", $result);
    }

    /** Visitor reformats links using template interpolation */
    public function test_visitor_custom_link_format(): void
    {
        $visitor = new class {
            public function visit_link($ctx, $href, $text, $title) {
                return ['custom' => {text} ({href})];
            }
        };
        $result = HtmlToMarkdown::convert("<p>Visit <a href=\"https://example.com\">Example</a> for more info.</p>", $visitor);
        $this->assertStringContainsString("Example (https://example.com)", $result);
        $this->assertStringNotContainsString("[Example]", $result);
    }

    /** Visitor replaces link with static custom output */
    public function test_visitor_custom_link_static(): void
    {
        $visitor = new class {
            public function visit_link($ctx, $href, $text, $title) {
                return ['custom' => [REDACTED LINK]];
            }
        };
        $result = HtmlToMarkdown::convert("<a href=\"https://example.com\">Click here</a>", $visitor);
        $this->assertStringContainsString("[REDACTED LINK]", $result);
        $this->assertStringNotContainsString("example.com", $result);
    }

    /** Visitor custom action replaces element output */
    public function test_visitor_custom_output(): void
    {
        $visitor = new class {
            public function visit_heading($ctx, $level, $text, $id) {
                return ['custom' => ## REPLACED HEADING];
            }
        };
        $result = HtmlToMarkdown::convert("<h1>Original Heading</h1>", $visitor);
        $this->assertStringContainsString("## REPLACED HEADING", $result);
        $this->assertStringNotContainsString("# Original Heading", $result);
    }

    /** Visitor customizes definition list items */
    public function test_visitor_definition_list_custom(): void
    {
        $visitor = new class {
            public function visit_definition_term($ctx, $text) {
                return ['custom' => **{text}**];
            }
        };
        $result = HtmlToMarkdown::convert("<dl><dt>HTML</dt><dd>HyperText Markup Language</dd><dt>CSS</dt><dd>Cascading Style Sheets</dd></dl>", $visitor);
        $this->assertStringContainsString("**HTML**", $result);
        $this->assertStringContainsString("**CSS**", $result);
        $this->assertStringContainsString("HyperText Markup Language", $result);
    }

    /** Visitor formats definition lists with custom templates */
    public function test_visitor_definition_list_custom_format(): void
    {
        $visitor = new class {
            public function visit_definition_description($ctx, $text) {
                return ['custom' => > {text}];
            }
            public function visit_definition_term($ctx, $text) {
                return ['custom' => ### {text}];
            }
        };
        $result = HtmlToMarkdown::convert("<dl><dt>Python</dt><dd>A high-level programming language</dd><dt>JavaScript</dt><dd>A scripting language for web browsers</dd></dl>", $visitor);
        $this->assertStringContainsString("### Python", $result);
        $this->assertStringContainsString("### JavaScript", $result);
        $this->assertStringContainsString("> A high-level programming language", $result);
        $this->assertStringContainsString("> A scripting language for web browsers", $result);
    }

    /** Visitor skips definition list items from output */
    public function test_visitor_definition_list_skip(): void
    {
        $visitor = new class {
            public function visit_definition_term($ctx, $text) {
                return 'skip';
            }
            public function visit_definition_description($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Glossary:</p><dl><dt>Term A</dt><dd>Definition of term A</dd><dt>Term B</dt><dd>Definition of term B</dd></dl><p>End of glossary</p>", $visitor);
        $this->assertStringContainsString("Glossary:", $result);
        $this->assertStringContainsString("End of glossary", $result);
        $this->assertStringNotContainsString("Term A", $result);
        $this->assertStringNotContainsString("Definition", $result);
    }

    /** Visitor customizes details/summary disclosure elements */
    public function test_visitor_details_summary_custom(): void
    {
        $visitor = new class {
            public function visit_summary($ctx, $text) {
                return ['custom' => [EXPANDABLE] {text}];
            }
        };
        $result = HtmlToMarkdown::convert("<details><summary>Click to expand</summary><p>This content is initially hidden.</p><p>But can be revealed by the user.</p></details>", $visitor);
        $this->assertStringContainsString("[EXPANDABLE] Click to expand", $result);
        $this->assertStringContainsString("This content is initially hidden.", $result);
    }

    /** Visitor removes details/summary elements entirely */
    public function test_visitor_details_summary_skip(): void
    {
        $visitor = new class {
            public function visit_details($ctx, $isOpen) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Main content here.</p><details><summary>Hidden section</summary><p>Secret details</p></details><p>More main content.</p>", $visitor);
        $this->assertStringContainsString("Main content here.", $result);
        $this->assertStringContainsString("More main content.", $result);
        $this->assertStringNotContainsString("Hidden section", $result);
        $this->assertStringNotContainsString("Secret details", $result);
    }

    /** Visitor customizes figure and figcaption elements */
    public function test_visitor_figure_custom(): void
    {
        $visitor = new class {
            public function visit_figcaption($ctx, $text) {
                return ['custom' => *{text}*];
            }
        };
        $result = HtmlToMarkdown::convert("<article><h1>Article Title</h1><p>Introduction paragraph.</p><figure><img src=\"diagram.png\" alt=\"System architecture diagram\"><figcaption>Figure 1: System Architecture</figcaption></figure><p>Explanation of the figure.</p></article>", $visitor);
        $this->assertStringContainsString("Article Title", $result);
        $this->assertStringContainsString("*Figure 1: System Architecture*", $result);
        $this->assertStringContainsString("Explanation of the figure.", $result);
    }

    /** Visitor wraps figure content with custom formatting */
    public function test_visitor_figure_custom_wrap(): void
    {
        $visitor = new class {
            public function visit_figure_start($ctx) {
                return ['custom' => \n[FIGURE]\n];
            }
            public function visit_figure_end($ctx, $output) {
                return ['custom' => {output}\n[/FIGURE]\n];
            }
        };
        $result = HtmlToMarkdown::convert("<section><h2>Gallery</h2><figure><img src=\"photo1.jpg\" alt=\"Photo\"><figcaption>Beautiful sunset</figcaption></figure></section>", $visitor);
        $this->assertStringContainsString("[FIGURE]", $result);
        $this->assertStringContainsString("[/FIGURE]", $result);
        $this->assertStringContainsString("Gallery", $result);
    }

    /** Visitor removes figure elements with their captions */
    public function test_visitor_figure_skip(): void
    {
        $visitor = new class {
            public function visit_figure_start($ctx) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>See the chart below:</p><figure><img src=\"chart.svg\"><figcaption>Revenue Trends 2020-2024</figcaption></figure><p>As shown in the chart above.</p>", $visitor);
        $this->assertStringContainsString("See the chart below:", $result);
        $this->assertStringContainsString("As shown in the chart above.", $result);
        $this->assertStringNotContainsString("Revenue Trends", $result);
        $this->assertStringNotContainsString("chart.svg", $result);
    }

    /** Visitor replaces form with custom output */
    public function test_visitor_form_custom(): void
    {
        $visitor = new class {
            public function visit_form($ctx, $actionUrl, $method) {
                return ['custom' => [FORM PLACEHOLDER]];
            }
        };
        $result = HtmlToMarkdown::convert("<div><form action=\"/submit\" method=\"POST\"><label>Name: <input type=\"text\" name=\"name\"></label><button type=\"submit\">Submit</button></form></div>", $visitor);
        $this->assertStringContainsString("[FORM PLACEHOLDER]", $result);
        $this->assertStringNotContainsString("submit", $result);
        $this->assertStringNotContainsString("input", $result);
    }

    /** Visitor skips form elements entirely */
    public function test_visitor_form_skip(): void
    {
        $visitor = new class {
            public function visit_form($ctx, $actionUrl, $method) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Before form</p><form><input type=\"email\" name=\"email\"></form><p>After form</p>", $visitor);
        $this->assertStringContainsString("Before form", $result);
        $this->assertStringContainsString("After form", $result);
        $this->assertStringNotContainsString("email", $result);
    }

    /** Visitor replaces horizontal rule with custom output */
    public function test_visitor_horizontal_rule_custom(): void
    {
        $visitor = new class {
            public function visit_horizontal_rule($ctx) {
                return ['custom' => \n[DIVIDER]\n];
            }
        };
        $result = HtmlToMarkdown::convert("<h1>Section A</h1><p>Content A</p><hr><h1>Section B</h1><p>Content B</p>", $visitor);
        $this->assertStringContainsString("[DIVIDER]", $result);
        $this->assertStringContainsString("Section A", $result);
        $this->assertStringContainsString("Section B", $result);
        $this->assertStringNotContainsString("---", $result);
    }

    /** Visitor removes all horizontal rules */
    public function test_visitor_horizontal_rule_skip(): void
    {
        $visitor = new class {
            public function visit_horizontal_rule($ctx) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Part 1</p><hr><p>Part 2</p><hr><p>Part 3</p>", $visitor);
        $this->assertStringContainsString("Part 1", $result);
        $this->assertStringContainsString("Part 2", $result);
        $this->assertStringContainsString("Part 3", $result);
        $this->assertStringNotContainsString("---", $result);
    }

    /** Visitor replaces embedded iframe with custom text */
    public function test_visitor_iframe_custom(): void
    {
        $visitor = new class {
            public function visit_iframe($ctx, $src) {
                return ['custom' => [EMBEDDED: https://maps.example.com/embed]];
            }
        };
        $result = HtmlToMarkdown::convert("<p>Embedded map:</p><iframe src=\"https://maps.example.com/embed\" width=\"400\" height=\"300\"></iframe><p>End of map</p>", $visitor);
        $this->assertStringContainsString("[EMBEDDED: https://maps.example.com/embed]", $result);
        $this->assertStringContainsString("Embedded map:", $result);
        $this->assertStringContainsString("End of map", $result);
    }

    /** Visitor removes embedded iframes */
    public function test_visitor_iframe_skip(): void
    {
        $visitor = new class {
            public function visit_iframe($ctx, $src) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<h3>Reviews</h3><iframe src=\"https://widget.example.com/reviews\"></iframe><p>See reviews from our partners.</p>", $visitor);
        $this->assertStringContainsString("Reviews", $result);
        $this->assertStringContainsString("See reviews from our partners.", $result);
        $this->assertStringNotContainsString("widget.example.com", $result);
    }

    /** Visitor replaces input with labeled output */
    public function test_visitor_input_custom(): void
    {
        $visitor = new class {
            public function visit_input($ctx, $inputType, $name, $value) {
                return ['custom' => [INPUT:{input_type}]];
            }
        };
        $result = HtmlToMarkdown::convert("<form><label>Username: <input type=\"text\" name=\"username\" value=\"\"></label><label>Password: <input type=\"password\" name=\"password\"></label></form>", $visitor);
        $this->assertStringContainsString("[INPUT:text]", $result);
        $this->assertStringContainsString("[INPUT:password]", $result);
    }

    /** Visitor skips all input elements */
    public function test_visitor_input_skip(): void
    {
        $visitor = new class {
            public function visit_input($ctx, $inputType, $name, $value) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Sign up:</p><input type=\"text\" name=\"email\" placeholder=\"your@email.com\"><input type=\"checkbox\" name=\"agree\"><p>Continue</p>", $visitor);
        $this->assertStringContainsString("Sign up:", $result);
        $this->assertStringContainsString("Continue", $result);
        $this->assertStringNotContainsString("email", $result);
    }

    /** Visitor replaces line break with custom output */
    public function test_visitor_line_break_custom(): void
    {
        $visitor = new class {
            public function visit_line_break($ctx) {
                return ['custom' =>  | ];
            }
        };
        $result = HtmlToMarkdown::convert("<p>First line<br>Second line<br>Third line</p>", $visitor);
        $this->assertStringContainsString("First line | Second line | Third line", $result);
        $this->assertStringNotContainsString("\n\n", $result);
    }

    /** Visitor removes all line breaks */
    public function test_visitor_line_break_skip(): void
    {
        $visitor = new class {
            public function visit_line_break($ctx) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Address Line 1<br>Address Line 2<br>Address Line 3</p>", $visitor);
        $this->assertStringContainsString("Address Line 1Address Line 2Address Line 3", $result);
    }

    /** Visitor replaces highlight/mark with custom template */
    public function test_visitor_mark_custom(): void
    {
        $visitor = new class {
            public function visit_mark($ctx, $text) {
                return ['custom' => =={text}==];
            }
        };
        $result = HtmlToMarkdown::convert("<p>This is a <mark>highlighted passage</mark> in the text.</p>", $visitor);
        $this->assertStringContainsString("==highlighted passage==", $result);
        $this->assertStringContainsString("This is a", $result);
    }

    /** Visitor skips mark elements entirely */
    public function test_visitor_mark_skip(): void
    {
        $visitor = new class {
            public function visit_mark($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Key insight: <mark>always validate input</mark> for security.</p>", $visitor);
        $this->assertStringNotContainsString("always validate input", $result);
        $this->assertStringContainsString("Key insight:", $result);
        $this->assertStringContainsString("for security.", $result);
    }

    /** Visitor preserve_html action includes raw HTML in output */
    public function test_visitor_preserve_html(): void
    {
        $visitor = new class {
            public function visit_custom_element($ctx, $tagName, $html) {
                return 'preserve_html';
            }
        };
        $result = HtmlToMarkdown::convert("<div><custom-tag>Custom content</custom-tag></div>", $visitor);
        $this->assertStringContainsString("<custom-tag>", $result);
    }

    /** Visitor skips all headings from document */
    public function test_visitor_skip_all_headings(): void
    {
        $visitor = new class {
            public function visit_heading($ctx, $level, $text, $id) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<h1>Title</h1><p>Body text remains.</p>", $visitor);
        $this->assertStringNotContainsString("Title", $result);
        $this->assertStringContainsString("Body text remains.", $result);
    }

    /** Visitor skips code blocks from output */
    public function test_visitor_skip_code_blocks(): void
    {
        $visitor = new class {
            public function visit_code_block($ctx, $lang, $code) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>", $visitor);
        $this->assertStringContainsString("Intro text", $result);
        $this->assertStringContainsString("Outro text", $result);
        $this->assertStringNotContainsString("let x = 42", $result);
    }

    /** Visitor skip action omits all headings from output */
    public function test_visitor_skip_heading(): void
    {
        $visitor = new class {
            public function visit_heading($ctx, $level, $text, $id) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<h1>Title</h1><p>Body text remains.</p>", $visitor);
        $this->assertStringNotContainsString("Title", $result);
        $this->assertStringContainsString("Body text remains.", $result);
    }

    /** Visitor skips all images from output */
    public function test_visitor_skip_images(): void
    {
        $visitor = new class {
            public function visit_image($ctx, $src, $alt, $title) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Before image</p><img src=\"photo.jpg\" alt=\"A photo\"><p>After image</p>", $visitor);
        $this->assertStringContainsString("Before image", $result);
        $this->assertStringContainsString("After image", $result);
        $this->assertStringNotContainsString("photo.jpg", $result);
        $this->assertStringNotContainsString("A photo", $result);
    }

    /** Visitor skips all links entirely */
    public function test_visitor_skip_links(): void
    {
        $visitor = new class {
            public function visit_link($ctx, $href, $text, $title) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Before <a href=\"https://example.com\">link text</a> after</p>", $visitor);
        $this->assertStringNotContainsString("link text", $result);
        $this->assertStringNotContainsString("example.com", $result);
    }

    /** Visitor skips bold/strong elements */
    public function test_visitor_skip_strong(): void
    {
        $visitor = new class {
            public function visit_strong($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Normal <strong>bold text</strong> normal</p>", $visitor);
        $this->assertStringNotContainsString("bold text", $result);
        $this->assertStringContainsString("Normal", $result);
    }

    /** Visitor replaces subscript with custom template */
    public function test_visitor_subscript_custom(): void
    {
        $visitor = new class {
            public function visit_subscript($ctx, $text) {
                return ['custom' => ~{text}~];
            }
        };
        $result = HtmlToMarkdown::convert("<p>H<sub>2</sub>O is water.</p>", $visitor);
        $this->assertStringContainsString("H~2~O", $result);
        $this->assertStringContainsString("is water", $result);
    }

    /** Visitor skips subscript elements entirely */
    public function test_visitor_subscript_skip(): void
    {
        $visitor = new class {
            public function visit_subscript($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>The formula C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> is sugar.</p>", $visitor);
        $this->assertStringContainsString("The formula CHO is sugar.", $result);
    }

    /** Visitor replaces superscript with custom template */
    public function test_visitor_superscript_custom(): void
    {
        $visitor = new class {
            public function visit_superscript($ctx, $text) {
                return ['custom' => ^{text}^];
            }
        };
        $result = HtmlToMarkdown::convert("<p>Einstein's E=mc<sup>2</sup> revolutionized physics.</p>", $visitor);
        $this->assertStringContainsString("E=mc^2^", $result);
        $this->assertStringContainsString("revolutionized physics", $result);
    }

    /** Visitor skips superscript from output */
    public function test_visitor_superscript_skip(): void
    {
        $visitor = new class {
            public function visit_superscript($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>The equation x<sup>3</sup> + y<sup>3</sup> = z<sup>3</sup> has no solutions.</p>", $visitor);
        $this->assertStringContainsString("The equation x + y = z has no solutions.", $result);
    }

    /** Visitor replaces underline with custom markup */
    public function test_visitor_underline_custom(): void
    {
        $visitor = new class {
            public function visit_underline($ctx, $text) {
                return ['custom' => _{text}_];
            }
        };
        $result = HtmlToMarkdown::convert("<p>This is <u>very important</u> text.</p>", $visitor);
        $this->assertStringContainsString("_very important_", $result);
        $this->assertStringNotContainsString("**", $result);
    }

    /** Visitor skips underline elements from output */
    public function test_visitor_underline_skip(): void
    {
        $visitor = new class {
            public function visit_underline($ctx, $text) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<p>Normal text with <u>underlined part</u> and more text.</p>", $visitor);
        $this->assertStringContainsString("Normal text with", $result);
        $this->assertStringContainsString("and more text.", $result);
        $this->assertStringNotContainsString("underlined part", $result);
    }

    /** Visitor replaces video with custom link */
    public function test_visitor_video_custom(): void
    {
        $visitor = new class {
            public function visit_video($ctx, $src) {
                return ['custom' => [VIDEO: {src}]];
            }
        };
        $result = HtmlToMarkdown::convert("<p>Watch our tutorial:</p><video src=\"tutorial.mp4\" width=\"320\" height=\"240\" controls></video><p>Great content!</p>", $visitor);
        $this->assertStringContainsString("[VIDEO: tutorial.mp4]", $result);
        $this->assertStringContainsString("Watch our tutorial:", $result);
        $this->assertStringContainsString("Great content!", $result);
    }

    /** Visitor removes video elements entirely */
    public function test_visitor_video_skip(): void
    {
        $visitor = new class {
            public function visit_video($ctx, $src) {
                return 'skip';
            }
        };
        $result = HtmlToMarkdown::convert("<h2>Demo</h2><video src=\"demo.webm\"></video><p>See the demo above.</p>", $visitor);
        $this->assertStringContainsString("Demo", $result);
        $this->assertStringContainsString("See the demo above.", $result);
        $this->assertStringNotContainsString("demo.webm", $result);
    }
}
