// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:685dc57c80f4bb0fcec2dbda6f012fd68f9d3121b8181b11fd81c62d54274d9f
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/html_to_markdown.h");

    let go_include_dir = std::path::Path::new("../../packages/go/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/html_to_markdown.h", go_include_dir.join("html_to_markdown.h"))
        .expect("Unable to copy header to Go include directory");
}
