// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7a5db60bccf447a1926d02a9f997536fa745b504b6f337e28a27c58f8578477f
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/html_to_markdown.h");
    let go_include_dir = std::path::Path::new("../../packages/go/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/html_to_markdown.h", go_include_dir.join("html_to_markdown.h"))
        .expect("Unable to copy header to Go include directory");
}
