# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9135e12d3dfbd3200ba0cadbedaff214ea7fc5e98fc63761ce624408dd94db93
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
