# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38590a6c7413300d231f3fa0843bc743b96f2c659eec30b3ff49228569a0a1bf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
