# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4cf1fb9c1acc4d54ab3839d70df9d384afe6d74d0a91fe6b9e77f6728cbe08c4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
# Package loaded via library() from CRAN install.

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
