# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da3f733541dacb8d8396cd65dac17c95d8fe2ba5c26eeb11cd61c388a7cbd141
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: options

test_that("options_autolinks_false: Bare URL links rendered as regular markdown links when autolinks disabled", {
  result <- jsonlite::fromJSON(convert(html = "<p><a href='https://example.com'>https://example.com</a></p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("example.com", result$content, fixed = TRUE))
})

test_that("options_br_in_tables_false: BR elements in table cells are stripped when disabled", {
  result <- jsonlite::fromJSON(convert(html = "<table><tr><th>Col</th></tr><tr><td>A<br>B</td></tr></table>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Col", result$content, fixed = TRUE))
})

test_that("options_br_in_tables_true: BR elements in table cells render as line breaks", {
  result <- jsonlite::fromJSON(convert(html = "<table><tr><th>Header</th></tr><tr><td>Line 1<br>Line 2</td></tr></table>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Header", result$content, fixed = TRUE))
  expect_true(grepl("Line 1", result$content, fixed = TRUE))
  expect_true(grepl("Line 2", result$content, fixed = TRUE))
})

test_that("options_code_block_backticks: Backticks code block style uses triple backtick fences", {
  result <- jsonlite::fromJSON(convert(html = "<pre><code class=\"language-js\">console.log('hi');</code></pre>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("```", result$content, fixed = TRUE))
  expect_true(grepl("console.log('hi');", result$content, fixed = TRUE))
})

test_that("options_code_block_indented: Code blocks use 4-space indentation", {
  result <- jsonlite::fromJSON(convert(html = "<pre><code>print('hello')</code></pre>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("print('hello')", result$content, fixed = TRUE))
  expect_false(grepl("```", result$content, fixed = TRUE))
})

test_that("options_code_block_tildes: Code blocks use tilde fences", {
  result <- jsonlite::fromJSON(convert(html = "<pre><code>let x = 1;</code></pre>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("~~~", result$content, fixed = TRUE))
  expect_true(grepl("let x = 1;", result$content, fixed = TRUE))
})

test_that("options_code_block_tildes_style: Tildes code block style uses triple tilde fences", {
  result <- jsonlite::fromJSON(convert(html = "<pre><code>some code</code></pre>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("~~~", result$content, fixed = TRUE))
  expect_true(grepl("some code", result$content, fixed = TRUE))
})

test_that("options_code_language_python: Default code language annotation on blocks without lang attribute", {
  result <- jsonlite::fromJSON(convert(html = "<pre><code>def hello(): pass</code></pre>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("```python", result$content, fixed = TRUE))
  expect_true(grepl("def hello", result$content, fixed = TRUE))
})

test_that("options_convert_as_inline: Block elements treated as inline", {
  result <- jsonlite::fromJSON(convert(html = "<p>One</p><p>Two</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("One", result$content, fixed = TRUE))
  expect_true(grepl("Two", result$content, fixed = TRUE))
})

test_that("options_debug_true: Debug mode enabled does not crash and produces output", {
  result <- jsonlite::fromJSON(convert(html = "<p>Debug test</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Debug test", result$content, fixed = TRUE))
})

test_that("options_default_title_true: Links without title get empty title attribute when defaultTitle is true", {
  result <- jsonlite::fromJSON(convert(html = "<p><a href='https://example.com'>Link</a></p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Link", result$content, fixed = TRUE))
  expect_true(grepl("https://example.com", result$content, fixed = TRUE))
})

test_that("options_encoding_utf8: UTF-8 encoding hint for special characters", {
  result <- jsonlite::fromJSON(convert(html = "<p>Café naïve résumé</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
})

test_that("options_escape_ascii_enabled: ASCII Markdown characters are escaped when escapeAscii is true", {
  result <- jsonlite::fromJSON(convert(html = "<p>Text with # hash and [brackets] and * star</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Text", result$content, fixed = TRUE))
  expect_true(grepl("hash", result$content, fixed = TRUE))
  expect_true(grepl("brackets", result$content, fixed = TRUE))
  expect_true(grepl("star", result$content, fixed = TRUE))
})

test_that("options_escape_asterisks: escape_asterisks option escapes asterisks in plain text", {
  result <- jsonlite::fromJSON(convert(html = "<p>Use 2*3 = 6 in math.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("2", result$content, fixed = TRUE))
  expect_true(grepl("3", result$content, fixed = TRUE))
  expect_true(grepl("6", result$content, fixed = TRUE))
})

test_that("options_escape_misc: escape_misc option escapes miscellaneous markdown characters", {
  result <- jsonlite::fromJSON(convert(html = "<p>Use # and | and ~ in text.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("Use", result$content, fixed = TRUE))
  expect_true(grepl("and", result$content, fixed = TRUE))
  expect_true(grepl("in text.", result$content, fixed = TRUE))
})

test_that("options_escape_underscores: escape_underscores option escapes underscores in plain text", {
  result <- jsonlite::fromJSON(convert(html = "<p>The variable_name is defined.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("variable", result$content, fixed = TRUE))
  expect_true(grepl("name", result$content, fixed = TRUE))
  expect_true(grepl("defined.", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_attribute: Elements matching CSS attribute selector are excluded entirely", {
  result <- jsonlite::fromJSON(convert(html = "<body><div role=\"complementary\">Sidebar</div><p>Primary text</p></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Primary text", result$content, fixed = TRUE))
  expect_false(grepl("Sidebar", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_class: Elements matching CSS class selector are excluded entirely", {
  result <- jsonlite::fromJSON(convert(html = "<body><div class=\"cookie-banner\">Accept cookies</div><p>Main content</p></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Main content", result$content, fixed = TRUE))
  expect_false(grepl("cookies", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_empty_noop: Empty exclude_selectors list does not affect output", {
  result <- jsonlite::fromJSON(convert(html = "<p>Hello world</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Hello world", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_id: Elements matching CSS id selector are excluded entirely", {
  result <- jsonlite::fromJSON(convert(html = "<body><div id=\"ad-container\">Buy stuff</div><p>Article text</p></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Article text", result$content, fixed = TRUE))
  expect_false(grepl("Buy stuff", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_multiple: Multiple CSS selectors each exclude their matched elements", {
  result <- jsonlite::fromJSON(convert(html = "<body><nav class=\"nav\">Menu</nav><p>Content</p><footer>Footer</footer></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Content", result$content, fixed = TRUE))
  expect_false(grepl("Menu", result$content, fixed = TRUE))
  expect_false(grepl("Footer", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_nested_content_dropped: All descendants of excluded elements are dropped", {
  result <- jsonlite::fromJSON(convert(html = "<body><aside class=\"sidebar\"><h2>Related</h2><p>Sidebar text</p></aside><main><p>Main text</p></main></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Main text", result$content, fixed = TRUE))
  expect_false(grepl("Related", result$content, fixed = TRUE))
  expect_false(grepl("Sidebar text", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_plain_text_mode: Exclude selectors work in plain text output mode", {
  result <- jsonlite::fromJSON(convert(html = "<body><div class=\"nav\">Navigation</div><p>Article body</p></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Article body", result$content, fixed = TRUE))
  expect_false(grepl("Navigation", result$content, fixed = TRUE))
})

test_that("options_exclude_selectors_vs_strip_tags: exclude_selectors drops entire subtree unlike strip_tags which keeps children", {
  result <- jsonlite::fromJSON(convert(html = "<body><div class=\"wrapper\"><p>Inner paragraph</p></div><p>Outer text</p></body>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Outer text", result$content, fixed = TRUE))
  expect_false(grepl("Inner paragraph", result$content, fixed = TRUE))
})

test_that("options_extract_metadata_true: Extract metadata returns document metadata when enabled", {
  result <- jsonlite::fromJSON(convert(html = "<html><head><title>Test Page</title><meta name='description' content='A test page'></head><body><p>Content</p></body></html>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_equal(trimws(result$metadata$document$title), "Test Page")
  expect_equal(trimws(result$metadata$document$description), "A test page")
})

test_that("options_heading_style_atx: ATX heading style produces hash-prefixed headings", {
  result <- jsonlite::fromJSON(convert(html = "<h1>Title</h1><h2>Subtitle</h2>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("# Title", result$content, fixed = TRUE))
  expect_true(grepl("## Subtitle", result$content, fixed = TRUE))
})

test_that("options_heading_style_atx_closed: ATX closed heading style adds closing hashes", {
  result <- jsonlite::fromJSON(convert(html = "<h1>Closed Heading</h1>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("# Closed Heading #", result$content, fixed = TRUE))
})

test_that("options_heading_style_underlined: Underlined heading style produces setext-style headings for h1 and h2", {
  result <- jsonlite::fromJSON(convert(html = "<h1>Main Title</h1>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("Main Title", result$content, fixed = TRUE))
})

test_that("options_highlight_bold: Mark tag rendered as bold", {
  result <- jsonlite::fromJSON(convert(html = "<p>Text with <mark>highlighted</mark> text.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("**highlighted**", result$content, fixed = TRUE))
})

test_that("options_highlight_double_equal: Mark tag with double equal highlight style", {
  result <- jsonlite::fromJSON(convert(html = "<p>Text with <mark>highlighted</mark> here.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("==highlighted==", result$content, fixed = TRUE))
})

test_that("options_highlight_none: Mark tag with no highlight style strips the mark", {
  result <- jsonlite::fromJSON(convert(html = "<p>Text with <mark>plain</mark> content.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("plain", result$content, fixed = TRUE))
  expect_false(grepl("==", result$content, fixed = TRUE))
})

test_that("options_keep_inline_images_in_paragraph: Images inside specified tags stay inline", {
  result <- jsonlite::fromJSON(convert(html = "<p>Text <img src='icon.png' alt='icon'> more text</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Text", result$content, fixed = TRUE))
  expect_true(grepl("more text", result$content, fixed = TRUE))
})

test_that("options_link_style_reference: Links use reference-style formatting", {
  result <- jsonlite::fromJSON(convert(html = "<p><a href='https://example.com'>Example</a> and <a href='https://other.com'>Other</a></p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Example", result$content, fixed = TRUE))
  expect_true(grepl("Other", result$content, fixed = TRUE))
  expect_true(grepl("example.com", result$content, fixed = TRUE))
})

test_that("options_list_custom_bullets: Custom bullet character for unordered lists", {
  result <- jsonlite::fromJSON(convert(html = "<ul><li>Item A</li><li>Item B</li></ul>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("* Item A", result$content, fixed = TRUE))
  expect_true(grepl("* Item B", result$content, fixed = TRUE))
})

test_that("options_list_indent_tabs: Tab indentation type for nested list items", {
  result <- jsonlite::fromJSON(convert(html = "<ul><li>Parent<ul><li>Child</li></ul></li></ul>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("Parent", result$content, fixed = TRUE))
  expect_true(grepl("Child", result$content, fixed = TRUE))
})

test_that("options_list_indent_width_four: Nested lists indented with 4 spaces per level", {
  result <- jsonlite::fromJSON(convert(html = "<ul><li>Outer<ul><li>Inner</li></ul></li></ul>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Outer", result$content, fixed = TRUE))
  expect_true(grepl("Inner", result$content, fixed = TRUE))
})

test_that("options_max_depth_default_unlimited: Default max_depth (null) converts deeply nested content fully", {
  result <- jsonlite::fromJSON(convert(html = "<div><div><div><div><p>Deep content</p></div></div></div></div>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Deep content", result$content, fixed = TRUE))
})

test_that("options_max_depth_truncates: max_depth truncates content beyond the specified depth", {
  result <- jsonlite::fromJSON(convert(html = "<div><p>Shallow</p><div><div><div><p>Too deep</p></div></div></div></div>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Shallow", result$content, fixed = TRUE))
  expect_false(grepl("Too deep", result$content, fixed = TRUE))
})

test_that("options_max_depth_zero_empty: max_depth of 0 produces empty output", {
  result <- jsonlite::fromJSON(convert(html = "<p>Hello</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_equal(trimws(result$content), "")
})

test_that("options_newline_backslash: Hard line breaks rendered with backslash", {
  result <- jsonlite::fromJSON(convert(html = "<p>Line one<br>Line two</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Line one", result$content, fixed = TRUE))
  expect_true(grepl("Line two", result$content, fixed = TRUE))
})

test_that("options_newline_spaces: Hard line breaks rendered with trailing spaces", {
  result <- jsonlite::fromJSON(convert(html = "<p>First<br>Second</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("First", result$content, fixed = TRUE))
  expect_true(grepl("Second", result$content, fixed = TRUE))
})

test_that("options_output_format_djot: Djot output format produces djot-compatible markup", {
  result <- jsonlite::fromJSON(convert(html = "<p>Simple paragraph.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("Simple paragraph.", result$content, fixed = TRUE))
})

test_that("options_output_format_markdown: Default markdown output format produces standard markdown", {
  result <- jsonlite::fromJSON(convert(html = "<h1>Title</h1><p>Some text.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("# Title", result$content, fixed = TRUE))
  expect_true(grepl("Some text.", result$content, fixed = TRUE))
})

test_that("options_output_format_plain: Plain text output format strips markdown syntax", {
  result <- jsonlite::fromJSON(convert(html = "<h1>Title</h1><p>Some <strong>bold</strong> text.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Title", result$content, fixed = TRUE))
  expect_true(grepl("bold", result$content, fixed = TRUE))
  expect_true(grepl("text.", result$content, fixed = TRUE))
})

test_that("options_preprocessing_aggressive: Aggressive preset removes nav, footer, aside unconditionally", {
  result <- jsonlite::fromJSON(convert(html = "<nav>Menu</nav><article><h1>Title</h1><p>Content</p></article><aside>Sidebar</aside><footer>Footer</footer>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Title", result$content, fixed = TRUE))
  expect_true(grepl("Content", result$content, fixed = TRUE))
  expect_false(grepl("Menu", result$content, fixed = TRUE))
})

test_that("options_preprocessing_minimal: Minimal preset preserves nav, footer, aside", {
  result <- jsonlite::fromJSON(convert(html = "<nav>Navigation</nav><p>Content</p><footer>Footer</footer>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Navigation", result$content, fixed = TRUE))
  expect_true(grepl("Content", result$content, fixed = TRUE))
  expect_true(grepl("Footer", result$content, fixed = TRUE))
})

test_that("options_preprocessing_remove_forms: Forms are removed when remove_forms is true", {
  result <- jsonlite::fromJSON(convert(html = "<p>Before</p><form><input type='text'/><button>Submit</button></form><p>After</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Before", result$content, fixed = TRUE))
  expect_true(grepl("After", result$content, fixed = TRUE))
  expect_false(grepl("Submit", result$content, fixed = TRUE))
})

test_that("options_preserve_tags_iframe: Iframe tags preserved as raw HTML in output", {
  result <- jsonlite::fromJSON(convert(html = "<p>Before</p><iframe src='video.html' width='560'></iframe><p>After</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Before", result$content, fixed = TRUE))
  expect_true(grepl("After", result$content, fixed = TRUE))
  expect_true(grepl("<iframe", result$content, fixed = TRUE))
})

test_that("options_skip_images_true: Images are omitted from output when skipImages is true", {
  result <- jsonlite::fromJSON(convert(html = "<p>Before <img src='test.jpg' alt='photo'> After</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Before", result$content, fixed = TRUE))
  expect_true(grepl("After", result$content, fixed = TRUE))
  expect_false(grepl("photo", result$content, fixed = TRUE))
})

test_that("options_strip_newlines: Strip newlines produces single-line paragraphs", {
  result <- jsonlite::fromJSON(convert(html = "<p>First paragraph.</p><p>Second paragraph.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("First paragraph.", result$content, fixed = TRUE))
  expect_true(grepl("Second paragraph.", result$content, fixed = TRUE))
})

test_that("options_strip_tags_div_span: Div and span tags stripped but content preserved", {
  result <- jsonlite::fromJSON(convert(html = "<div class='wrapper'><p>Inside div</p></div><p>Outside <span class='hl'>span text</span></p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("Inside div", result$content, fixed = TRUE))
  expect_true(grepl("span text", result$content, fixed = TRUE))
})

test_that("options_strong_em_underscore: Strong and em tags use underscore symbol instead of asterisk", {
  result <- jsonlite::fromJSON(convert(html = "<p><strong>bold</strong> and <em>italic</em></p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("__bold__", result$content, fixed = TRUE))
  expect_true(grepl("_italic_", result$content, fixed = TRUE))
})

test_that("options_sub_symbol_tilde: Subscript rendered with tilde symbol", {
  result <- jsonlite::fromJSON(convert(html = "<p>H<sub>2</sub>O</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("~2~", result$content, fixed = TRUE))
})

test_that("options_sup_symbol_caret: Superscript rendered with caret symbol", {
  result <- jsonlite::fromJSON(convert(html = "<p>x<sup>2</sup></p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("^2^", result$content, fixed = TRUE))
})

test_that("options_whitespace_normalized: Normalized whitespace mode collapses multiple spaces", {
  result <- jsonlite::fromJSON(convert(html = "<p>Text   with    extra   spaces.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("Text", result$content, fixed = TRUE))
  expect_true(grepl("with", result$content, fixed = TRUE))
  expect_true(grepl("extra", result$content, fixed = TRUE))
  expect_true(grepl("spaces.", result$content, fixed = TRUE))
})

test_that("options_whitespace_strict: Strict whitespace mode preserves whitespace as-is", {
  result <- jsonlite::fromJSON(convert(html = "<p>Preserved   spacing.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("Preserved", result$content, fixed = TRUE))
  expect_true(grepl("spacing.", result$content, fixed = TRUE))
})

test_that("options_wrap_disabled: Wrap option disabled preserves long lines without breaking", {
  result <- jsonlite::fromJSON(convert(html = "<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(grepl("This is a long paragraph that should not be wrapped at all because wrapping is disabled.", result$content, fixed = TRUE))
})

test_that("options_wrap_enabled: Wrap option enabled with custom width wraps long lines", {
  result <- jsonlite::fromJSON(convert(html = "<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>", options = HtmlOutputConfig$default()), simplifyVector = FALSE)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(grepl("This is a long paragraph", result$content, fixed = TRUE))
})
