<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:602dff71187141788025192a9fca1e3288feb1abd857a11d46edaa3834499870
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace HtmlToMarkdown;

final class HtmlToMarkdown
{
    /**
     * Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images,
     * and warnings.
     *
     * @param string $html
     * @param ?ConversionOptions $options
     * @return ConversionResult
     * @throws \HtmlToMarkdown\HtmlToMarkdownException
     */
    public static function convert(
        string $html,
        ?ConversionOptions $options = null,
    ): ConversionResult {
        return \HtmlToMarkdown\HtmlToMarkdownApi::convert($html, $options); // delegate to native extension class
    }
}
