<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ca94d0174bf5be381dcaa9782c94a6abe4a61523eb258aef67daf0dbeaf2a58f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);

namespace HtmlToMarkdown;

/**
 * Type alias for a visitor handle (`Arc`-wrapped `Mutex` for thread-safe shared mutation).
 *
 * `Send + Sync` so that types embedding a `VisitorHandle` (e.g. `ConversionOptions`)
 * can be shared across threads — required by callers that stash configs inside
 * axum/rmcp/tokio Send-bound contexts.
 */
final class VisitorHandle {}
