// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.htmltomarkdown.HtmlToMarkdown;

/** E2e tests for category: edge-cases. */
class EdgeCasesTest {
    @Test
    void testEmptyHtml() throws Exception {
        // Empty HTML document
        var result = HtmlToMarkdown.convert("<html><head></head><body></body></html>");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testEncodingCjkCharacters() throws Exception {
        // CJK (Chinese, Japanese, Korean) characters are preserved
        var result = HtmlToMarkdown.convert("<p>中文内容</p><p>日本語テキスト</p><p>한국어 텍스트</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("中文内容"), "expected to contain: " + "中文内容");
        assertTrue(result.content().orElse("").contains("日本語テキスト"), "expected to contain: " + "日本語テキスト");
        assertTrue(result.content().orElse("").contains("한국어 텍스트"), "expected to contain: " + "한국어 텍스트");
    }

    @Test
    void testEncodingHtmlEntities() throws Exception {
        // Common HTML entities are decoded in output
        var result = HtmlToMarkdown.convert("<p>&amp; &lt; &gt; &nbsp; &quot; &apos;</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("&"), "expected to contain: " + "&");
        assertTrue(result.content().orElse("").contains("<"), "expected to contain: " + "<");
        assertTrue(result.content().orElse("").contains(">"), "expected to contain: " + ">");
    }

    @Test
    void testEncodingNamedEntities() throws Exception {
        // Named HTML entities like &mdash; and &hellip; are decoded
        var result = HtmlToMarkdown.convert("<p>Em dash&mdash;used for parenthetical remarks&mdash;is common. Ellipsis&hellip; indicates omission. Non-breaking&nbsp;space.</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("—"), "expected to contain: " + "—");
        assertTrue(result.content().orElse("").contains("…"), "expected to contain: " + "…");
    }

    @Test
    void testEncodingNumericEntities() throws Exception {
        // Numeric HTML entities (decimal and hex) are decoded
        var result = HtmlToMarkdown.convert("<p>Copyright: &#169; Trade: &#174; Euro: &#8364; Hex: &#x00A9;</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("©"), "expected to contain: " + "©");
        assertTrue(result.content().orElse("").contains("®"), "expected to contain: " + "®");
        assertTrue(result.content().orElse("").contains("€"), "expected to contain: " + "€");
    }

    @Test
    void testEncodingUnicodeEmoji() throws Exception {
        // Emoji and Unicode characters are preserved
        var result = HtmlToMarkdown.convert("<p>Hello 🌍 World 🚀</p><p>Stars: ⭐ ✨</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("🌍"), "expected to contain: " + "🌍");
        assertTrue(result.content().orElse("").contains("🚀"), "expected to contain: " + "🚀");
        assertTrue(result.content().orElse("").contains("⭐"), "expected to contain: " + "⭐");
    }

    @Test
    void testHtmlCommentsOnly() throws Exception {
        // Document containing only HTML comments produces empty output
        var result = HtmlToMarkdown.convert("<!-- This is a comment --><!-- Another comment -->");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testJustWhitespaceInput() throws Exception {
        // Input that is only whitespace characters (spaces, tabs, newlines) produces empty output
        var result = HtmlToMarkdown.convert("   ");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testMalformedDeeplyNestedElements() throws Exception {
        // Deeply nested elements (100 levels) are handled without stack overflow
        var result = HtmlToMarkdown.convert("<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><p>Deeply nested content</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("Deeply nested content"), "expected to contain: " + "Deeply nested content");
    }

    @Test
    void testMalformedMissingBlockClosingTags() throws Exception {
        // Missing closing tags on block elements are auto-closed by parser
        var result = HtmlToMarkdown.convert("<div><h1>Title<p>First paragraph<p>Second paragraph</div>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("Title"), "expected to contain: " + "Title");
        assertTrue(result.content().orElse("").contains("First paragraph"), "expected to contain: " + "First paragraph");
        assertTrue(result.content().orElse("").contains("Second paragraph"), "expected to contain: " + "Second paragraph");
    }

    @Test
    void testMalformedOverlappingTags() throws Exception {
        // Overlapping bold/italic tags are recovered by the HTML parser without panic
        var result = HtmlToMarkdown.convert("<p><b><i>bold and italic</b></i></p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("bold and italic"), "expected to contain: " + "bold and italic");
    }

    @Test
    void testMalformedUnclosedParagraph() throws Exception {
        // Unclosed <p> tag is recovered gracefully and content is preserved
        var result = HtmlToMarkdown.convert("<p>This paragraph is never closed");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("This paragraph is never closed"), "expected to contain: " + "This paragraph is never closed");
    }

    @Test
    void testScriptTagsOnly() throws Exception {
        // Document with only script tags produces empty output (scripts are stripped)
        var result = HtmlToMarkdown.convert("<html><head><script>alert('xss')</script></head><body><script>document.write('hello')</script></body></html>");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testStyleTagsOnly() throws Exception {
        // Document with only style tags produces empty output (styles are stripped)
        var result = HtmlToMarkdown.convert("<html><head><style>body { color: red; }</style></head><body><style>.foo { margin: 0; }</style></body></html>");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testWhitespaceOnly() throws Exception {
        // Whitespace-only content
        var result = HtmlToMarkdown.convert("<p>   </p>");
        assertEquals("", result.content().orElse("").trim());
    }

    @Test
    void testXssOnclickHandlerRemoved() throws Exception {
        // onclick and other on* event handlers are removed from elements
        var result = HtmlToMarkdown.convert("<p><a href=\"https://example.com\" onclick=\"alert('xss')\">Click me</a></p><button onmouseover=\"steal_data()\">Hover me</button>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("Click me"), "expected to contain: " + "Click me");
    }

    @Test
    void testXssScriptTagStripped() throws Exception {
        // Script tag content is stripped and does not appear in output
        var result = HtmlToMarkdown.convert("<p>Safe content.</p><script>alert('xss')</script><p>More safe content.</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("Safe content"), "expected to contain: " + "Safe content");
        assertTrue(result.content().orElse("").contains("More safe content"), "expected to contain: " + "More safe content");
    }

    @Test
    void testXssSvgNestedScriptStripped() throws Exception {
        // Script tags nested inside SVG are stripped
        var result = HtmlToMarkdown.convert("<p>Before SVG.</p><svg xmlns=\"http://www.w3.org/2000/svg\"><script>alert('svg-xss')</script><text>SVG text</text></svg><p>After SVG.</p>");
        assertFalse(result.content().orElse("").isEmpty(), "expected non-empty value");
        assertTrue(result.content().orElse("").contains("Before SVG"), "expected to contain: " + "Before SVG");
        assertTrue(result.content().orElse("").contains("After SVG"), "expected to contain: " + "After SVG");
    }

}
