// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d43aaa0ec89faee74665bd79a1b78fb8e45005aa586b370773becc87c7965c73
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.htmltomarkdown.HtmlToMarkdownRs;
import dev.kreuzberg.htmltomarkdown.ConversionOptions;
import java.util.Optional;

/** E2e tests for category: smoke. */
class SmokeTest {

    @Test
    void testSmokeEmptyString() throws Exception {
        // Empty string produces empty output
        var result = HtmlToMarkdownRs.convert("", ConversionOptions.builder().build());
assertEquals("", java.util.Optional.ofNullable(result.content()).orElse("").trim());
    }


    @Test
    void testSmokeSimpleHeading() throws Exception {
        // H1 heading converts to ATX markdown
        var result = HtmlToMarkdownRs.convert("<h1>Title</h1>", ConversionOptions.builder().build());
assertTrue(java.util.Optional.ofNullable(result.content()).orElse("").contains("# Title"), "expected to contain: " + "# Title");
    }


    @Test
    void testSmokeSimpleParagraph() throws Exception {
        // Simple paragraph converts correctly
        var result = HtmlToMarkdownRs.convert("<p>Hello World</p>", ConversionOptions.builder().build());
assertEquals("Hello World", java.util.Optional.ofNullable(result.content()).orElse("").trim());assertFalse(java.util.Optional.ofNullable(result.content()).isEmpty(), "expected non-empty value");
    }

}
