# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d62cf0c304e24a167a710e943106d8203118ef6cb83aa812f3133c24bfa7c7f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
