# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e73d29e5ad7b807c9227a3e1c6917dbb006fdcd742429737c103bdd95d1e30c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
