/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:ff61139834885ca5a1d211a781605cd59e6b65ab2790131754fc440c69668f4c
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
#include <html_to_markdown.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  const char *version = htm_version();

  if (!version || strlen(version) == 0) {
    fprintf(stderr, "FAIL: expected non-empty version string\n");
    return 1;
  }

  printf("PASS: htm_version returned: %s\n", version);
  return 0;
}
