// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b3135b542cb7b8e6a0c2596b1d16d6a738b344dc02314b2a41cf0825f2eea349
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using HtmlToMarkdown;
using static HtmlToMarkdown.HtmlToMarkdownRs;

namespace HtmlToMarkdown
{
    /// <summary>E2e tests for category: smoke.</summary>
    public class SmokeTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_SmokeEmptyString()
        {
            // Empty string produces empty output
            var result = HtmlToMarkdownRs.Convert("", null);
    Assert.Equal("", result.Content!.Trim());

        }

        [Fact]
        public void Test_SmokeSimpleHeading()
        {
            // H1 heading converts to ATX markdown
            var result = HtmlToMarkdownRs.Convert("<h1>Title</h1>", null);
    Assert.Contains("# title", result.Content.ToString().ToLower());

        }

        [Fact]
        public void Test_SmokeSimpleParagraph()
        {
            // Simple paragraph converts correctly
            var result = HtmlToMarkdownRs.Convert("<p>Hello World</p>", null);
    Assert.Equal("Hello World", result.Content!.Trim());
    Assert.False(string.IsNullOrEmpty(result.Content?.ToString()));

        }


    }
}
