# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83104226b7b462190f3357003209ec44bc4298c3b5bf09c613d94e1adeb82050
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'html_to_markdown/version'
require_relative 'html_to_markdown/native'

module HtmlToMarkdown
  # Re-export all types and functions from native extension
end
