# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:094484387808183514a801bab05d27e52c1d7d3d595e8913feed7cad1498eee3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.AnnotationKind do
  @moduledoc """
  The type of an inline text annotation.

  Uses internally tagged representation (`"annotation_type": "bold"`) for JSON serialization.
  """

  @typedoc "The type of an inline text annotation."
  @type t :: term()

  @typedoc "Bold / strong emphasis."
  @type bold :: :bold
  @typedoc "Italic / emphasis."
  @type italic :: :italic
  @typedoc "Underline."
  @type underline :: :underline
  @typedoc "Strikethrough / deleted text."
  @type strikethrough :: :strikethrough
  @typedoc "Inline code."
  @type code :: :code
  @typedoc "Subscript text."
  @type subscript :: :subscript
  @typedoc "Superscript text."
  @type superscript :: :superscript
  @typedoc "Highlighted / marked text."
  @type highlight :: :highlight
  @typedoc "A hyperlink sourced from an `<a href=\"...\">` element."
  @type link :: %{type: :link, url: String.t(), title: String.t()}
end
