# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8beb68eff11670b72d6c7c692015eddc4cef91ff579dcc166a0560a84f069266
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.CodeBlockStyle do
  @moduledoc """
  Code block fence style in Markdown output.

  Determines how code blocks (`<pre><code>`) are rendered in Markdown.
  """

  @typedoc "Code block fence style in Markdown output."
  @type t :: :indented | :backticks | :tildes

  @indented :indented
  @backticks :backticks
  @tildes :tildes

  @doc "Indented code blocks (4 spaces). `CommonMark` standard."
  @spec indented() :: t()
  def indented, do: @indented
  @doc "Fenced code blocks with backticks (```). Default (GFM). Supports language hints."
  @spec backticks() :: t()
  def backticks, do: @backticks
  @doc "Fenced code blocks with tildes (~~~). Supports language hints."
  @spec tildes() :: t()
  def tildes, do: @tildes
end
