# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38590a6c7413300d231f3fa0843bc743b96f2c659eec30b3ff49228569a0a1bf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: String.t() | nil,
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          annotations: [map()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
