# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f60e3f0588314e9a7c65cd870f26448fd0fa9edc0f82439c11a884b257ee9c93
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HeadingStyle do
  @moduledoc """
  Heading style options for Markdown output.

  Controls how headings (h1-h6) are rendered in the output Markdown.
  """

  @typedoc "Heading style options for Markdown output."
  @type t :: :underlined | :atx | :atx_closed

  @underlined :underlined
  @atx :atx
  @atx_closed :atx_closed

  @doc "Underlined style (=== for h1, --- for h2)."
  @spec underlined() :: t()
  def underlined, do: @underlined
  @doc "ATX style (# for h1, ## for h2, etc.). Default."
  @spec atx() :: t()
  def atx, do: @atx
  @doc "ATX closed style (# title #, with closing hashes)."
  @spec atx_closed() :: t()
  def atx_closed, do: @atx_closed
end
