# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7b5d1e6d960b4f829958e8e3e6005f1bc11926edceb31e3c0ac55ce647ac3e2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc """
  HTML preprocessing aggressiveness level.

  Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
  """

  @typedoc "HTML preprocessing aggressiveness level."
  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @doc "Minimal cleanup. Remove only essential noise (scripts, styles)."
  @spec minimal() :: t()
  def minimal, do: @minimal
  @doc "Standard cleanup. Default. Removes navigation, forms, and other auxiliary content."
  @spec standard() :: t()
  def standard, do: @standard
  @doc "Aggressive cleanup. Remove extensive non-content elements and structure."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
