# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:326db5ca43a336a58504a1bfdc18688d38c6bef7d9bcd7e34b87f6ce03811523
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc """
  Partial update for `PreprocessingOptions`.

  This struct uses `Option<T>` to represent optional fields that can be selectively updated.
  Only specified fields (Some values) will override existing options; None values leave the
  corresponding fields unchanged when applied via [`PreprocessingOptions::apply_update`].
  """

  @typedoc "Partial update for `PreprocessingOptions`."
  @type t :: %__MODULE__{
          enabled: boolean() | nil,
          preset: String.t() | nil | nil,
          remove_navigation: boolean() | nil,
          remove_forms: boolean() | nil
        }

  defstruct enabled: nil,
            preset: nil,
            remove_navigation: nil,
            remove_forms: nil
  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
        |> Map.from_struct()
        |> Jason.Encoder.encode(opts)
    end
  end

end
