# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7471d00a591a836cdb7076cfa76ddf0a8b03850c500d98669bcb0c59b507180a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc """
  A non-fatal diagnostic produced during HTML conversion.

  Warnings indicate that conversion completed but some content may have been handled
  differently than expected — for example, an image that could not be extracted, a truncated
  input, or malformed HTML that was repaired with best-effort parsing.

  Conversion always succeeds (returns `ConversionResult`) even when warnings are
  present. Callers should inspect `warnings` and decide how to
  handle them based on their tolerance for partial results:

  - **Logging pipelines**: emit each warning at `WARN` level and continue.
  - **Strict pipelines**: treat any warning as a hard error by checking
    `result.warnings.is_empty()` before using the output.

  See [`WarningKind`] for the full taxonomy of warning categories.
  """

  @typedoc "A non-fatal diagnostic produced during HTML conversion."
  @type t :: %__MODULE__{
          message: String.t() | nil,
          kind: String.t() | nil
        }

  defstruct message: nil,
            kind: :image_extraction_failed
end
