# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9d115071638507550e36d6a14df4a0d14b3a1af063c48fdb79381da5c9f158da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: map(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
