# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e73d29e5ad7b807c9227a3e1c6917dbb006fdcd742429737c103bdd95d1e30c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: map(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
