# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be17301dad2f955f30f940d89b8669da852aeab9d2a35529da823575443068c1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  defstruct grid: nil,
            markdown: ""
end
