# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fdbb9cafd32b125b64abd4acbff204711d3d5b50282abb93bbf1b9ff46c6f1c4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  @typedoc "A structured table grid with cell-level data including spans."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [map()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
