# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91ad34e85d841c35f1dcbed162b9270f3921880acf211991233a223ea1643e69
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TextDirection do
  @moduledoc "Text directionality of document content."

  @type t :: :left_to_right | :right_to_left | :auto

  @left_to_right :left_to_right
  @right_to_left :right_to_left
  @auto :auto

  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @spec auto() :: t()
  def auto, do: @auto
end
