# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0f6bafb76c53d2a76524bb39e19c2ae53ff99ba38753f37f796ea242ea079c6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.TextDirection do
  @moduledoc """
  Text directionality of document content.

  Corresponds to the HTML `dir` attribute and `bdi` element directionality.
  """

  @typedoc "Text directionality of document content."
  @type t :: :ltr | :rtl | :auto

  @left_to_right :ltr
  @right_to_left :rtl
  @auto :auto

  @doc "Left-to-right text flow (default for Latin scripts)"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text flow (Hebrew, Arabic, Urdu, etc.)"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic directionality detection"
  @spec auto() :: t()
  def auto, do: @auto
end
