# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:094484387808183514a801bab05d27e52c1d7d3d595e8913feed7cad1498eee3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.VisitorHandle do
  @moduledoc """
  Shareable, thread-safe handle to a user-provided HTML visitor implementation.

  Pass an instance wrapped in this handle to `ConversionOptions` to
  customise how the HTML document is traversed and converted to Markdown.
  The handle may be cloned and shared across threads without additional
  synchronisation on the caller's side.
  """

  defstruct [:ref]

  @typedoc "Shareable, thread-safe handle to a user-provided HTML visitor implementation."
  @type t :: %__MODULE__{ref: reference()}
end
