# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:587d200c95438abc2158e73f50ad7a072bde7ec6ef55df8510c6b9bc5343923c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.VisitorHandle do
  @moduledoc """
  Shareable, thread-safe handle to a user-provided HTML visitor implementation.

  Pass an instance wrapped in this handle to `ConversionOptions` to
  customise how the HTML document is traversed and converted to Markdown.
  The handle may be cloned and shared across threads without additional
  synchronisation on the caller's side.
  """

  defstruct [:ref]

  @typedoc "Shareable, thread-safe handle to a user-provided HTML visitor implementation."
  @type t :: %__MODULE__{ref: reference()}
end
