// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:39f2b6d069740246833ac7ec8b2af26783e8061178e2689c5782684718b433be
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
