// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:34fbdb4c0b2fb7f62ac67874a0b159460164b065dffdca16159d5338edb45346
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
