// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b110069778603d48070f19d6c637194f3da616a566eee8000e89902f685b025b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
