// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f8026f1bd5c957d54c05eab1d6eace9df28d99dae19dfe307c25ea4ef8344e6b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
