// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:13b7bce1b8084474dd907fe08752e4afc7c05b5c42cd4030ec54e77e76527ab1
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
