// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0432ece27ff03d50f6faee36be590e4bf33128917454468a89b6fae9471f3481
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A structured document tree representing the semantic content of an HTML document.
///
/// Uses a flat node array with index-based parent/child references for efficient traversal.
/// </summary>
public sealed record DocumentStructure
{
    /// <summary>
    /// All nodes in document reading order.
    /// </summary>
    [JsonPropertyName("nodes")]
    public List<DocumentNode> Nodes { get; init; } = [];

    /// <summary>
    /// The source format (always "html" for this crate).
    /// </summary>
    [JsonPropertyName("source_format")]
    public string? SourceFormat { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="DocumentStructure"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static DocumentStructure FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DocumentStructure>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse DocumentStructure from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse DocumentStructure from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
