// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:37ff8f311d7e716947cc449c77f02759ef733e25f8da74d8c586b1bbc5f6914c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Header element metadata with hierarchy tracking.
///
/// Captures heading elements (h1-h6) with their text content, identifiers,
/// and position in the document structure.
///
/// # Examples
///
/// ```
/// let header = HeaderMetadata {
///     level: 1,
///     text: "Main Title".to_string(),
///     id: Some("main-title".to_string()),
///     depth: 0,
///     html_offset: 145,
/// };
///
/// assert_eq!(header.level, 1);
/// assert!(header.is_valid());
/// ```
/// </summary>
public sealed class HeaderMetadata
{
    /// <summary>
    /// Header level: 1 (h1) through 6 (h6)
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; set; } = 0;

    /// <summary>
    /// Normalized text content of the header
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// HTML id attribute if present
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; } = null;

    /// <summary>
    /// Document tree depth at the header element
    /// </summary>
    [JsonPropertyName("depth")]
    public ulong Depth { get; set; } = 0;

    /// <summary>
    /// Byte offset in original HTML document
    /// </summary>
    [JsonPropertyName("html_offset")]
    public ulong HtmlOffset { get; set; } = 0;

}
