// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:34f0f6db5776cc4b2c5a1c5704bf1c422c3e70f951ff3c86c99a6493dcb4755b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Highlight rendering style for `<mark>` elements.
///
/// Controls how highlighted text is rendered in Markdown output.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum HighlightStyle
{    /// <summary>
    /// Double equals syntax (==text==). Default. Pandoc-compatible.
    /// </summary>
    [JsonPropertyName("doubleequal")]
    DoubleEqual,    /// <summary>
    /// Preserve as HTML (==text==). Original HTML tag.
    /// </summary>
    [JsonPropertyName("html")]
    Html,    /// <summary>
    /// Render as bold (**text**). Uses strong emphasis.
    /// </summary>
    [JsonPropertyName("bold")]
    Bold,    /// <summary>
    /// Strip formatting, render as plain text. No markup.
    /// </summary>
    [JsonPropertyName("none")]
    None,}
