// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:29cabe43e605a532788bdc7560430df026532172651e57215dc753f67d8f19f8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

public static class HtmlToMarkdownRs
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault
    };

    /// <summary>
    /// Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images,
    /// and warnings.
    ///
    /// # Arguments
    ///
    /// * `html` — the HTML string to convert.
    /// * `options` — optional conversion options. Defaults to [`ConversionOptions::default`].
    ///   When the `visitor` feature is enabled, a custom [`crate::visitor::HtmlVisitor`] can be
    ///   attached via the `visitor` field on `ConversionOptions`.
    ///
    /// # Example
    ///
    /// ```
    /// use html_to_markdown_rs::convert;
    ///
    /// let html = "&lt;h1&gt;Hello World&lt;/h1&gt;";
    /// let result = convert(html, None).unwrap();
    /// assert!(result.content.as_deref().unwrap_or("").contains("Hello World"));
    /// ```
    ///
    /// # Errors
    ///
    /// Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
    /// </summary>
    /// <param name="html"></param>
    /// <param name="options">Optional.</param>
    public static ConversionResult Convert(string html, ConversionOptions? options)
    {
        ArgumentNullException.ThrowIfNull(html);
        var optionsJson = options != null ? JsonSerializer.Serialize(options, JsonOptions) : "null";
        var optionsHandle = NativeMethods.ConversionOptionsFromJson(optionsJson);
        var nativeResult = NativeMethods.Convert(
            html,
            optionsHandle
        );
        if (nativeResult == IntPtr.Zero)
        {
            throw GetLastError();
        }
        var jsonPtr = NativeMethods.ConversionResultToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ConversionResultFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ConversionResult>(json ?? "null", JsonOptions)!;
        NativeMethods.ConversionOptionsFree(optionsHandle);
        return returnValue;
    }

    /// <summary>
    /// Validate that the header level is within valid range (1-6).
    ///
    /// # Returns
    ///
    /// `true` if level is 1-6, `false` otherwise.
    ///
    /// # Examples
    ///
    /// ```
    /// # use html_to_markdown_rs::metadata::HeaderMetadata;
    /// let valid = HeaderMetadata {
    ///     level: 3,
    ///     text: "Title".to_string(),
    ///     id: None,
    ///     depth: 2,
    ///     html_offset: 100,
    /// };
    /// assert!(valid.is_valid());
    ///
    /// let invalid = HeaderMetadata {
    ///     level: 7,  // Invalid
    ///     text: "Title".to_string(),
    ///     id: None,
    ///     depth: 2,
    ///     html_offset: 100,
    /// };
    /// assert!(!invalid.is_valid());
    /// ```
    /// </summary>
    public static bool HeaderMetadataIsValid(IntPtr handle)
    {
        var nativeResult = NativeMethods.HeaderMetadataIsValid(
            handle
        );
        var returnValue = nativeResult != 0;
        return returnValue;
    }

    /// <summary>
    /// Classify a link based on href value.
    ///
    /// # Arguments
    ///
    /// * `href` - The href attribute value
    ///
    /// # Returns
    ///
    /// Appropriate [`LinkType`] based on protocol and content.
    ///
    /// # Examples
    ///
    /// ```
    /// # use html_to_markdown_rs::metadata::{LinkMetadata, LinkType};
    /// assert_eq!(LinkMetadata::classify_link("#section"), LinkType::Anchor);
    /// assert_eq!(LinkMetadata::classify_link("mailto:test@example.com"), LinkType::Email);
    /// assert_eq!(LinkMetadata::classify_link("tel:+1234567890"), LinkType::Phone);
    /// assert_eq!(LinkMetadata::classify_link("https://example.com"), LinkType::External);
    /// ```
    /// </summary>
    /// <param name="href"></param>
    public static LinkType LinkMetadataClassifyLink(string href)
    {
        ArgumentNullException.ThrowIfNull(href);
        var nativeResult = NativeMethods.LinkMetadataClassifyLink(
            href
        );
        var json = Marshal.PtrToStringUTF8(nativeResult);
        NativeMethods.FreeString(nativeResult);
        var returnValue = JsonSerializer.Deserialize<LinkType>(json ?? "null", JsonOptions)!;
        return returnValue;
    }

    public static ConversionOptions ConversionOptionsDefault()
    {
        var nativeResult = NativeMethods.ConversionOptionsDefault();
        var jsonPtr = NativeMethods.ConversionOptionsToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ConversionOptionsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ConversionOptions>(json ?? "null", JsonOptions)!;
        return returnValue;
    }

    /// <summary>
    /// Create a new builder with default values.
    /// </summary>
    public static ConversionOptionsBuilder ConversionOptionsBuilder()
    {
        var nativeResult = NativeMethods.ConversionOptionsBuilder();
        var returnValue = new ConversionOptionsBuilder(nativeResult);
        return returnValue;
    }

    /// <summary>
    /// Create from a partial update, applying to defaults.
    /// </summary>
    /// <param name="update"></param>
    public static ConversionOptions ConversionOptionsFromUpdate(ConversionOptionsUpdate update)
    {
        ArgumentNullException.ThrowIfNull(update);
        var updateJson = JsonSerializer.Serialize(update, JsonOptions);
        var updateHandle = NativeMethods.ConversionOptionsUpdateFromJson(updateJson);
        var nativeResult = NativeMethods.ConversionOptionsFromUpdate(
            updateHandle
        );
        var jsonPtr = NativeMethods.ConversionOptionsToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ConversionOptionsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ConversionOptions>(json ?? "null", JsonOptions)!;
        NativeMethods.ConversionOptionsUpdateFree(updateHandle);
        return returnValue;
    }

    public static ConversionOptions ConversionOptionsFrom(ConversionOptionsUpdate update)
    {
        ArgumentNullException.ThrowIfNull(update);
        var updateJson = JsonSerializer.Serialize(update, JsonOptions);
        var updateHandle = NativeMethods.ConversionOptionsUpdateFromJson(updateJson);
        var nativeResult = NativeMethods.ConversionOptionsFrom(
            updateHandle
        );
        var jsonPtr = NativeMethods.ConversionOptionsToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ConversionOptionsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ConversionOptions>(json ?? "null", JsonOptions)!;
        NativeMethods.ConversionOptionsUpdateFree(updateHandle);
        return returnValue;
    }

    public static PreprocessingOptions PreprocessingOptionsDefault()
    {
        var nativeResult = NativeMethods.PreprocessingOptionsDefault();
        var jsonPtr = NativeMethods.PreprocessingOptionsToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.PreprocessingOptionsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<PreprocessingOptions>(json ?? "null", JsonOptions)!;
        return returnValue;
    }

    /// <summary>
    /// Create new preprocessing options from a partial update.
    ///
    /// Creates a new `PreprocessingOptions` struct with defaults, then applies the update.
    /// Fields not specified in the update keep their default values.
    ///
    /// # Arguments
    ///
    /// * `update` - Partial preprocessing options update
    ///
    /// # Returns
    ///
    /// New `PreprocessingOptions` with specified updates applied to defaults
    /// </summary>
    /// <param name="update"></param>
    public static PreprocessingOptions PreprocessingOptionsFromUpdate(PreprocessingOptionsUpdate update)
    {
        ArgumentNullException.ThrowIfNull(update);
        var updateJson = JsonSerializer.Serialize(update, JsonOptions);
        var updateHandle = NativeMethods.PreprocessingOptionsUpdateFromJson(updateJson);
        var nativeResult = NativeMethods.PreprocessingOptionsFromUpdate(
            updateHandle
        );
        var jsonPtr = NativeMethods.PreprocessingOptionsToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.PreprocessingOptionsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<PreprocessingOptions>(json ?? "null", JsonOptions)!;
        NativeMethods.PreprocessingOptionsUpdateFree(updateHandle);
        return returnValue;
    }

    public static PreprocessingOptions PreprocessingOptionsFrom(PreprocessingOptionsUpdate update)
    {
        ArgumentNullException.ThrowIfNull(update);
        var updateJson = JsonSerializer.Serialize(update, JsonOptions);
        var updateHandle = NativeMethods.PreprocessingOptionsUpdateFromJson(updateJson);
        var nativeResult = NativeMethods.PreprocessingOptionsFrom(
            updateHandle
        );
        var jsonPtr = NativeMethods.PreprocessingOptionsToJson(nativeResult);
        var json = Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.PreprocessingOptionsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<PreprocessingOptions>(json ?? "null", JsonOptions)!;
        NativeMethods.PreprocessingOptionsUpdateFree(updateHandle);
        return returnValue;
    }

    /// <summary>
    /// Convert HTML to Markdown, invoking visitor callbacks during processing.
    /// </summary>
    public static ConversionResult? ConvertWithVisitor(string html, ConversionOptions? options, IHtmlVisitor visitor)
    {
        ArgumentNullException.ThrowIfNull(html);
        ArgumentNullException.ThrowIfNull(visitor);

        using var bridge = new HtmlVisitorBridge(visitor);

        var optionsHandle = IntPtr.Zero;
        var visitorHandle = IntPtr.Zero;
        try
        {
            if (options != null)
            {
                var optionsJson = JsonSerializer.Serialize(options, JsonOptions);
                optionsHandle = NativeMethods.ConversionOptionsFromJson(optionsJson);
            }

            visitorHandle = NativeMethods.VisitorCreate(bridge._vtable);
            if (visitorHandle == IntPtr.Zero)
            {
                throw GetLastError();
            }

            var resultPtr = NativeMethods.ConvertWithVisitor(html, optionsHandle, visitorHandle);
            if (resultPtr == IntPtr.Zero)
            {
                throw GetLastError();
            }
            var json = Marshal.PtrToStringUTF8(resultPtr);
            NativeMethods.FreeString(resultPtr);
            return JsonSerializer.Deserialize<ConversionResult>(json!, JsonOptions);
        }
        finally
        {
            if (visitorHandle != IntPtr.Zero) NativeMethods.VisitorFree(visitorHandle);
            if (optionsHandle != IntPtr.Zero) NativeMethods.ConversionOptionsFree(optionsHandle);
        }
    }
    private static Exception GetLastError()
    {
        var code = NativeMethods.LastErrorCode();
        var ctxPtr = NativeMethods.LastErrorContext();
        var message = Marshal.PtrToStringUTF8(ctxPtr) ?? "Unknown error";
        if (code == 1) return new InvalidInputException(message);
        if (code == 2) return new ConversionErrorException(message);
        return new HtmlToMarkdownRsException(code, message);
    }
}
