// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Image source classification for proper handling and processing.
///
/// Determines whether an image is embedded (data URI), inline SVG, external, or relative.
/// </summary>
public enum ImageType
{
    /// <summary>
    /// Data URI embedded image (base64 or other encoding)
    /// </summary>
    [JsonPropertyName("data_uri")]
    DataUri,
    /// <summary>
    /// Inline SVG element
    /// </summary>
    [JsonPropertyName("inline_svg")]
    InlineSvg,
    /// <summary>
    /// External image URL (http/https)
    /// </summary>
    [JsonPropertyName("external")]
    External,
    /// <summary>
    /// Relative image path
    /// </summary>
    [JsonPropertyName("relative")]
    Relative,
}
