// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ccd79060df29124749580ce26f53785b68919a624fd4538767543a124363ee88
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
