// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:61bf09f33eb2faa62974efc6fd1521f704c1d132337671f4bfa46aa22dd34031
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
