// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cb17f151d028a481a20959f465c73c1974164a0ea218e02fbc91b405992a148d
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
