// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b110069778603d48070f19d6c637194f3da616a566eee8000e89902f685b025b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
