// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:80f8b536a098546cb45aeac87bc445c109ad23165d878115ac137d9b6b1c947b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
