// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:85065beb18f8a96b5459afe7ed182ceaa0c84dc975f053e2dda86981bfe4238d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Output format for conversion.
///
/// Specifies the target markup language format for the conversion output.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OutputFormat
{    /// <summary>
    /// Standard Markdown (CommonMark compatible). Default.
    /// </summary>
    [JsonPropertyName("markdown")]
    Markdown,    /// <summary>
    /// Djot lightweight markup language.
    /// </summary>
    [JsonPropertyName("djot")]
    Djot,    /// <summary>
    /// Plain text output (no markup, visible text only).
    /// </summary>
    [JsonPropertyName("plain")]
    Plain,}
