// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c4123217bb42e6cbe7cc59851037f301994cdb660a4a2934d8b056b2b5fc5adf
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
