// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c9e86fbd37245e8d95f0fa47ea92f2e7acd8da76a28a99f9eacd64c126b5f3c2
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
