// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7471d00a591a836cdb7076cfa76ddf0a8b03850c500d98669bcb0c59b507180a
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
