// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:37778fd884e4b95687934e3897d9e3a6198aa0b9f139557fe4a327ceab41f7d8
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// HTML preprocessing aggressiveness level.
///
/// Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PreprocessingPreset
{    /// <summary>
    /// Minimal cleanup. Remove only essential noise (scripts, styles).
    /// </summary>
    [JsonPropertyName("minimal")]
    Minimal,    /// <summary>
    /// Standard cleanup. Default. Removes navigation, forms, and other auxiliary content.
    /// </summary>
    [JsonPropertyName("standard")]
    Standard,    /// <summary>
    /// Aggressive cleanup. Remove extensive non-content elements and structure.
    /// </summary>
    [JsonPropertyName("aggressive")]
    Aggressive,}
