// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8beb68eff11670b72d6c7c692015eddc4cef91ff579dcc166a0560a84f069266
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
