// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4dc99abf2bf36539437457be6b18ac3381ea7d2c2c95cfc377ab43c25238c712
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
