// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:916d4bc28e07ef28a825e0f6996d70e0391fb2f85136a4473449809107d57a63
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A top-level extracted table with both structured data and markdown representation.
/// </summary>
public sealed record TableData
{
    /// <summary>
    /// The structured table grid.
    /// </summary>
    [JsonPropertyName("grid")]
    public required TableGrid Grid { get; init; }

    /// <summary>
    /// The markdown rendering of this table.
    /// </summary>
    [JsonPropertyName("markdown")]
    public required string Markdown { get; init; }


    /// <summary>
    /// Parse a <see cref="TableData"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static TableData FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<TableData>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse TableData from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse TableData from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
