// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:094484387808183514a801bab05d27e52c1d7d3d595e8913feed7cad1498eee3
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Controls which conversion tier is used.
/// </summary>
[JsonConverter(typeof(TierStrategyJsonConverter))]
public enum TierStrategy
{
    /// <summary>
    /// Automatically pick the best tier for the input (default).
    ///
    /// Runs the classifier against the prescan report and uses Tier-1 when
    /// eligible; falls back to Tier-2 on bail or when the classifier routes
    /// to Tier-2.
    /// </summary>
    [JsonPropertyName("auto")]
    Auto,
    /// <summary>
    /// Always use the Tier-2 (`tl.parse` + walk) path, skipping Tier-1.
    /// </summary>
    [JsonPropertyName("tier2")]
    Tier2,
    /// <summary>
    /// Force the Tier-1 byte scanner; if it bails, fall back to Tier-2.
    /// Testkit-only; not stable API.
    /// </summary>
    [JsonPropertyName("tier1")]
    Tier1,
}


/// <summary>
/// Custom JSON converter for <see cref="TierStrategy"/> that respects explicit variant names.
/// </summary>
internal sealed class TierStrategyJsonConverter : JsonConverter<TierStrategy>
{
    public override TierStrategy Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "auto" => TierStrategy.Auto,
            "tier2" => TierStrategy.Tier2,
            "tier1" => TierStrategy.Tier1,
            _ => throw new JsonException($"Unknown TierStrategy value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, TierStrategy value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            TierStrategy.Auto => "auto",
            TierStrategy.Tier2 => "tier2",
            TierStrategy.Tier1 => "tier1",
            _ => throw new JsonException($"Unknown TierStrategy value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
