// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aca55190c0fe0dbb7e87aa20416641cc15f60376062096ac9a762644272ccc67
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace HtmlToMarkdown;

internal sealed class VisitorHandleSafeHandle : SafeHandle
{
    internal VisitorHandleSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.VisitorHandleFree(handle);
        return true;
    }
}

/// <summary>
/// Type alias for a visitor handle (Rc-wrapped `RefCell` for interior mutability).
///
/// This allows visitors to be passed around and shared while still being mutable.
/// </summary>
public sealed class VisitorHandle : IDisposable
{
    private readonly VisitorHandleSafeHandle _safeHandle;

    internal VisitorHandle(IntPtr handle)
    {
        _safeHandle = new VisitorHandleSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
