// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cff48328aa24f8a4f42fbb42c6b4f7c3cb9881655a7f854dd581e44d60e49b8e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Whitespace handling strategy during conversion.
///
/// Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum WhitespaceMode
{    /// <summary>
    /// Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
    /// </summary>
    [JsonPropertyName("normalized")]
    Normalized,    /// <summary>
    /// Preserve all whitespace exactly as it appears in the HTML.
    /// </summary>
    [JsonPropertyName("strict")]
    Strict,}
