# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4dc99abf2bf36539437457be6b18ac3381ea7d2c2c95cfc377ab43c25238c712
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Public API for conversion."""

import json
from typing import Any, TypeVar, cast, overload

import html_to_markdown._html_to_markdown as _rust

from ._html_to_markdown import ConversionResult, VisitorHandle
from .options import ConversionOptions, PreprocessingOptions

_E = TypeVar("_E")


def _pascal_to_snake(value: str) -> str:
    """Convert PascalCase/camelCase to snake_case (AtxClosed -> atx_closed)."""
    out_chars: list[str] = []
    for index, ch in enumerate(value):
        if (
            ch.isupper()
            and index > 0
            and (value[index - 1].islower() or (index + 1 < len(value) and value[index + 1].islower()))
        ):
            out_chars.append("_")
        out_chars.append(ch.lower())
    return "".join(out_chars)


def _coerce_enum(enum_cls: type[_E], value: object) -> _E:
    """Coerce a string/alias value into the matching pyclass enum instance."""
    if isinstance(value, enum_cls):
        return value
    if value is None:
        msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
        raise ValueError(msg)
    s = str(value).replace("-", "_").replace(" ", "_")
    snake = _pascal_to_snake(s)
    candidates = (
        s,
        s.upper(),
        s.lower(),
        snake,
        snake.upper(),
        "".join(part.capitalize() for part in s.split("_")),
        "".join(part.capitalize() for part in snake.split("_")),
    )
    for candidate in candidates:
        attr = getattr(enum_cls, candidate, None)
        if isinstance(attr, enum_cls):
            return attr
    msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
    raise ValueError(msg)


@overload
def _to_rust_preprocessing_options(value: None) -> None: ...


@overload
def _to_rust_preprocessing_options(
    value: PreprocessingOptions | dict[str, Any] | str,
) -> _rust.PreprocessingOptions: ...
def _to_rust_preprocessing_options(
    value: PreprocessingOptions | dict[str, Any] | str | None,
) -> _rust.PreprocessingOptions | None:
    """Convert Python PreprocessingOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "preset" in value and value["preset"] is not None:
            value["preset"] = _coerce_enum(_rust.PreprocessingPreset, value["preset"])
        value = PreprocessingOptions(**value)
    if value is None:
        return None
    value = cast("PreprocessingOptions", value)
    return _rust.PreprocessingOptions(
        enabled=value.enabled,
        preset=_coerce_enum(_rust.PreprocessingPreset, value.preset),
        remove_navigation=value.remove_navigation,
        remove_forms=value.remove_forms,
    )


def _coerce_dict_conversion_options(value: dict[str, Any]) -> ConversionOptions:
    """Coerce a dict into ConversionOptions, converting nested types in-place."""
    _struct_coercions = {
        "preprocessing": _to_rust_preprocessing_options,
    }
    for _k, _fn in _struct_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _fn(value[_k])
    _enum_coercions = {
        "heading_style": _rust.HeadingStyle,
        "list_indent_type": _rust.ListIndentType,
        "highlight_style": _rust.HighlightStyle,
        "whitespace_mode": _rust.WhitespaceMode,
        "newline_style": _rust.NewlineStyle,
        "code_block_style": _rust.CodeBlockStyle,
        "url_escape_style": _rust.UrlEscapeStyle,
        "link_style": _rust.LinkStyle,
        "output_format": _rust.OutputFormat,
        "tier_strategy": _rust.TierStrategy,
    }
    for _k, _cls in _enum_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _coerce_enum(_cls, value[_k])
    return ConversionOptions(**value)


@overload
def _to_rust_conversion_options(value: None, _visitor_override: None = None) -> None: ...


@overload
def _to_rust_conversion_options(value: None, _visitor_override: VisitorHandle) -> _rust.ConversionOptions: ...


@overload
def _to_rust_conversion_options(
    value: ConversionOptions | dict[str, Any] | str,
    _visitor_override: VisitorHandle | None = None,
) -> _rust.ConversionOptions: ...
def _to_rust_conversion_options(
    value: ConversionOptions | dict[str, Any] | str | None,
    _visitor_override: VisitorHandle | None = None,
) -> _rust.ConversionOptions | None:
    """Convert Python ConversionOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = _coerce_dict_conversion_options(value)
    if value is None:
        if _visitor_override is not None:
            return _rust.ConversionOptions(visitor=_visitor_override)
        return None
    value = cast("ConversionOptions", value)
    return _rust.ConversionOptions(
        heading_style=_coerce_enum(_rust.HeadingStyle, value.heading_style),
        list_indent_type=_coerce_enum(_rust.ListIndentType, value.list_indent_type),
        list_indent_width=value.list_indent_width,
        bullets=value.bullets,
        strong_em_symbol=value.strong_em_symbol,
        escape_asterisks=value.escape_asterisks,
        escape_underscores=value.escape_underscores,
        escape_misc=value.escape_misc,
        escape_ascii=value.escape_ascii,
        code_language=value.code_language,
        autolinks=value.autolinks,
        default_title=value.default_title,
        br_in_tables=value.br_in_tables,
        compact_tables=value.compact_tables,
        highlight_style=_coerce_enum(_rust.HighlightStyle, value.highlight_style),
        extract_metadata=value.extract_metadata,
        whitespace_mode=_coerce_enum(_rust.WhitespaceMode, value.whitespace_mode),
        strip_newlines=value.strip_newlines,
        wrap=value.wrap,
        wrap_width=value.wrap_width,
        convert_as_inline=value.convert_as_inline,
        sub_symbol=value.sub_symbol,
        sup_symbol=value.sup_symbol,
        newline_style=_coerce_enum(_rust.NewlineStyle, value.newline_style),
        code_block_style=_coerce_enum(_rust.CodeBlockStyle, value.code_block_style),
        keep_inline_images_in=value.keep_inline_images_in,
        preprocessing=_to_rust_preprocessing_options(value.preprocessing),
        encoding=value.encoding,
        debug=value.debug,
        strip_tags=value.strip_tags,
        preserve_tags=value.preserve_tags,
        skip_images=value.skip_images,
        url_escape_style=_coerce_enum(_rust.UrlEscapeStyle, value.url_escape_style),
        link_style=_coerce_enum(_rust.LinkStyle, value.link_style),
        output_format=_coerce_enum(_rust.OutputFormat, value.output_format),
        include_document_structure=value.include_document_structure,
        extract_images=value.extract_images,
        max_image_size=value.max_image_size,
        capture_svg=value.capture_svg,
        infer_dimensions=value.infer_dimensions,
        max_depth=value.max_depth,
        exclude_selectors=value.exclude_selectors,
        **(
            {"tier_strategy": _coerce_enum(_rust.TierStrategy, value.tier_strategy)}
            if value.tier_strategy is not None
            else {}
        ),
        visitor=_visitor_override if _visitor_override is not None else value.visitor,
    )


def convert(
    html: str,
    options: ConversionOptions | None = None,
    visitor: VisitorHandle | None = None,
) -> ConversionResult:
    """Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images."""
    _rust_options = _to_rust_conversion_options(options, _visitor_override=visitor)

    return _rust.convert(html=html, options=_rust_options, visitor=visitor)
