# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:430ef19cdc26a55b0159e1184f51c34147623cbcbb638e254629267528dd6c7f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy."""


class ConversionError(Exception):
    """Errors that can occur during HTML to Markdown conversion."""


class ParseError(ConversionError):
    """HTML parsing error."""


class SanitizationError(ConversionError):
    """HTML sanitization error."""


class ConfigError(ConversionError):
    """Invalid configuration."""


class IoError(ConversionError):
    """I/O error -- stores the error message string so the variant is FFI-safe."""


class PanicError(ConversionError):
    """Panic caught during conversion to prevent unwinding across FFI boundaries."""


class InvalidInputError(ConversionError):
    """Invalid input data."""


class OtherError(ConversionError):
    """Generic conversion error."""
