# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b134ede61d41a7c7213100f29b1f6758a7149a0f3502964d0a16d7eb2055c2af
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Configuration options for the conversion API."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING

from ._html_to_markdown import (
    CodeBlockStyle,  # noqa: TC001
    HeadingStyle,  # noqa: TC001
    HighlightStyle,  # noqa: TC001
    LinkStyle,  # noqa: TC001
    ListIndentType,  # noqa: TC001
    NewlineStyle,  # noqa: TC001
    OutputFormat,  # noqa: TC001
    PreprocessingPreset,  # noqa: TC001
    TextDirection,  # noqa: TC001
    WhitespaceMode,  # noqa: TC001
)

if TYPE_CHECKING:
    from ._html_to_markdown import (
        GridCell,  # noqa: F401
        HeaderMetadata,  # noqa: F401
        ImageMetadata,  # noqa: F401
        LinkMetadata,  # noqa: F401
        StructuredData,  # noqa: F401
        VisitorHandle,  # noqa: F401
    )


class LinkType(str, Enum):
    """Link classification based on href value and document context."""

    anchor = "anchor"

    internal = "internal"

    external = "external"

    email = "email"

    phone = "phone"

    other = "other"


class ImageType(str, Enum):
    """Image source classification for proper handling and processing."""

    data_uri = "data_uri"

    inline_svg = "inline_svg"

    external = "external"

    relative = "relative"


class StructuredDataType(str, Enum):
    """Structured data format type."""

    json_ld = "json_ld"

    microdata = "microdata"

    rd_fa = "rdfa"


class WarningKind(str, Enum):
    """Categories of processing warnings."""

    image_extraction_failed = "image_extraction_failed"

    encoding_fallback = "encoding_fallback"

    truncated_input = "truncated_input"

    malformed_html = "malformed_html"

    sanitization_applied = "sanitization_applied"

    depth_limit_exceeded = "depth_limit_exceeded"


class NodeType(str, Enum):
    """Node type enumeration covering all HTML element types."""

    text = "text"

    element = "element"

    heading = "heading"

    paragraph = "paragraph"

    div = "div"

    blockquote = "blockquote"

    pre = "pre"

    hr = "hr"

    list = "list"

    list_item = "list_item"

    definition_list = "definition_list"

    definition_term = "definition_term"

    definition_description = "definition_description"

    table = "table"

    table_row = "table_row"

    table_cell = "table_cell"

    table_header = "table_header"

    table_body = "table_body"

    table_head = "table_head"

    table_foot = "table_foot"

    link = "link"

    image = "image"

    strong = "strong"

    em = "em"

    code = "code"

    strikethrough = "strikethrough"

    underline = "underline"

    subscript = "subscript"

    superscript = "superscript"

    mark = "mark"

    small = "small"

    br = "br"

    span = "span"

    article = "article"

    section = "section"

    nav = "nav"

    aside = "aside"

    header = "header"

    footer = "footer"

    main = "main"

    figure = "figure"

    figcaption = "figcaption"

    time = "time"

    details = "details"

    summary = "summary"

    form = "form"

    input = "input"

    select = "select"

    option = "option"

    button = "button"

    textarea = "textarea"

    label = "label"

    fieldset = "fieldset"

    legend = "legend"

    audio = "audio"

    video = "video"

    picture = "picture"

    source = "source"

    iframe = "iframe"

    svg = "svg"

    canvas = "canvas"

    ruby = "ruby"

    rt = "rt"

    rp = "rp"

    abbr = "abbr"

    kbd = "kbd"

    samp = "samp"

    var = "var"

    cite = "cite"

    q = "q"

    del = "del"

    ins = "ins"

    data = "data"

    meter = "meter"

    progress = "progress"

    output = "output"

    template = "template"

    slot = "slot"

    html = "html"

    head = "head"

    body = "body"

    title = "title"

    meta = "meta"

    link_tag = "link_tag"

    style = "style"

    script = "script"

    base = "base"

    custom = "custom"


@dataclass(frozen=True, slots=True)
class DocumentMetadata:
    """Document-level metadata extracted from `<head>` and top-level elements."""

    title: str | None = None

    """Document title from `<title>` tag"""

    description: str | None = None

    """Document description from `<meta name="description">` tag"""

    keywords: list[str] = field(default_factory=list)

    """Document keywords from `<meta name="keywords">` tag, split on commas"""

    author: str | None = None

    """Document author from `<meta name="author">` tag"""

    canonical_url: str | None = None

    """Canonical URL from `<link rel="canonical">` tag"""

    base_href: str | None = None

    """Base URL from `<base href="">` tag for resolving relative URLs"""

    language: str | None = None

    """Document language from `lang` attribute"""

    text_direction: TextDirection | str | None = None

    """Document text direction from `dir` attribute"""

    open_graph: dict[str, str] = field(default_factory=dict)

    """Open Graph metadata (og:* properties) for social media Keys like "title", "description", "image", "url", etc."""

    twitter_card: dict[str, str] = field(default_factory=dict)

    """Twitter Card metadata (twitter:* properties) Keys like "card", "site", "creator", "title", "description", "image", etc."""

    meta_tags: dict[str, str] = field(default_factory=dict)

    """Additional meta tags not covered by specific fields Keys are meta name/property attributes, values are content"""


@dataclass(frozen=True, slots=True)
class HtmlMetadata:
    """Comprehensive metadata extraction result from HTML document."""

    document: DocumentMetadata | None = None

    """Document-level metadata (title, description, canonical, etc.)"""

    headers: list[HeaderMetadata] = field(default_factory=list)

    """Extracted header elements with hierarchy"""

    links: list[LinkMetadata] = field(default_factory=list)

    """Extracted hyperlinks with type classification"""

    images: list[ImageMetadata] = field(default_factory=list)

    """Extracted images with source and dimensions"""

    structured_data: list[StructuredData] = field(default_factory=list)

    """Extracted structured data blocks"""


@dataclass(frozen=True, slots=True)
class ConversionOptions:
    """Main conversion options for HTML to Markdown conversion."""

    heading_style: HeadingStyle | str = "atx"

    """Heading style to use in Markdown output (ATX `#` or Setext underline)."""

    list_indent_type: ListIndentType | str = "spaces"

    """How to indent nested list items (spaces or tab)."""

    list_indent_width: int = 2

    """Number of spaces (or tabs) to use for each level of list indentation."""

    bullets: str = "-*+"

    """Bullet character(s) to use for unordered list items (e.g. `"-"`, `"*"`)."""

    strong_em_symbol: str = "*"

    """Character used for bold/italic emphasis markers (`*` or `_`)."""

    escape_asterisks: bool = False

    """Escape `*` characters in plain text to avoid unintended bold/italic."""

    escape_underscores: bool = False

    """Escape `_` characters in plain text to avoid unintended bold/italic."""

    escape_misc: bool = False

    """Escape miscellaneous Markdown metacharacters (`[]()#` etc.) in plain text."""

    escape_ascii: bool = False

    """Escape ASCII characters that have special meaning in certain Markdown dialects."""

    code_language: str = ""

    """Default language annotation for fenced code blocks that have no language hint."""

    autolinks: bool = True

    """Automatically convert bare URLs into Markdown autolinks."""

    default_title: bool = False

    """Emit a default title when no `<title>` tag is present."""

    br_in_tables: bool = False

    """Render `<br>` elements inside table cells as literal line breaks."""

    compact_tables: bool = False

    """Emit tables without column padding (compact GFM format)."""

    highlight_style: HighlightStyle | str = "double_equal"

    """Style used for `<mark>` / highlighted text (e.g. `==text==`)."""

    extract_metadata: bool = True

    """Populate `result.metadata` with `<head>` / `<meta>` extraction (title, description, Open Graph, Twitter Card, JSON-LD, …)."""

    whitespace_mode: WhitespaceMode | str = "normalized"

    """Controls how whitespace sequences are normalised in the converted output."""

    strip_newlines: bool = False

    """Strip all newlines from the output, producing a single-line result."""

    wrap: bool = False

    """Wrap long lines at [`wrap_width`](Self::wrap_width) characters."""

    wrap_width: int = 80

    """Maximum output line width in characters when [`wrap`](Self::wrap) is `true` (default `80`)."""

    convert_as_inline: bool = False

    """Treat the entire document as inline content (no block-level wrappers)."""

    sub_symbol: str = ""

    """Markdown notation for subscript text (e.g. `"~"`)."""

    sup_symbol: str = ""

    """Markdown notation for superscript text (e.g. `"^"`)."""

    newline_style: NewlineStyle | str = "spaces"

    """How to encode hard line breaks (`<br>`) in Markdown."""

    code_block_style: CodeBlockStyle | str = "backticks"

    """Style used for fenced code blocks (backticks or tilde)."""

    keep_inline_images_in: list[str] = field(default_factory=list)

    """HTML tag names whose `<img>` children are kept inline instead of block."""

    preprocessing: PreprocessingOptions | None = None

    """Options for the HTML pre-processing pass applied before conversion begins."""

    encoding: str = "utf-8"

    """Expected character encoding of the input HTML (default `"utf-8"`)."""

    debug: bool = False

    """Emit debug information during conversion."""

    strip_tags: list[str] = field(default_factory=list)

    """HTML tag names whose content is stripped from the output entirely."""

    preserve_tags: list[str] = field(default_factory=list)

    """HTML tag names that are preserved verbatim in the output."""

    skip_images: bool = False

    """Skip conversion of `<img>` elements (omit images from output)."""

    link_style: LinkStyle | str = "inline"

    """Link rendering style (inline or reference)."""

    output_format: OutputFormat | str = "markdown"

    """Target output format (Markdown, plain text, etc.)."""

    include_document_structure: bool = False

    """Include structured document tree in result."""

    extract_images: bool = False

    """Extract inline images from data URIs and SVGs."""

    max_image_size: int = 5242880

    """Maximum decoded image size in bytes (default 5MB)."""

    capture_svg: bool = False

    """Capture SVG elements as images."""

    infer_dimensions: bool = True

    """Infer image dimensions from data."""

    max_depth: int | None = None

    """Maximum DOM traversal depth. `None` means unlimited. When set, subtrees beyond this depth are silently truncated."""

    exclude_selectors: list[str] = field(default_factory=list)

    """CSS selectors for elements to exclude entirely (element + all content)."""

    visitor: VisitorHandle | None = None

    """Optional visitor for custom traversal logic."""


@dataclass(frozen=True, slots=True)
class PreprocessingOptions:
    """HTML preprocessing options for document cleanup before conversion."""

    enabled: bool = True

    """Enable HTML preprocessing globally"""

    preset: PreprocessingPreset | str = "standard"

    """Preprocessing preset level (Minimal, Standard, Aggressive)"""

    remove_navigation: bool = True

    """Remove navigation elements (nav, breadcrumbs, menus, sidebars)"""

    remove_forms: bool = True

    """Remove form elements (forms, inputs, buttons, etc.)"""


@dataclass(frozen=True, slots=True)
class TableGrid:
    """A structured table grid with cell-level data including spans."""

    rows: int = 0

    """Number of rows."""

    cols: int = 0

    """Number of columns."""

    cells: list[GridCell] = field(default_factory=list)

    """All cells in the table as a flat, sparse list."""
