// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9135e12d3dfbd3200ba0cadbedaff214ea7fc5e98fc63761ce624408dd94db93
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

import { describe, expect, it } from "vitest";
import {
	convert,
	WasmConversionOptions,
	WasmPreprocessingOptions,
	WasmVisitorHandle,
	WasmCodeBlockStyle,
	WasmHeadingStyle,
	WasmHighlightStyle,
	WasmLinkStyle,
	WasmListIndentType,
	WasmNewlineStyle,
	WasmOutputFormat,
	WasmPreprocessingPreset,
	WasmUrlEscapeStyle,
	WasmWhitespaceMode,
} from "@kreuzberg/html-to-markdown-wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [
		_alefE2eText(item),
		_alefE2eText(record.kind),
		_alefE2eText(record.name),
		_alefE2eText(record.source),
		_alefE2eText(record.alias),
		_alefE2eText(record.text),
		_alefE2eText(record.signature),
		itemsText,
	];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}

describe("options", () => {
	it("issue_396_backticks_blank_line_after_fence: Backticks code block trims trailing newline inside fence and adds blank line after closing fence (issue #396)", () => {
		const result = convert(
			"<p>Foo</p><pre><code>1\n2\n</code></pre><p>Bar</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.codeBlockStyle = WasmCodeBlockStyle.Backticks;
				return _u0;
			})(),
		);
		expect((result.content ?? "").trim()).toBe("Foo\n\n```\n1\n2\n```\n\nBar");
	}, 30000);
	it("options_autolinks_false: Bare URL links rendered as regular markdown links when autolinks disabled", () => {
		const result = convert(
			"<p><a href='https://example.com'>https://example.com</a></p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.autolinks = false;
				return _u0;
			})(),
		);
		expect(result.content).toContain("example.com");
	}, 30000);
	it("options_br_in_tables_false: BR elements in table cells are stripped when disabled", () => {
		const result = convert(
			"<table><tr><th>Col</th></tr><tr><td>A<br>B</td></tr></table>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.brInTables = false;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Col");
	}, 30000);
	it("options_br_in_tables_true: BR elements in table cells render as line breaks", () => {
		const result = convert(
			"<table><tr><th>Header</th></tr><tr><td>Line 1<br>Line 2</td></tr></table>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.brInTables = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Header");
		expect(result.content).toContain("Line 1");
		expect(result.content).toContain("Line 2");
	}, 30000);
	it("options_capture_svg_false: Disabling capture_svg still produces content; SVG is not extracted as an image", () => {
		const result = convert(
			'<p>Below SVG:</p><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.captureSvg = false;
				_u0.extractImages = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("Below SVG");
	}, 30000);
	it("options_capture_svg_true: Enabling capture_svg processes inline SVG elements when extract_images is on", () => {
		const result = convert(
			'<p>Below SVG:</p><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.captureSvg = true;
				_u0.extractImages = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("Below SVG");
	}, 30000);
	it("options_code_block_backticks: Backticks code block style uses triple backtick fences", () => {
		const result = convert(
			"<pre><code class=\"language-js\">console.log('hi');</code></pre>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.codeBlockStyle = WasmCodeBlockStyle.Backticks;
				return _u0;
			})(),
		);
		expect(result.content).toContain("```");
		expect(result.content).toContain("console.log('hi');");
	}, 30000);
	it("options_code_block_indented: Code blocks use 4-space indentation", () => {
		const result = convert(
			"<pre><code>print('hello')</code></pre>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.codeBlockStyle = WasmCodeBlockStyle.Indented;
				return _u0;
			})(),
		);
		expect(result.content).toContain("print('hello')");
		expect(result.content).not.toContain("```");
	}, 30000);
	it("options_code_block_tildes: Code blocks use tilde fences", () => {
		const result = convert(
			"<pre><code>let x = 1;</code></pre>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.codeBlockStyle = WasmCodeBlockStyle.Tildes;
				return _u0;
			})(),
		);
		expect(result.content).toContain("~~~");
		expect(result.content).toContain("let x = 1;");
	}, 30000);
	it("options_code_block_tildes_style: Tildes code block style uses triple tilde fences", () => {
		const result = convert(
			"<pre><code>some code</code></pre>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.codeBlockStyle = WasmCodeBlockStyle.Tildes;
				return _u0;
			})(),
		);
		expect(result.content).toContain("~~~");
		expect(result.content).toContain("some code");
	}, 30000);
	it("options_code_language_python: Default code language annotation on blocks without lang attribute", () => {
		const result = convert(
			"<pre><code>def hello(): pass</code></pre>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.codeLanguage = "python";
				return _u0;
			})(),
		);
		expect(result.content).toContain("```python");
		expect(result.content).toContain("def hello");
	}, 30000);
	it("options_compact_tables_false: compact_tables false (default) pads cells to column width", () => {
		const result = convert(
			"<table><thead><tr><th>Name</th><th>Score</th></tr></thead><tbody><tr><td>Alice</td><td>100</td></tr><tr><td>Bob</td><td>42</td></tr></tbody></table>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.compactTables = false;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("| ----- |");
		expect(result.content ?? "").toContain("| 42    |");
		expect(result.content).not.toContain("| --- |");
	}, 30000);
	it("options_compact_tables_true: compact_tables emits unpadded cells and minimal --- separators", () => {
		const result = convert(
			"<table><thead><tr><th>Name</th><th>Score</th></tr></thead><tbody><tr><td>Alice</td><td>100</td></tr><tr><td>Bob</td><td>42</td></tr></tbody></table>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.compactTables = true;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("| --- |");
		expect(result.content).not.toContain("| ----- |");
		expect(result.content ?? "").toContain("| 42 |");
		expect(result.content).not.toContain("| 42    |");
	}, 30000);
	it("options_convert_as_inline: Block elements treated as inline", () => {
		const result = convert(
			"<p>One</p><p>Two</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.convertAsInline = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("One");
		expect(result.content).toContain("Two");
	}, 30000);
	it("options_debug_true: Debug mode enabled does not crash and produces output", () => {
		const result = convert(
			"<p>Debug test</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.debug = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Debug test");
	}, 30000);
	it("options_default_title_true: Links without title get empty title attribute when defaultTitle is true", () => {
		const result = convert(
			"<p><a href='https://example.com'>Link</a></p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.defaultTitle = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Link");
		expect(result.content).toContain("https://example.com");
	}, 30000);
	it("options_encoding_utf8: UTF-8 encoding hint for special characters", () => {
		const result = convert(
			"<p>Café naïve résumé</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.encoding = "utf-8";
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
	}, 30000);
	it("options_escape_ascii_enabled: ASCII Markdown characters are escaped when escapeAscii is true", () => {
		const result = convert(
			"<p>Text with # hash and [brackets] and * star</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.escapeAscii = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Text");
		expect(result.content).toContain("hash");
		expect(result.content).toContain("brackets");
		expect(result.content).toContain("star");
	}, 30000);
	it("options_escape_asterisks: escape_asterisks option escapes asterisks in plain text", () => {
		const result = convert(
			"<p>Use 2*3 = 6 in math.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.escapeAsterisks = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("2");
		expect(result.content).toContain("3");
		expect(result.content).toContain("6");
	}, 30000);
	it("options_escape_misc: escape_misc option escapes miscellaneous markdown characters", () => {
		const result = convert(
			"<p>Use # and | and ~ in text.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.escapeMisc = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Use");
		expect(result.content).toContain("and");
		expect(result.content).toContain("in text.");
	}, 30000);
	it("options_escape_underscores: escape_underscores option escapes underscores in plain text", () => {
		const result = convert(
			"<p>The variable_name is defined.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.escapeUnderscores = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("variable");
		expect(result.content).toContain("name");
		expect(result.content).toContain("defined.");
	}, 30000);
	it("options_exclude_selectors_attribute: Elements matching CSS attribute selector are excluded entirely", () => {
		const result = convert(
			'<body><div role="complementary">Sidebar</div><p>Primary text</p></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = ["[role='complementary']"];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Primary text");
		expect(result.content).not.toContain("Sidebar");
	}, 30000);
	it("options_exclude_selectors_class: Elements matching CSS class selector are excluded entirely", () => {
		const result = convert(
			'<body><div class="cookie-banner">Accept cookies</div><p>Main content</p></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = [".cookie-banner"];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Main content");
		expect(result.content).not.toContain("cookies");
	}, 30000);
	it("options_exclude_selectors_empty_noop: Empty exclude_selectors list does not affect output", () => {
		const result = convert(
			"<p>Hello world</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = [];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Hello world");
	}, 30000);
	it("options_exclude_selectors_id: Elements matching CSS id selector are excluded entirely", () => {
		const result = convert(
			'<body><div id="ad-container">Buy stuff</div><p>Article text</p></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = ["#ad-container"];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Article text");
		expect(result.content).not.toContain("Buy stuff");
	}, 30000);
	it("options_exclude_selectors_multiple: Multiple CSS selectors each exclude their matched elements", () => {
		const result = convert(
			'<body><nav class="nav">Menu</nav><p>Content</p><footer>Footer</footer></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = [".nav", "footer"];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Content");
		expect(result.content).not.toContain("Menu");
		expect(result.content).not.toContain("Footer");
	}, 30000);
	it("options_exclude_selectors_nested_content_dropped: All descendants of excluded elements are dropped", () => {
		const result = convert(
			'<body><aside class="sidebar"><h2>Related</h2><p>Sidebar text</p></aside><main><p>Main text</p></main></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = [".sidebar"];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Main text");
		expect(result.content).not.toContain("Related");
		expect(result.content).not.toContain("Sidebar text");
	}, 30000);
	it("options_exclude_selectors_plain_text_mode: Exclude selectors work in plain text output mode", () => {
		const result = convert(
			'<body><div class="nav">Navigation</div><p>Article body</p></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = [".nav"];
				_u0.outputFormat = WasmOutputFormat.Plain;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Article body");
		expect(result.content).not.toContain("Navigation");
	}, 30000);
	it("options_exclude_selectors_vs_strip_tags: exclude_selectors drops entire subtree unlike strip_tags which keeps children", () => {
		const result = convert(
			'<body><div class="wrapper"><p>Inner paragraph</p></div><p>Outer text</p></body>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.excludeSelectors = [".wrapper"];
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Outer text");
		expect(result.content).not.toContain("Inner paragraph");
	}, 30000);
	it("options_extract_images_false: When extract_images is false, conversion still succeeds and inline images are not extracted", () => {
		const result = convert(
			'<p>Text with <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" alt="pixel"> image.</p>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractImages = false;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
	}, 30000);
	it("options_extract_images_true_data_uri: Enabling extract_images processes a data-URI image without crashing", () => {
		const result = convert(
			'<p>Before<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" alt="pixel">After</p>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractImages = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Before");
		expect(result.content).toContain("After");
	}, 30000);
	it("options_extract_metadata_true: Extract metadata returns document metadata when enabled", () => {
		const result = convert(
			"<html><head><title>Test Page</title><meta name='description' content='A test page'></head><body><p>Content</p></body></html>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractMetadata = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect((result.metadata.document.title ?? "").trim()).toBe("Test Page");
		expect((result.metadata.document.description ?? "").trim()).toBe("A test page");
	}, 30000);
	it("options_heading_style_atx: ATX heading style produces hash-prefixed headings", () => {
		const result = convert(
			"<h1>Title</h1><h2>Subtitle</h2>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.headingStyle = WasmHeadingStyle.Atx;
				return _u0;
			})(),
		);
		expect(result.content).toContain("# Title");
		expect(result.content).toContain("## Subtitle");
	}, 30000);
	it("options_heading_style_atx_closed: ATX closed heading style adds closing hashes", () => {
		const result = convert(
			"<h1>Closed Heading</h1>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.headingStyle = WasmHeadingStyle.AtxClosed;
				return _u0;
			})(),
		);
		expect(result.content).toContain("# Closed Heading #");
	}, 30000);
	it("options_heading_style_underlined: Underlined heading style produces setext-style headings for h1 and h2", () => {
		const result = convert(
			"<h1>Main Title</h1>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.headingStyle = WasmHeadingStyle.Underlined;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Main Title");
	}, 30000);
	it("options_highlight_bold: Mark tag rendered as bold", () => {
		const result = convert(
			"<p>Text with <mark>highlighted</mark> text.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.highlightStyle = WasmHighlightStyle.Bold;
				return _u0;
			})(),
		);
		expect(result.content).toContain("**highlighted**");
	}, 30000);
	it("options_highlight_double_equal: Mark tag with double equal highlight style", () => {
		const result = convert(
			"<p>Text with <mark>highlighted</mark> here.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.highlightStyle = WasmHighlightStyle.DoubleEqual;
				return _u0;
			})(),
		);
		expect(result.content).toContain("==highlighted==");
	}, 30000);
	it("options_highlight_none: Mark tag with no highlight style strips the mark", () => {
		const result = convert(
			"<p>Text with <mark>plain</mark> content.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.highlightStyle = WasmHighlightStyle.None;
				return _u0;
			})(),
		);
		expect(result.content).toContain("plain");
		expect(result.content).not.toContain("==");
	}, 30000);
	it("options_include_document_structure_false: Disabling include_document_structure still produces content without the document tree overhead", () => {
		const result = convert(
			"<article><h1>Heading</h1><p>Paragraph body.</p></article>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.includeDocumentStructure = false;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("Heading");
	}, 30000);
	it("options_include_document_structure_true: Setting include_document_structure populates the structured document tree on the result", () => {
		const result = convert(
			"<article><h1>Heading</h1><p>Paragraph body.</p></article>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.includeDocumentStructure = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("Heading");
	}, 30000);
	it("options_infer_dimensions_false: Disabling infer_dimensions skips the decode step and still produces content", () => {
		const result = convert(
			'<p>No dims: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" alt="pixel"></p>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractImages = true;
				_u0.inferDimensions = false;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("No dims");
	}, 30000);
	it("options_infer_dimensions_true: Enabling infer_dimensions decodes image bytes to populate dimension metadata when extract_images is on", () => {
		const result = convert(
			'<p>With dims: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" alt="pixel"></p>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractImages = true;
				_u0.inferDimensions = true;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("With dims");
	}, 30000);
	it("options_keep_inline_images_in_paragraph: Images inside specified tags stay inline", () => {
		const result = convert(
			"<p>Text <img src='icon.png' alt='icon'> more text</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.keepInlineImagesIn = ["p"];
				return _u0;
			})(),
		);
		expect(result.content).toContain("Text");
		expect(result.content).toContain("more text");
	}, 30000);
	it("options_link_style_reference: Links use reference-style formatting", () => {
		const result = convert(
			"<p><a href='https://example.com'>Example</a> and <a href='https://other.com'>Other</a></p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.linkStyle = WasmLinkStyle.Reference;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Example");
		expect(result.content).toContain("Other");
		expect(result.content).toContain("example.com");
	}, 30000);
	it("options_list_custom_bullets: Custom bullet character for unordered lists", () => {
		const result = convert(
			"<ul><li>Item A</li><li>Item B</li></ul>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.bullets = "*";
				return _u0;
			})(),
		);
		expect(result.content).toContain("* Item A");
		expect(result.content).toContain("* Item B");
	}, 30000);
	it("options_list_indent_tabs: Tab indentation type for nested list items", () => {
		const result = convert(
			"<ul><li>Parent<ul><li>Child</li></ul></li></ul>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.listIndentType = WasmListIndentType.Tabs;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Parent");
		expect(result.content).toContain("Child");
	}, 30000);
	it("options_list_indent_width_four: Nested lists indented with 4 spaces per level", () => {
		const result = convert(
			"<ul><li>Outer<ul><li>Inner</li></ul></li></ul>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.listIndentWidth = 4;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Outer");
		expect(result.content).toContain("Inner");
	}, 30000);
	it("options_max_depth_default_unlimited: Default max_depth (null) converts deeply nested content fully", () => {
		const result = convert("<div><div><div><div><p>Deep content</p></div></div></div></div>", undefined);
		expect(result.content ?? "").toContain("Deep content");
	}, 30000);
	it("options_max_depth_truncates: max_depth truncates content beyond the specified depth", () => {
		const result = convert(
			"<div><p>Shallow</p><div><div><div><p>Too deep</p></div></div></div></div>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.maxDepth = 3;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("Shallow");
		expect(result.content).not.toContain("Too deep");
	}, 30000);
	it("options_max_depth_zero_empty: max_depth of 0 produces empty output", () => {
		const result = convert(
			"<p>Hello</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.maxDepth = 0;
				return _u0;
			})(),
		);
		expect((result.content ?? "").trim()).toBe("");
	}, 30000);
	it("options_max_image_size_generous_limit: A generous max_image_size accommodates a small data-URI image without warnings", () => {
		const result = convert(
			'<p>Image: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" alt="pixel"></p>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractImages = true;
				_u0.maxImageSize = 10485760n;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("Image");
	}, 30000);
	it("options_max_image_size_tiny_limit_safe: A tiny max_image_size does not crash conversion even when the image exceeds the limit", () => {
		const result = convert(
			'<p>Tiny limit: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" alt="pixel"></p>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.extractImages = true;
				_u0.maxImageSize = 10n;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content ?? "").toContain("Tiny limit");
	}, 30000);
	it("options_newline_backslash: Hard line breaks rendered with backslash", () => {
		const result = convert(
			"<p>Line one<br>Line two</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.newlineStyle = WasmNewlineStyle.Backslash;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Line one");
		expect(result.content).toContain("Line two");
	}, 30000);
	it("options_newline_spaces: Hard line breaks rendered with trailing spaces", () => {
		const result = convert(
			"<p>First<br>Second</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.newlineStyle = WasmNewlineStyle.Spaces;
				return _u0;
			})(),
		);
		expect(result.content).toContain("First");
		expect(result.content).toContain("Second");
	}, 30000);
	it("options_output_format_djot: Djot output format produces djot-compatible markup", () => {
		const result = convert(
			"<p>Simple paragraph.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.outputFormat = WasmOutputFormat.Djot;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Simple paragraph.");
	}, 30000);
	it("options_output_format_markdown: Default markdown output format produces standard markdown", () => {
		const result = convert(
			"<h1>Title</h1><p>Some text.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.headingStyle = WasmHeadingStyle.Atx;
				_u0.outputFormat = WasmOutputFormat.Markdown;
				return _u0;
			})(),
		);
		expect(result.content).toContain("# Title");
		expect(result.content).toContain("Some text.");
	}, 30000);
	it("options_output_format_plain: Plain text output format strips markdown syntax", () => {
		const result = convert(
			"<h1>Title</h1><p>Some <strong>bold</strong> text.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.outputFormat = WasmOutputFormat.Plain;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Title");
		expect(result.content).toContain("bold");
		expect(result.content).toContain("text.");
	}, 30000);
	it("options_preprocessing_aggressive: Aggressive preset removes nav, footer, aside unconditionally", () => {
		const result = convert(
			"<nav>Menu</nav><article><h1>Title</h1><p>Content</p></article><aside>Sidebar</aside><footer>Footer</footer>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.preprocessing = (() => {
					const _u1 = WasmPreprocessingOptions.default();
					_u1.preset = WasmPreprocessingPreset.Aggressive;
					return _u1;
				})();
				return _u0;
			})(),
		);
		expect(result.content).toContain("Title");
		expect(result.content).toContain("Content");
		expect(result.content).not.toContain("Menu");
	}, 30000);
	it("options_preprocessing_enabled_false_skips_cleanup: Disabling preprocessing entirely preserves elements the standard preset would remove", () => {
		const result = convert(
			"<nav>NavSection</nav><p>Paragraph</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.preprocessing = (() => {
					const _u1 = WasmPreprocessingOptions.default();
					_u1.enabled = false;
					return _u1;
				})();
				return _u0;
			})(),
		);
		expect(result.content).toContain("NavSection");
		expect(result.content).toContain("Paragraph");
	}, 30000);
	it("options_preprocessing_minimal: Minimal preset preserves nav, footer, aside", () => {
		const result = convert(
			"<nav>Navigation</nav><p>Content</p><footer>Footer</footer>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.preprocessing = (() => {
					const _u1 = WasmPreprocessingOptions.default();
					_u1.preset = WasmPreprocessingPreset.Minimal;
					return _u1;
				})();
				return _u0;
			})(),
		);
		expect(result.content).toContain("Navigation");
		expect(result.content).toContain("Content");
		expect(result.content).toContain("Footer");
	}, 30000);
	it("options_preprocessing_remove_forms: Forms are removed when remove_forms is true", () => {
		const result = convert(
			"<p>Before</p><form><input type='text'/><button>Submit</button></form><p>After</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.preprocessing = (() => {
					const _u1 = WasmPreprocessingOptions.default();
					_u1.removeForms = true;
					return _u1;
				})();
				return _u0;
			})(),
		);
		expect(result.content).toContain("Before");
		expect(result.content).toContain("After");
		expect(result.content).not.toContain("Submit");
	}, 30000);
	it("options_preprocessing_remove_navigation_false_keeps_nav: Setting remove_navigation to false preserves nav and aside elements", () => {
		const result = convert(
			"<nav>SiteMenu</nav><main><p>MainContent</p></main><aside>SidebarText</aside>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.preprocessing = (() => {
					const _u1 = WasmPreprocessingOptions.default();
					_u1.removeNavigation = false;
					return _u1;
				})();
				return _u0;
			})(),
		);
		expect(result.content).toContain("SiteMenu");
		expect(result.content).toContain("MainContent");
		expect(result.content).toContain("SidebarText");
	}, 30000);
	it("options_preserve_tags_iframe: Iframe tags preserved as raw HTML in output", () => {
		const result = convert(
			"<p>Before</p><iframe src='video.html' width='560'></iframe><p>After</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.preserveTags = ["iframe"];
				return _u0;
			})(),
		);
		expect(result.content).toContain("Before");
		expect(result.content).toContain("After");
		expect(result.content).toContain("<iframe");
	}, 30000);
	it("options_skip_images_true: Images are omitted from output when skipImages is true", () => {
		const result = convert(
			"<p>Before <img src='test.jpg' alt='photo'> After</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.skipImages = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("Before");
		expect(result.content).toContain("After");
		expect(result.content).not.toContain("photo");
	}, 30000);
	it("options_strip_newlines: Strip newlines produces single-line paragraphs", () => {
		const result = convert(
			"<p>First paragraph.</p><p>Second paragraph.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.stripNewlines = true;
				return _u0;
			})(),
		);
		expect(result.content).toContain("First paragraph.");
		expect(result.content).toContain("Second paragraph.");
	}, 30000);
	it("options_strip_tags_div_span: Div and span tags stripped but content preserved", () => {
		const result = convert(
			"<div class='wrapper'><p>Inside div</p></div><p>Outside <span class='hl'>span text</span></p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.stripTags = ["div", "span"];
				return _u0;
			})(),
		);
		expect(result.content).toContain("Inside div");
		expect(result.content).toContain("span text");
	}, 30000);
	it("options_strong_em_underscore: Strong and em tags use underscore symbol instead of asterisk", () => {
		const result = convert(
			"<p><strong>bold</strong> and <em>italic</em></p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.strongEmSymbol = "_";
				return _u0;
			})(),
		);
		expect(result.content).toContain("__bold__");
		expect(result.content).toContain("_italic_");
	}, 30000);
	it("options_sub_symbol_tilde: Subscript rendered with tilde symbol", () => {
		const result = convert(
			"<p>H<sub>2</sub>O</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.subSymbol = "~";
				return _u0;
			})(),
		);
		expect(result.content).toContain("~2~");
	}, 30000);
	it("options_sup_symbol_caret: Superscript rendered with caret symbol", () => {
		const result = convert(
			"<p>x<sup>2</sup></p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.supSymbol = "^";
				return _u0;
			})(),
		);
		expect(result.content).toContain("^2^");
	}, 30000);
	it("options_url_escape_style_angle_default: Default angle style wraps URLs containing spaces in angle brackets", () => {
		const result = convert(
			'<a href="/file (1).pdf">file</a>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.urlEscapeStyle = WasmUrlEscapeStyle.Angle;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("</file (1).pdf>");
	}, 30000);
	it("options_url_escape_style_percent_angle_brackets_in_url: Percent style encodes angle brackets in link URLs from issue 392", () => {
		const result = convert(
			'<a href="/file (1) <draft>.pdf">file</a>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.urlEscapeStyle = WasmUrlEscapeStyle.Percent;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("/file%20%281%29%20%3Cdraft%3E.pdf");
	}, 30000);
	it("options_url_escape_style_percent_image: Percent style encodes special characters in image src URLs", () => {
		const result = convert(
			'<img src="/img (1) <draft>.png" alt="alt">',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.urlEscapeStyle = WasmUrlEscapeStyle.Percent;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("/img%20%281%29%20%3Cdraft%3E.png");
	}, 30000);
	it("options_url_escape_style_percent_link: Percent style encodes spaces and parens in link URLs", () => {
		const result = convert(
			'<a href="/file (1).pdf">file</a>',
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.urlEscapeStyle = WasmUrlEscapeStyle.Percent;
				return _u0;
			})(),
		);
		expect(result.content ?? "").toContain("/file%20%281%29.pdf");
		expect(result.content).not.toContain("</");
	}, 30000);
	it("options_whitespace_normalized: Normalized whitespace mode collapses multiple spaces", () => {
		const result = convert(
			"<p>Text   with    extra   spaces.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.whitespaceMode = WasmWhitespaceMode.Normalized;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Text");
		expect(result.content).toContain("with");
		expect(result.content).toContain("extra");
		expect(result.content).toContain("spaces.");
	}, 30000);
	it("options_whitespace_strict: Strict whitespace mode preserves whitespace as-is", () => {
		const result = convert(
			"<p>Preserved   spacing.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.whitespaceMode = WasmWhitespaceMode.Strict;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("Preserved");
		expect(result.content).toContain("spacing.");
	}, 30000);
	it("options_wrap_disabled: Wrap option disabled preserves long lines without breaking", () => {
		const result = convert(
			"<p>This is a long paragraph that should not be wrapped at all because wrapping is disabled.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.wrap = false;
				return _u0;
			})(),
		);
		expect(result.content).toContain(
			"This is a long paragraph that should not be wrapped at all because wrapping is disabled.",
		);
	}, 30000);
	it("options_wrap_enabled: Wrap option enabled with custom width wraps long lines", () => {
		const result = convert(
			"<p>This is a long paragraph that should be wrapped at the specified column width when the wrap option is enabled.</p>",
			(() => {
				const _u0 = WasmConversionOptions.default();
				_u0.wrap = true;
				_u0.wrapWidth = 40;
				return _u0;
			})(),
		);
		{
			const _v = result.content;
			if (typeof _v === "string" || Array.isArray(_v)) {
				expect(_v.length).toBeGreaterThan(0);
			} else {
				expect(_v).toBeDefined();
				expect(_v).not.toBeNull();
			}
		}
		expect(result.content).toContain("This is a long paragraph");
	}, 30000);
});
