# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'structure' do
  it 'structure_code_block: Fenced code block produces Code node' do
    result = HtmlToMarkdown.convert('<p>Example code:</p><pre><code class="language-rust">fn main() { println!("Hello"); }</code></pre>', {include_document_structure: true})
    expect(result).not_to be_empty
  end

  it 'structure_deep_nesting_h1_h2_h3: H1 > H2 > H3 creates three levels of heading nesting' do
    result = HtmlToMarkdown.convert('<h1>Top Level</h1><p>Top intro.</p><h2>Mid Level</h2><p>Mid content.</p><h3>Deep Level</h3><p>Deep content.</p>', {include_document_structure: true})
    expect(result).not_to be_empty
  end

  it 'structure_h1_h2_nested_group: H1 followed by H2 creates a nested group under the H1' do
    result = HtmlToMarkdown.convert('<h1>Chapter One</h1><p>Chapter intro.</p><h2>Section One</h2><p>Section content.</p>', {include_document_structure: true})
    expect(result).not_to be_empty
  end

  it 'structure_heading_paragraph: Simple heading followed by paragraph produces Heading and Paragraph nodes' do
    result = HtmlToMarkdown.convert('<h1>Title</h1><p>A paragraph of text.</p>', {include_document_structure: true})
    expect(result).not_to be_empty
  end

  it 'structure_list: Unordered list produces List and ListItem nodes' do
    result = HtmlToMarkdown.convert('<p>Items:</p><ul><li>Alpha</li><li>Beta</li><li>Gamma</li></ul>', {include_document_structure: true})
    expect(result).not_to be_empty
  end

  it 'structure_multiple_headings: Multiple headings create multiple Heading nodes with correct levels' do
    result = HtmlToMarkdown.convert('<h1>Main Title</h1><h2>Section One</h2><p>Section one content.</p><h2>Section Two</h2><p>Section two content.</p>', {include_document_structure: true})
    expect(result).not_to be_empty
  end

  it 'structure_sibling_h1_groups: H1, H2, then another H1 creates two sibling top-level groups' do
    result = HtmlToMarkdown.convert('<h1>Chapter One</h1><h2>Section A</h2><p>Section A content.</p><h1>Chapter Two</h1><h2>Section B</h2><p>Section B content.</p>', {include_document_structure: true})
    expect(result).not_to be_empty
  end
end
