// Generated by alef. Do not edit by hand.
// alef:hash:61bf09f33eb2faa62974efc6fd1521f704c1d132337671f4bfa46aa22dd34031
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
 * A single key-value metadata entry from `<head>` meta tags.
 *
 * Binding-safe replacement for `(String, String)` tuples used in `NodeContent.MetadataBlock`. Tuple
 * pairs cannot be represented across language boundaries without lossy degradation.
 */
data class MetadataEntry(
    /** Metadata key (e.g. `"title"`, `"description"`, `"og:title"`). */
    val key: String,
    /** Metadata value. */
    val value: String,
)
