# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:602dff71187141788025192a9fca1e3288feb1abd857a11d46edaa3834499870
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
