# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4dc99abf2bf36539437457be6b18ac3381ea7d2c2c95cfc377ab43c25238c712
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
