// DO NOT EDIT - auto-generated by alef
// alef:hash:094484387808183514a801bab05d27e52c1d7d3d595e8913feed7cad1498eee3
package dev.kreuzberg.htmltomarkdown;

/**
 * Invalid configuration
 */
public class ConfigErrorException extends ConversionErrorException {
    /** Creates a new ConfigErrorException with the given message. */
    public ConfigErrorException(final String message) {
        super(message);
    }

    /** Creates a new ConfigErrorException with the given message and cause. */
    public ConfigErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
