// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b110069778603d48070f19d6c637194f3da616a566eee8000e89902f685b025b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends HtmlToMarkdownRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
