// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ce5f5230736d360310bd04d368d585875f1950f4d92ae06dced309deb89eda1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * The primary result of HTML conversion and extraction.
 *
 * Contains the converted text output, optional structured document tree,
 * metadata, extracted tables, images, and processing warnings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConversionResult.Builder.class)
public record ConversionResult(
    /**
     * Converted text output (markdown, djot, or plain text).
     *
     * {@code None} when {@code output_format} is set to {@code OutputFormat.None},
     * indicating extraction-only mode.
     */
    @Nullable String content,
    /**
     * Structured document tree with semantic elements.
     *
     * Populated when {@code ConversionOptions.include_document_structure} is {@code true}. {@code None}
     * otherwise (the default), which avoids the overhead of building the tree.
     *
     * When present, the tree mirrors the converted document: headings open
     * {@code Group} sections, paragraphs and list items carry
     * inline {@code TextAnnotation}s, and tables reference the same
     * {@code TableGrid} data exposed in Self.tables.
     *
     * Note: this field is independent of the {@code metadata} feature flag. Document structure
     * collection is always available at runtime; it is gated only by the runtime option, not
     * by a compile-time feature.
     */
    @Nullable DocumentStructure document,
    /**
     * Extracted HTML metadata (title, OG, links, images, structured data).
     */
    HtmlMetadata metadata,
    /**
     * Extracted tables with structured cell data and markdown representation.
     */
    List<TableData> tables,
    /**
     * Extracted inline images (data URIs and SVGs).
     *
     * Populated when {@code extract_images} is {@code true} in options.
     */
    List<String> images,
    /**
     * Non-fatal processing warnings.
     */
    List<ProcessingWarning> warnings
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("content")
        private Optional<String> content = Optional.empty();
        @JsonProperty("document")
        private Optional<DocumentStructure> document = Optional.empty();
        @JsonProperty("metadata")
        private HtmlMetadata metadata = null;
        @JsonProperty("tables")
        private List<TableData> tables = List.of();
        @JsonProperty("images")
        private List<String> images = List.of();
        @JsonProperty("warnings")
        private List<ProcessingWarning> warnings = List.of();

        /** Sets the content field. */
        @JsonProperty("content")
        public Builder withContent(final @Nullable String value) {
            this.content = Optional.ofNullable(value);
            return this;
        }

        /** Sets the document field. */
        @JsonProperty("document")
        public Builder withDocument(final @Nullable DocumentStructure value) {
            this.document = Optional.ofNullable(value);
            return this;
        }

        /** Sets the metadata field. */
        @JsonProperty("metadata")
        public Builder withMetadata(final HtmlMetadata value) {
            this.metadata = value;
            return this;
        }

        /** Sets the tables field. */
        @JsonProperty("tables")
        public Builder withTables(final List<TableData> value) {
            this.tables = value;
            return this;
        }

        /** Sets the images field. */
        @JsonProperty("images")
        public Builder withImages(final List<String> value) {
            this.images = value;
            return this;
        }

        /** Sets the warnings field. */
        @JsonProperty("warnings")
        public Builder withWarnings(final List<ProcessingWarning> value) {
            this.warnings = value;
            return this;
        }

        /** Builds the ConversionResult instance. */
        public ConversionResult build() {
            return new ConversionResult(
                content.orElse(null),
                document.orElse(null),
                metadata,
                tables,
                images,
                warnings
            );
        }
    }
    // CPD-ON
}
