// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:091b71b9d9a803828171af7a360d2693fa93e208296f4fb59adfed815b43df6a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Optional;

/**
 * Main conversion options for HTML to Markdown conversion.
 *
 * Use ConversionOptions::builder() to construct, or Default::default() for defaults.
 */
public class ConversionOptionsBuilder {

    private HeadingStyle headingStyle = null;
    private ListIndentType listIndentType = null;
    private long listIndentWidth = 0;
    private String bullets = "";
    private String strongEmSymbol = "";
    private boolean escapeAsterisks = false;
    private boolean escapeUnderscores = false;
    private boolean escapeMisc = false;
    private boolean escapeAscii = false;
    private String codeLanguage = "";
    private boolean autolinks = false;
    private boolean defaultTitle = false;
    private boolean brInTables = false;
    private HighlightStyle highlightStyle = null;
    private boolean extractMetadata = false;
    private WhitespaceMode whitespaceMode = null;
    private boolean stripNewlines = false;
    private boolean wrap = false;
    private long wrapWidth = 0;
    private boolean convertAsInline = false;
    private String subSymbol = "";
    private String supSymbol = "";
    private NewlineStyle newlineStyle = null;
    private CodeBlockStyle codeBlockStyle = null;
    private List<String> keepInlineImagesIn = List.of();
    private PreprocessingOptions preprocessing = null;
    private String encoding = "";
    private boolean debug = false;
    private List<String> stripTags = List.of();
    private List<String> preserveTags = List.of();
    private boolean skipImages = false;
    private LinkStyle linkStyle = null;
    private OutputFormat outputFormat = null;
    private boolean includeDocumentStructure = false;
    private boolean extractImages = false;
    private long maxImageSize = 0;
    private boolean captureSvg = false;
    private boolean inferDimensions = false;
    private Optional<Long> maxDepth = Optional.empty();
    private List<String> excludeSelectors = List.of();
    private Optional<VisitorHandle> visitor = Optional.empty();

    /** Sets the headingStyle field. */
    public ConversionOptionsBuilder withHeadingStyle(final HeadingStyle value) {
        this.headingStyle = value;
        return this;
    }

    /** Sets the listIndentType field. */
    public ConversionOptionsBuilder withListIndentType(final ListIndentType value) {
        this.listIndentType = value;
        return this;
    }

    /** Sets the listIndentWidth field. */
    public ConversionOptionsBuilder withListIndentWidth(final long value) {
        this.listIndentWidth = value;
        return this;
    }

    /** Sets the bullets field. */
    public ConversionOptionsBuilder withBullets(final String value) {
        this.bullets = value;
        return this;
    }

    /** Sets the strongEmSymbol field. */
    public ConversionOptionsBuilder withStrongEmSymbol(final String value) {
        this.strongEmSymbol = value;
        return this;
    }

    /** Sets the escapeAsterisks field. */
    public ConversionOptionsBuilder withEscapeAsterisks(final boolean value) {
        this.escapeAsterisks = value;
        return this;
    }

    /** Sets the escapeUnderscores field. */
    public ConversionOptionsBuilder withEscapeUnderscores(final boolean value) {
        this.escapeUnderscores = value;
        return this;
    }

    /** Sets the escapeMisc field. */
    public ConversionOptionsBuilder withEscapeMisc(final boolean value) {
        this.escapeMisc = value;
        return this;
    }

    /** Sets the escapeAscii field. */
    public ConversionOptionsBuilder withEscapeAscii(final boolean value) {
        this.escapeAscii = value;
        return this;
    }

    /** Sets the codeLanguage field. */
    public ConversionOptionsBuilder withCodeLanguage(final String value) {
        this.codeLanguage = value;
        return this;
    }

    /** Sets the autolinks field. */
    public ConversionOptionsBuilder withAutolinks(final boolean value) {
        this.autolinks = value;
        return this;
    }

    /** Sets the defaultTitle field. */
    public ConversionOptionsBuilder withDefaultTitle(final boolean value) {
        this.defaultTitle = value;
        return this;
    }

    /** Sets the brInTables field. */
    public ConversionOptionsBuilder withBrInTables(final boolean value) {
        this.brInTables = value;
        return this;
    }

    /** Sets the highlightStyle field. */
    public ConversionOptionsBuilder withHighlightStyle(final HighlightStyle value) {
        this.highlightStyle = value;
        return this;
    }

    /** Sets the extractMetadata field. */
    public ConversionOptionsBuilder withExtractMetadata(final boolean value) {
        this.extractMetadata = value;
        return this;
    }

    /** Sets the whitespaceMode field. */
    public ConversionOptionsBuilder withWhitespaceMode(final WhitespaceMode value) {
        this.whitespaceMode = value;
        return this;
    }

    /** Sets the stripNewlines field. */
    public ConversionOptionsBuilder withStripNewlines(final boolean value) {
        this.stripNewlines = value;
        return this;
    }

    /** Sets the wrap field. */
    public ConversionOptionsBuilder withWrap(final boolean value) {
        this.wrap = value;
        return this;
    }

    /** Sets the wrapWidth field. */
    public ConversionOptionsBuilder withWrapWidth(final long value) {
        this.wrapWidth = value;
        return this;
    }

    /** Sets the convertAsInline field. */
    public ConversionOptionsBuilder withConvertAsInline(final boolean value) {
        this.convertAsInline = value;
        return this;
    }

    /** Sets the subSymbol field. */
    public ConversionOptionsBuilder withSubSymbol(final String value) {
        this.subSymbol = value;
        return this;
    }

    /** Sets the supSymbol field. */
    public ConversionOptionsBuilder withSupSymbol(final String value) {
        this.supSymbol = value;
        return this;
    }

    /** Sets the newlineStyle field. */
    public ConversionOptionsBuilder withNewlineStyle(final NewlineStyle value) {
        this.newlineStyle = value;
        return this;
    }

    /** Sets the codeBlockStyle field. */
    public ConversionOptionsBuilder withCodeBlockStyle(final CodeBlockStyle value) {
        this.codeBlockStyle = value;
        return this;
    }

    /** Sets the keepInlineImagesIn field. */
    public ConversionOptionsBuilder withKeepInlineImagesIn(final List<String> value) {
        this.keepInlineImagesIn = value;
        return this;
    }

    /** Sets the preprocessing field. */
    public ConversionOptionsBuilder withPreprocessing(final PreprocessingOptions value) {
        this.preprocessing = value;
        return this;
    }

    /** Sets the encoding field. */
    public ConversionOptionsBuilder withEncoding(final String value) {
        this.encoding = value;
        return this;
    }

    /** Sets the debug field. */
    public ConversionOptionsBuilder withDebug(final boolean value) {
        this.debug = value;
        return this;
    }

    /** Sets the stripTags field. */
    public ConversionOptionsBuilder withStripTags(final List<String> value) {
        this.stripTags = value;
        return this;
    }

    /** Sets the preserveTags field. */
    public ConversionOptionsBuilder withPreserveTags(final List<String> value) {
        this.preserveTags = value;
        return this;
    }

    /** Sets the skipImages field. */
    public ConversionOptionsBuilder withSkipImages(final boolean value) {
        this.skipImages = value;
        return this;
    }

    /** Sets the linkStyle field. */
    public ConversionOptionsBuilder withLinkStyle(final LinkStyle value) {
        this.linkStyle = value;
        return this;
    }

    /** Sets the outputFormat field. */
    public ConversionOptionsBuilder withOutputFormat(final OutputFormat value) {
        this.outputFormat = value;
        return this;
    }

    /** Sets the includeDocumentStructure field. */
    public ConversionOptionsBuilder withIncludeDocumentStructure(final boolean value) {
        this.includeDocumentStructure = value;
        return this;
    }

    /** Sets the extractImages field. */
    public ConversionOptionsBuilder withExtractImages(final boolean value) {
        this.extractImages = value;
        return this;
    }

    /** Sets the maxImageSize field. */
    public ConversionOptionsBuilder withMaxImageSize(final long value) {
        this.maxImageSize = value;
        return this;
    }

    /** Sets the captureSvg field. */
    public ConversionOptionsBuilder withCaptureSvg(final boolean value) {
        this.captureSvg = value;
        return this;
    }

    /** Sets the inferDimensions field. */
    public ConversionOptionsBuilder withInferDimensions(final boolean value) {
        this.inferDimensions = value;
        return this;
    }

    /** Sets the maxDepth field. */
    public ConversionOptionsBuilder withMaxDepth(final Optional<Long> value) {
        this.maxDepth = value;
        return this;
    }

    /** Sets the excludeSelectors field. */
    public ConversionOptionsBuilder withExcludeSelectors(final List<String> value) {
        this.excludeSelectors = value;
        return this;
    }

    /** Sets the visitor field. */
    public ConversionOptionsBuilder withVisitor(final Optional<VisitorHandle> value) {
        this.visitor = value;
        return this;
    }

    /** Builds the ConversionOptions instance. */
    public ConversionOptions build() {
        return new ConversionOptions(headingStyle, listIndentType, listIndentWidth, bullets, strongEmSymbol,
                escapeAsterisks, escapeUnderscores, escapeMisc, escapeAscii, codeLanguage, autolinks, defaultTitle,
                brInTables, highlightStyle, extractMetadata, whitespaceMode, stripNewlines, wrap, wrapWidth,
                convertAsInline, subSymbol, supSymbol, newlineStyle, codeBlockStyle, keepInlineImagesIn, preprocessing,
                encoding, debug, stripTags, preserveTags, skipImages, linkStyle, outputFormat, includeDocumentStructure,
                extractImages, maxImageSize, captureSvg, inferDimensions, maxDepth.orElse(null), excludeSelectors,
                visitor.orElse(null));
    }
}
