// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:094484387808183514a801bab05d27e52c1d7d3d595e8913feed7cad1498eee3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Image metadata with source and dimensions.
 *
 * Captures {@code &lt;img&gt;} elements and inline {@code &lt;svg&gt;} elements with metadata
 * for image analysis and optimization.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageMetadata.Builder.class)
public record ImageMetadata(
    /**
     * Image source (URL, data URI, or SVG content identifier)
     */
    @JsonProperty("src") String src,
    /**
     * Alternative text from alt attribute (for accessibility)
     */
    @Nullable @JsonProperty("alt") String alt,
    /**
     * Title attribute (often shown as tooltip)
     */
    @Nullable @JsonProperty("title") String title,
    /**
     * Image dimensions as (width, height) if available
     */
    @Nullable @JsonProperty("dimensions") List<Integer> dimensions,
    /**
     * Image type classification
     */
    @JsonProperty("image_type") ImageType imageType,
    /**
     * Additional HTML attributes
     */
    @JsonProperty("attributes") Map<String, String> attributes
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String src = "";
private String alt = null;
private String title = null;
private List<Integer> dimensions = null;
        @JsonProperty("image_type")
private ImageType imageType = null;
private Map<String, String> attributes = Map.of();

        /** Sets the src field. */
        @JsonProperty("src")
        public Builder withSrc(final String value) {
            this.src = value;
            return this;
        }

        /** Sets the alt field. */
        @JsonProperty("alt")
        public Builder withAlt(final @Nullable String value) {
            this.alt = value;
            return this;
        }

        /** Sets the title field. */
        @JsonProperty("title")
        public Builder withTitle(final @Nullable String value) {
            this.title = value;
            return this;
        }

        /** Sets the dimensions field. */
        @JsonProperty("dimensions")
        public Builder withDimensions(final @Nullable List<Integer> value) {
            this.dimensions = value;
            return this;
        }

        /** Sets the imageType field. */
        @JsonProperty("image_type")
        public Builder withImageType(final ImageType value) {
            this.imageType = value;
            return this;
        }

        /** Sets the attributes field. */
        @JsonProperty("attributes")
        public Builder withAttributes(final Map<String, String> value) {
            this.attributes = value;
            return this;
        }

        /** Builds the ImageMetadata instance. */
        public ImageMetadata build() {
            return new ImageMetadata(
                src,
                alt,
                title,
                dimensions,
                imageType,
                attributes
            );
        }
    }
    // CPD-ON
}
