// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:99ae6cf66176c6d0327aa243e5ba9c8b9efa18ef193f12bff3b7e9a6c9dc4388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image source classification for proper handling and processing.
 *
 * Determines whether an image is embedded (data URI), inline SVG, external, or relative.
 */
public enum ImageType {
    /** Data URI embedded image (base64 or other encoding) */
    DataUri("datauri"),
    /** Inline SVG element */
    InlineSvg("inlinesvg"),
    /** External image URL (http/https) */
    External("external"),
    /** Relative image path */
    Relative("relative");

    /** The string value. */
    private final String value;

    ImageType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ImageType fromValue(final String value) {
        for (ImageType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
