// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7e2ceb761ed5e8b0aa412335bc65133d86773a4f21837c5e10ec88b3ef32a6f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image metadata with source and dimensions.
 *
 * Captures {@code &lt;img&gt;} elements and inline {@code &lt;svg&gt;} elements with metadata
 * for image analysis and optimization.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ImageMetadata(
    /**
     * Image source (URL, data URI, or SVG content identifier)
     */
    String src,
    /**
     * Alternative text from alt attribute (for accessibility)
     */
    @Nullable String alt,
    /**
     * Title attribute (often shown as tooltip)
     */
    @Nullable String title,
    /**
     * Image dimensions as (width, height) if available
     */
    @Nullable List<Integer> dimensions,
    /**
     * Image type classification
     */
    @JsonProperty("image_type") ImageType imageType,
    /**
     * Additional HTML attributes
     */
    Map<String, String> attributes
) {

    /**
     * Parse a {@code ImageMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException if the JSON cannot be deserialised.
     */
    public static ImageMetadata fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ImageMetadata.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse ImageMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
