// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8026f1bd5c957d54c05eab1d6eace9df28d99dae19dfe307c25ea4ef8344e6b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Context information passed to all visitor methods.
 *
 * Provides comprehensive metadata about the current node being visited,
 * including its type, tag name, position in the DOM tree, and parent context.
 *
 * ## Attributes
 *
 * Access attributes via NodeContext.attributes, which returns
 * {@code &amp;BTreeMap&lt;String, String&gt;}. When the context was built with
 * NodeContext.with_lazy_attributes (the hot path inside the converter),
 * the map is only materialized on the first call — if the visitor never reads
 * attributes, the allocation is skipped.
 *
 * ## Lifetimes
 *
 * String fields use Cow&lt;'_, str&gt; so the converter can pass slices directly
 * out of the parsed DOM without allocating. Visitor implementations that need
 * to outlive the callback should call NodeContext.into_owned.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = NodeContext.Builder.class)
public record NodeContext(
    @JsonProperty("node_type") NodeType nodeType,
    @JsonProperty("tag_name") String tagName,
    @JsonProperty("depth") long depth,
    @JsonProperty("index_in_parent") long indexInParent,
    @Nullable @JsonProperty("parent_tag") String parentTag,
    @JsonProperty("is_inline") boolean isInline
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for NodeContext deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("node_type")
        private NodeType nodeType;
        @JsonProperty("tag_name")
        private String tagName;
        private long depth;
        @JsonProperty("index_in_parent")
        private long indexInParent;
        @JsonProperty("parent_tag")
        @Nullable private String parentTag;
        @JsonProperty("is_inline")
        private boolean isInline;

        /** Sets the nodeType field. */
        @JsonProperty("node_type")
        public Builder withNodeType(final NodeType value) {
            this.nodeType = value;
            return this;
        }

        /** Sets the tagName field. */
        @JsonProperty("tag_name")
        public Builder withTagName(final String value) {
            this.tagName = value;
            return this;
        }

        /** Sets the depth field. */
        @JsonProperty("depth")
        public Builder withDepth(final long value) {
            this.depth = value;
            return this;
        }

        /** Sets the indexInParent field. */
        @JsonProperty("index_in_parent")
        public Builder withIndexInParent(final long value) {
            this.indexInParent = value;
            return this;
        }

        /** Sets the parentTag field. */
        @JsonProperty("parent_tag")
        public Builder withParentTag(final @Nullable String value) {
            this.parentTag = value;
            return this;
        }

        /** Sets the isInline field. */
        @JsonProperty("is_inline")
        public Builder withIsInline(final boolean value) {
            this.isInline = value;
            return this;
        }

        /** Constructs a NodeContext instance from the builder's current state. */
        public NodeContext build() {
            return new NodeContext(
                nodeType,
                tagName,
                depth,
                indexInParent,
                parentTag,
                isInline
            );
        }
    }
    // CPD-ON
}
