// DO NOT EDIT - auto-generated by alef
// alef:hash:32481feb2a73dcc1b987f119cbb3057300b8cc4d51c0a0d108b116427b3a3127
package dev.kreuzberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
