// DO NOT EDIT - auto-generated by alef
// alef:hash:916d4bc28e07ef28a825e0f6996d70e0391fb2f85136a4473449809107d57a63
package dev.kreuzberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
    /** Creates a new PanicException with the given message. */
    public PanicException(final String message) {
        super(message);
    }

    /** Creates a new PanicException with the given message and cause. */
    public PanicException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
