// DO NOT EDIT - auto-generated by alef
// alef:hash:8beb68eff11670b72d6c7c692015eddc4cef91ff579dcc166a0560a84f069266
package dev.kreuzberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
    /** Creates a new PanicException with the given message. */
    public PanicException(final String message) {
        super(message);
    }

    /** Creates a new PanicException with the given message and cause. */
    public PanicException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
