// DO NOT EDIT - auto-generated by alef
// alef:hash:507aa96f89b492bb22c83998d7d9b4579f78cd71849888f2f59ed580959b41f2
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML parsing error
 */
public class ParseErrorException extends ConversionErrorException {
    /** Creates a new ParseErrorException with the given message. */
    public ParseErrorException(final String message) {
        super(message);
    }

    /** Creates a new ParseErrorException with the given message and cause. */
    public ParseErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
