// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

/** HTML parsing error */
public class ParseErrorException extends ConversionErrorException {
  public ParseErrorException(String message) {
    super(message);
  }

  public ParseErrorException(String message, Throwable cause) {
    super(message, cause);
  }
}
