// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:db7c61b02f2a6649cb841203ecfec9120fe8942139442c5e8cb3592f04807b70
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Partial update for {@code PreprocessingOptions}.
 *
 * This struct uses {@code Option&lt;T&gt;} to represent optional fields that can be selectively updated.
 * Only specified fields (Some values) will override existing options; None values leave the
 * corresponding fields unchanged when applied via PreprocessingOptions::apply_update.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PreprocessingOptionsUpdate(
    /**
     * Optional global preprocessing enablement override
     */
    @Nullable Boolean enabled,
    /**
     * Optional preprocessing preset level override (Minimal, Standard, Aggressive)
     */
    @Nullable String preset,
    /**
     * Optional navigation element removal override (nav, breadcrumbs, menus, sidebars)
     */
    @Nullable @JsonProperty("remove_navigation") Boolean removeNavigation,
    /**
     * Optional form element removal override (forms, inputs, buttons, etc.)
     */
    @Nullable @JsonProperty("remove_forms") Boolean removeForms
) {

    /**
     * Parse a {@code PreprocessingOptionsUpdate} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException if the JSON cannot be deserialised.
     */
    public static PreprocessingOptionsUpdate fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, PreprocessingOptionsUpdate.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse PreprocessingOptionsUpdate from JSON: " + e.getMessage(), e);
        }
    }
}
