// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:534c8df0bc3f7469c4423cae47ee607e9cc24197fa0a83a62d2e5894d284630f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * HTML preprocessing options for document cleanup before conversion.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PreprocessingOptions(
    /**
     * Enable HTML preprocessing globally
     */
    boolean enabled,
    /**
     * Preprocessing preset level (Minimal, Standard, Aggressive)
     */
    PreprocessingPreset preset,
    /**
     * Remove navigation elements (nav, breadcrumbs, menus, sidebars)
     */
    @JsonProperty("remove_navigation") boolean removeNavigation,
    /**
     * Remove form elements (forms, inputs, buttons, etc.)
     */
    @JsonProperty("remove_forms") boolean removeForms
) {
    public static PreprocessingOptions defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
