// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e776b20452760236aa1199da3456cfa67eee1192600fdafbb6f5be74e17d619
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Partial update for {@code PreprocessingOptions}.
 *
 * This struct uses {@code Option&lt;T&gt;} to represent optional fields that can be selectively updated.
 * Only specified fields (values) will override existing options; null values leave the
 * corresponding fields unchanged when applied via PreprocessingOptions.apply_update.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PreprocessingOptionsUpdate(
    /**
     * Optional global preprocessing enablement override
     */
    @Nullable Boolean enabled,
    /**
     * Optional preprocessing preset level override (Minimal, Standard, Aggressive)
     */
    @Nullable PreprocessingPreset preset,
    /**
     * Optional navigation element removal override (nav, breadcrumbs, menus, sidebars)
     */
    @Nullable @JsonProperty("remove_navigation") Boolean removeNavigation,
    /**
     * Optional form element removal override (forms, inputs, buttons, etc.)
     */
    @Nullable @JsonProperty("remove_forms") Boolean removeForms
) {
}
