// DO NOT EDIT - auto-generated by alef
// alef:hash:c4123217bb42e6cbe7cc59851037f301994cdb660a4a2934d8b056b2b5fc5adf
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
    /** Creates a new SanitizationErrorException with the given message. */
    public SanitizationErrorException(final String message) {
        super(message);
    }

    /** Creates a new SanitizationErrorException with the given message and cause. */
    public SanitizationErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
