// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7b1fa4f19a16d2a5c2be32e9dab389bda398eb40d18035acf140a55c3466c0e7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A structured table grid with cell-level data including spans.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TableGrid(int rows, int cols, List<GridCell> cells) {
}
