// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5034ce9d858a5e8aaa780b4d08e6a399d29f3a15ae5d486e45d6db9bf22080bb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * An inline text annotation with byte-range offsets.
 *
 * Annotations describe formatting (bold, italic, etc.) and links within a node's text content.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TextAnnotation(int start, int end, AnnotationKind kind) {

    /**
     * Parse a {@code TextAnnotation} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException
     *             if the JSON cannot be deserialised.
     */
    public static TextAnnotation fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, TextAnnotation.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse TextAnnotation from JSON: " + e.getMessage(), e);
        }
    }
}
