// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum TextDirection {
  LeftToRight("ltr"),
  RightToLeft("rtl"),
  Auto("auto");

  private final String value;

  TextDirection(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @JsonCreator
  public static TextDirection fromValue(String value) {
    for (TextDirection e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown value: " + value);
  }
}
